force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/DD_Transaction_dd_mm__c.field-meta.xml
<CustomField>
    <fullName>DD_Transaction_dd_mm__c</fullName>
    <formula>MID(TEXT(Membership__r.Renewal_Date__c),9,2) &amp; &apos;/&apos; &amp; MID(TEXT(Membership__r.Renewal_Date__c),6,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DD Transaction DD/MM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Mandate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Amount__c</fullName>
    <label>Mandate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Renewal_Payment_Pending__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Payment_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a direct debit payment is due from a recent renewal, but that a transaction has not yet been generated.</description>
    <inlineHelpText>Indicates that a direct debit payment is due from a recent renewal, but that a transaction has not yet been generated.</inlineHelpText>
    <label>Renewal Payment Pending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Name__c</fullName>
    <formula>Payment_Method__r.Bank_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <formula>Payment_Method__r.Bank_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sort_Code__c</fullName>
    <formula>Payment_Method__r.Sort_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Sort Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>CASESAFEID(Payment_Method__r.Membership__r.Id)</formula>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchCreateDDTransactions.cls
global class BatchCreateDDTransactions implements Database.Batchable<sObject> {

//  global String QUERY = 'select id,Mandate_Amount__c,(select id from Transactions__r where Transaction_Type__c !=\'0N\' and Transaction_Type__c !=\'0C\') from Payment_Method__c where DD_Transaction_dd_mm__c = :ddmm and status__c=\'Active\' and recordtypeid=:sc.PaymentMethodDDRecordTypeId '; 
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        constants sc = new constants();
        
        Datetime D = Datetime.now().addDays(-1);
        String ddmm = D.format('dd/MM');
        
        system.debug(ddmm);
        
        String QUERY = 'select id,createddate,Membership__r.Date_Joined__c,Mandate_Amount__c,Sort_Code__c,Bank_Account_Name__c,Bank_Account_Number__c, (select id from Transactions__r where Transaction_Type__c !=\'0N\' and Transaction_Type__c !=\'0C\' and Status__c!=\'Pending\') from Payment_Method__c where DD_Transaction_dd_mm__c = :ddmm and mandate_amount__c>0 and status__c=\'Active\' and Renewal_Payment_Pending__c = true and recordtypeid=\''+sc.PaymentMethodDDRecordTypeId+'\''; 

        if(Test.isRunningTest()) {
            return Database.getQueryLocator(QUERY + ' LIMIT 200');
        }

        
        //ddmm ='07/12';
        
        return Database.getQueryLocator(QUERY);
    }

    global void execute(Database.BatchableContext BC, List<Payment_Method__c> scope) {
        constants sc = new constants();

        List<Transaction__c> transactions = new List<Transaction__c>();
        List<Payment_Method__c> paymentMethodsToUpdate = new List<Payment_Method__c>();
		
		BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
		Long days8Milliseconds = 691200000;

        for(Payment_Method__c pm : scope) {
        	if(system.now().addDays(-10)>pm.Membership__r.Date_Joined__c){
	            Transaction__c t = new Transaction__c(
	//                                       Customer_Sort_Code__c = pm.Sort_Code__c,
	//                                       Customer_Account_Name__c = pm.Bank_Account_Name__c,
	//                                       Customer_Account_Number__c = pm.Bank_Account_Number__c,
	                                         Transaction_Date__c = date.today(),
	                                         Amount__c = pm.Mandate_Amount__c,
	                                         Status__c = 'Pending',
	                                         Payment_Method__c = pm.Id,  
	                                         RecordTypeid = sc.trddebitRecordTypeId                        
	                                );
	            if(pm.transactions__r.size()>0){
	                t.Transaction_Type__c = '17';
	            }
				else
				{
					t.Transaction_Type__c = '01';
				}
				if(pm.CreatedDate.adddays(10)>datetime.now()){
					t.Transaction_Date__c = 	BusinessHours.add(bh.id, pm.createddate, days8Milliseconds).date();
				}
				transactions.add(t);
	            
	        }

	        // Set Renewal_Payment_Pending__c flag back to false to ensure that another payment isn't processed
	        // until the next renewal if the membership term is longer than a year.
	        pm.Renewal_Payment_Pending__c = false;
	        paymentMethodsToUpdate.add(pm);
        }
        
        insert transactions; 
        update paymentMethodsToUpdate;


    }

    global void finish(Database.BatchableContext BC) {}
		
}