force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/sectionSelectWrapper.cls
public class sectionSelectWrapper {

	public club_product__c s {get; set;}
	public Decimal price {get; set;}
	public Boolean selected {get; set;}
	public List<Price__c> prices {get;set;}
 
	public sectionSelectWrapper(club_product__c sec) {
		this.s = sec;
		this.selected = false;
	}

	public sectionSelectWrapper(club_product__c sec,Decimal price) {
		system.debug('creating a sectionSelectWrapper: ' + sec);
		this.s = sec;
		this.price = price;
		this.selected = false;
	}
	
	public sectionSelectWrapper(club_product__c sec, List<Price__c> prices){
		this.s = sec;
		this.prices = prices;
		this.selected = false;
	}
	
	public sectionSelectWrapper(club_product__c sec, List<Price__c> prices, boolean sel){
		this.s = sec;
		this.prices = prices;
		this.selected = sel;
	}

	public sectionSelectWrapper(club_product__c sec,boolean sel) {
		this.s = sec;
		this.selected = sel;
	}

	public sectionSelectWrapper(club_product__c sec,Decimal price,boolean sel) {
		this.s = sec;
		this.price = price;
		this.selected = sel;
	}
}