force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Allowed_Payment_Types__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Payment_Types__c</fullName>
    <label>Allowed Payment Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Type</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please select a valid membership type.</errorMessage>
        <filterItems>
            <field>Club_Product__c.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Show_in_New_Membership_Picklist__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Visible_to_Admin_Users_Only__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>New Memberships</relationshipLabel>
    <relationshipName>New_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentTypeSelectorController.cls
/*
* @who   Patrick Duncan <patrick.duncan@weare4c.com>
* @what  Apex controller for the NewMembershipPaymentTypeSelector lightning component 
* @when  25/7/2019
*/
public with sharing class PaymentTypeSelectorController {

	/*
	*  @description Function that gets the selected values from the multi-select picklist Allowed_Payment_Types__c for the Club_Product__c record that a new membership has a lookup to
    *  @param  recordId  The new membership's record id
    *  @return the values selected on Allowed_Payment_Types__c
    */
	@AuraEnabled
	public static List<String> getAllowedPaymentTypes(Id recordId){
		List<Lead> results = [SELECT Id, Membership_Type__c FROM Lead WHERE Id = :recordId];
		List<Club_Product__c> product = [SELECT Id, Allowed_Payment_Types__c FROM Club_Product__c WHERE Id = :results.get(0).Membership_Type__c];
		return product.get(0).Allowed_Payment_Types__c.split(';');
 	}

 	/*
	*  @description Function that updates the billing info and Payment_Method__c fields on a new membership
    *  @param  recordId  The new membership's record id
    *          paymentMethod    The selected Payment_Method__c
    *          paymentDetails   List of size 3 containing billing data - should be null if paymentMethod = 'Cash/Cheque'
    */
	@AuraEnabled
	public static void saveNewMembershipBillingDetails(Id recordId, String paymentMethod, String[] paymentDetails){
		List<Lead> results = [SELECT Id FROM Lead WHERE Id = :recordId];
		results.get(0).Payment_Method__c = paymentMethod;
		if(paymentMethod=='Direct Debit'){
			results.get(0).Bank_Account_Name__c = paymentDetails[0];
			results.get(0).Bank_Account_Number__c = paymentDetails[1];
			results.get(0).Sort_Code__c = paymentDetails[2];
		}

		try{
			update results;

		}
		catch(Exception e){
			System.debug('ERROR SAVING NEW MEMBERSHIP: '+e.getCause()+' '+e.getMessage());
		}
	}    
}