force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Allowed_Payment_Types__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Payment_Types__c</fullName>
    <label>Allowed Payment Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Type</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please select a valid membership type.</errorMessage>
        <filterItems>
            <field>Club_Product__c.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Show_in_New_Membership_Picklist__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Club_Product__c.Visible_to_Admin_Users_Only__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>New Memberships</relationshipLabel>
    <relationshipName>New_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentTypeSelectorControllerTest.cls
@isTest
public class PaymentTypeSelectorControllerTest {
    
    @testSetup
    static void testSetup(){
        Club_Product__c clubProduct = new Club_Product__c(Allowed_Payment_Types__c='Direct Debit;Debit/Credit Card');
        insert clubProduct;
        Lead l = new Lead(Email='email@test.com',FirstName='Test',LastName='Lead',Company='Test',Membership_Type__c=clubProduct.Id);
        insert l;
	}
    
    @isTest
    static void test_getAllowedPaymentTypes(){
        Lead l = [SELECT Id, Email FROM Lead LIMIT 1];
        Test.startTest();
        	List<String> paymentTypes = PaymentTypeSelectorController.getAllowedPaymentTypes(l.Id);
        Test.stopTest();
        
        System.assert(paymentTypes.contains('Direct Debit'));     
	}
        
    @isTest
    static void test_saveNewMembershipBillingDetails(){
        Lead l = [SELECT Id, Bank_Account_Name__c, Bank_Account_Number__c, Sort_Code__c FROM Lead LIMIT 1];
        Test.startTest();
        PaymentTypeSelectorController.saveNewMembershipBillingDetails(l.Id, 'Direct Debit', new List<String>{'Acc name','12345678','123456'});
        Test.stopTest();
        Lead le = [SELECT Id, Bank_Account_Name__c, Bank_Account_Number__c, Sort_Code__c FROM Lead LIMIT 1];
        System.assertEquals('Acc name',le.Bank_Account_Name__c);     
        System.assertEquals('12345678',le.Bank_Account_Number__c);     
        System.assertEquals('123456',le.Sort_Code__c);     

	}

}