force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Membership_Length__c.field-meta.xml
<CustomField>
    <fullName>Membership_Length__c</fullName>
    <label>Membership Length (Months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Associate_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_First_Name__c</fullName>
    <label>Associate Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Surname__c</fullName>
    <label>Associate Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_Title__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Title__c</fullName>
    <label>Associate Member Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Rev</fullName>
            </value>
            <value>
                <fullName>Sir</fullName>
            </value>
            <value>
                <fullName>Capt</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Sgt</fullName>
            </value>
            <value>
                <fullName>Corp</fullName>
            </value>
            <value>
                <fullName>Dr</fullName>
            </value>
            <value>
                <fullName>Prof</fullName>
            </value>
            <value>
                <fullName>Cllr</fullName>
            </value>
            <value>
                <fullName>Rt Hon</fullName>
            </value>
            <value>
                <fullName>Lady</fullName>
            </value>
            <value>
                <fullName>Lord</fullName>
            </value>
            <value>
                <fullName>Dame</fullName>
            </value>
            <value>
                <fullName>Duke</fullName>
            </value>
            <value>
                <fullName>Duchess</fullName>
            </value>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Countess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_1_First_Name__c</fullName>
    <label>Child 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_1_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_1_Surname__c</fullName>
    <label>Child 1 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_2_First_Name__c</fullName>
    <label>Child 2 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_2_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_2_Surname__c</fullName>
    <label>Child 2 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_3_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_3_First_Name__c</fullName>
    <label>Child 3 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_3_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_3_Surname__c</fullName>
    <label>Child 3 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_4_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_4_First_Name__c</fullName>
    <label>Child 4 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_4_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_4_Surname__c</fullName>
    <label>Child 4 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_5_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_5_First_Name__c</fullName>
    <label>Child 5 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_5_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_5_Surname__c</fullName>
    <label>Child 5 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_6_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_6_First_Name__c</fullName>
    <label>Child 6 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_6_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_6_Surname__c</fullName>
    <label>Child 6 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasAssociate__c.field-meta.xml
<CustomField>
    <fullName>hasAssociate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Associate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasPartner__c.field-meta.xml
<CustomField>
    <fullName>hasPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Joining_Fee_Waived__c.field-meta.xml
<CustomField>
    <fullName>Joining_Fee_Waived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Joining Fee Waived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length (m)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Children__c</fullName>
    <label>Number of Children</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Email__c</fullName>
    <label>Secondary Member Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_First_Name__c</fullName>
    <label>Secondary Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Surname__c</fullName>
    <label>Secondary Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateMemberTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
private class CreateMemberTest {
    //Test a regular use case (NOT with Young Camper membership type)
    @IsTest
    static void testCreateMembershipFromLead() {
        Date joinedDate = System.today();
        Id membershipCodeRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Club_Product__c' AND DeveloperName = 'Membership_Code' LIMIT 1].Id;

        String productName = 'Online';

        Club_Product__c clubProduct = new Club_Product__c(
                RecordTypeId = membershipCodeRecordTypeId,
                Name = productName,
                Product_Detail__c = 'Online Membership',
                Active__c = true,
                Show_in_New_Membership_Picklist__c = true,
                Sections_Allowed__c = true,
                Associate_Allowed__c = true,
                PartnerAllowed__c = true,
                DD_Payment_Allowed__c = true,
                Membership_Length__c = 24
        );
        insert clubProduct;

        Lead theLead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company = 'Testco', hasPartner__c = true,
                Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com', Joining_Fee_Waived__c = false,
                Number_of_Children__c = '6', Child_1_First_Name__c = 'Child 1', Child_1_Surname__c = 'Golf', Child_2_First_Name__c = 'Child 2',
                Child_2_Surname__c = 'Golf', Child_3_First_Name__c = 'Child 3', Child_3_Surname__c = 'Golf', Child_4_First_Name__c = 'Child 4',
                Child_4_Surname__c = 'Golf', Child_5_First_Name__c = 'Child 5', Child_5_Surname__c = 'Golf', Child_6_First_Name__c = 'Child 6',
                Child_6_Surname__c = 'Golf', Payment_Method__c = 'Direct Debit', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
                Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.', Sort_Code__c = '202020', Bank_Account_Name__c = 'Test Account',
                Bank_Account_Number__c = '41111111', Bank_Name__c = 'Test', Membership_Code__c = 'Online', Joining_Date__c = joinedDate, PostalCode = 'TE1 0YZ',
                Child_1_Date_of_Birth__c = Date.today(), Child_2_Date_of_Birth__c = Date.today(), Child_3_Date_of_Birth__c = Date.today(),
                Child_4_Date_of_Birth__c = Date.today(), Child_5_Date_of_Birth__c = Date.today(), Child_6_Date_of_Birth__c = Date.today(),
                Associate_Member_Date_of_Birth__c = Date.today(), Secondary_Member_Title__c = 'Mr.');
        insert theLead;

        new CreateMember().createMembershipfromLead(theLead, '', '');

        System.assertEquals(1, [SELECT COUNT() FROM Account], 'There should be only one Account record!');
        System.assertEquals(9, [SELECT COUNT() FROM Contact], 'There should be only nine Contact records (Member, Second Member, Associate Member and 6 children!)!');
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE IsConverted = TRUE], 'There should be only one Lead record with IsConverted = TRUE');

        Account convertedAccount = [SELECT Id, Name, Membership_Type_Name__c FROM Account LIMIT 1];
        System.assertEquals(productName, convertedAccount.Membership_Type_Name__c, 'Membership Type Name should be ' + productName + '!');
        System.assertEquals(theLead.LastName, convertedAccount.Name, 'Lead\'s LastName and Account\'s Name should be the same!');
    }

    // Test createMembershipfromLead using a Lead record of 'Young Camper' Membership Type
    @IsTest
    static void testCreateMembershipFromLead2() {
        Id membershipCodeRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Club_Product__c' AND DeveloperName = 'Membership_Code' LIMIT 1].Id;

        Club_Product__c clubProduct = new Club_Product__c(
                RecordTypeId = membershipCodeRecordTypeId,
                Name = 'Young Camper',
                Product_Detail__c = 'Young Camper',
                Active__c = true,
                Show_in_New_Membership_Picklist__c = true,
                Auto_Renew__c = true,
                Min_Age_for_Membership__c = 18,
                Max_Age_for_Membership__c = 25,
                Sections_Allowed__c = true,
                Associate_Allowed__c = true,
                PartnerAllowed__c = true,
                DD_Payment_Allowed__c = true,
                Cash_Payment_Allowed__c = true,
                Membership_Length__c = 12,
                Renewable__c = true,
                Allowed_Payment_Types__c = 'Cash/Cheque'
        );
        insert clubProduct;

        Price__c price = new Price__c(
                Product__c = clubProduct.Id,
                Price__c = 0,
                Start_Date__c = Date.today().addDays(-10),
                Joining_Fee__c = 0,
                Payment_Type__c = 'Cash/Cheque'
        );
        insert price;

        Date memberBirthday = Date.today().addYears(-20).addMonths(-2);

        Lead theLead = new Lead(
                FirstName = 'John', LastName = 'Smith', Company = 'Smith',
                Age_Concession__c = false, Amount__c = 0, Application_Source__c = 'Telephone',
                Email = 'john.smith@test.com', Membership_Code__c = 'Young Camper', Membership_Type__c = clubProduct.Id,
                Street = 'Green Str.', City = 'London', State = 'Fullham', PostalCode = '452462', Country = 'UK',
                Camping_Unit__c = 'Tent', Length__c = 1, Width__c = 1, Height__c = 1,
                Lead_Member_Date_of_Birth__c = memberBirthday
        );
        insert theLead;

        new CreateMember().createMembershipfromLead(theLead, '', '');

        System.assertEquals(1, [SELECT COUNT() FROM Account], 'There should be only one Account record!');
        System.assertEquals(1, [SELECT COUNT() FROM Contact], 'There should be only one Contact record!');
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE IsConverted = TRUE], 'There should be only one Lead record with IsConverted = TRUE');

        Account convertedAccount = [SELECT Id, Name, Renewal_Date__c FROM Account LIMIT 1];

        System.debug('memberBirthday = ' + memberBirthday);
        System.debug('convertedAccount.Renewal_Date__c = ' + convertedAccount.Renewal_Date__c);

        System.assertEquals(theLead.LastName, convertedAccount.Name, 'Lead\'s LastName and Account\'s Name should be the same!');
        System.assert(convertedAccount.Renewal_Date__c.month() == memberBirthday.month()
                        && convertedAccount.Renewal_Date__c.day() == memberBirthday.day(),
                'Renewal Date for members with Young Camper membership type should be equal to the next member\'s birthday!');
    }

//    static testMethod void CreateMemberTest() {
//        // TO DO: implement unit test
//        Date joinedDate = System.today();
//        RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName = 'Lead' limit 1];
//        RecordType rt1 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName = 'Membership_Code' limit 1];
//
//        Account acc = new Account();
//        Association__c da = new Association__c();
//        Association__c region = new Association__c();
//        DA_Postcode__c pc = new DA_Postcode__c();
//        Club_Product__c cp = new Club_Product__c();
//        Price__c p = new Price__c();
//        Date pStartDate = Date.newInstance(2016, 09, 24);
//        constants c = new constants();
//
//
//        region.RecordTypeId = c.accRegionRecordTypeId;
//        region.Name = 'Testing Region';
//        region.Region_Code__c = '101';
//        insert region;
//
//
//        pc.Association_Name__c = da.Id;
//        pc.Association_Code__c = da.Region_Code__c;
//        pc.Parent_Region_Name__c = region.Name;
//        pc.Postcode_Part_1__c = 'TE1';
//        insert pc;
//
//        cp.RecordTypeId = rt1.Id;
//        cp.Name = 'Online';
//        cp.Product_Detail__c = 'Online Membership';
//        cp.Active__c = true;
//        cp.Show_in_New_Membership_Picklist__c = true;
//        cp.Sections_Allowed__c = true;
//        cp.Associate_Allowed__c = true;
//        cp.PartnerAllowed__c = true;
//        cp.DD_Payment_Allowed__c = true;
//        cp.Membership_Length__c = 24;
//        insert cp;
//
//
//        acc.Name = 'Test Membership';
//        acc.District_Association__c = da.Id;
//        acc.BillingPostalCode = 'TE1 0YZ';
//        acc.Date_Joined__c = system.today();
//        acc.Membership_Code__c = cp.Id;
//        //acct.Renewal_Date__c =
//        insert acc;
//
//        p.Product__c = cp.Id;
//        p.Price__c = 36.00;
//        p.Start_Date__c = pStartDate;
//        p.Payment_Type__c = 'Direct Debit';
//        p.Joining_Fee__c = 15.50;
//        insert p;
//        // Account acc = new Account (Name = 'Patel', Date_Joined__c = system.today());
//        //insert acc;
//
//        //Contact con = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId = rt.Id, Account = acc, mobilephone = '07985468888', email = 'tony@tony.com');
//        //insert con;
//        //SalesProcess process = new
//        Lead lead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company = 'Testco', hasPartner__c = true,
//                Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com', Joining_Fee_Waived__c = false,
//                Number_of_Children__c = '6', Child_1_First_Name__c = 'Child 1', Child_1_Surname__c = 'Golf', Child_2_First_Name__c = 'Child 2',
//                Child_2_Surname__c = 'Golf', Child_3_First_Name__c = 'Child 3', Child_3_Surname__c = 'Golf', Child_4_First_Name__c = 'Child 4',
//                Child_4_Surname__c = 'Golf', Child_5_First_Name__c = 'Child 5', Child_5_Surname__c = 'Golf', Child_6_First_Name__c = 'Child 6',
//                Child_6_Surname__c = 'Golf', Payment_Method__c = 'Direct Debit', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
//                Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.', Sort_Code__c = '202020', Bank_Account_Name__c = 'Test Account',
//                Bank_Account_Number__c = '41111111', Bank_Name__c = 'Test', Membership_Code__c = 'Online', Joining_Date__c = joinedDate, postalcode = 'TE1 0YZ',
//                Child_1_Date_of_Birth__c = Date.today(), Child_2_Date_of_Birth__c = Date.today(), Child_3_Date_of_Birth__c = Date.today(),
//                Child_4_Date_of_Birth__c = Date.today(), Child_5_Date_of_Birth__c = Date.today(), Child_6_Date_of_Birth__c = Date.today(),
//                Associate_Member_Date_of_Birth__c = Date.today(), Secondary_Member_Title__c = 'Mr.');
//        insert lead;
//
//        CreateMember cm = new CreateMember();
//
//        Database.LeadConvertResult lc = cm.createMembershipfromLead(lead, '', '');
//
//        //cm.createMembershipfromLead(lead, 'Paid');
//
//        // Database.LeadConvert lc = new database.LeadConvert();
//
//
//        //Database.LeadConvertResult lcr = cm.createMembershipfromLead(lead,'000111','hello');
//
//
//    }

    /*static testMethod void CreateMemberTestWithDD() {
          // TO DO: implement unit test

          RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];

          Account acc = new Account (Name = 'Patel', Date_Joined__c = system.today());
          insert acc;

         Contact con = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId =rt.Id, Account = acc);
         insert con;

         Lead lead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
                                 Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
                                 Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2',
                                 Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
                                 Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6',
                                 Child_6_Surname__c='Golf', Payment_Method__c='Direct Debit', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
                                  Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.');
         insert lead;

         CreateMember cm = new CreateMember();
         cm.createMembershipfromLead(lead, 'paid');


       }

    static testMethod void CreateMemberTestWithCC() {
          // TO DO: implement unit test

          RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];

          Account acc = new Account (Name = 'Patel', Date_Joined__c = system.today());
          insert acc;

         Contact con = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId =rt.Id, Account = acc);
         insert con;

         Lead lead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
                                 Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
                                 Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2',
                                 Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
                                 Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6',
                                 Child_6_Surname__c='Golf', Payment_Method__c='Cash / Cheque', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
                                  Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.');
         insert lead;

         CreateMember cm = new CreateMember();
         cm.createMembershipfromLead(lead, 'Paid');


       }*/

}