force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NewMembershipUtilTest.cls
/**
 *  @who    Jordan Fraser jordan.fraser@weare4c.com
 *  @when   08/07/2019
 *  @what   Test methods for NewMembershipUtil.
 */

@isTest
public class NewMembershipUtilTest {


	@isTest static void testCalculateTotalSectionPricePositive() {

		String clubProdSectionRecordTypeId = Schema.SObjectType.Club_Product__c.RecordTypeInfosByName.get('Section').RecordTypeId;

		// Set up Club_Product__c records.
		Club_Product__c[] products = new List<Club_Product__c>();

		Club_Product__c product1 = new Club_Product__c(Name = 'product1',
														RecordTypeId = clubProdSectionRecordTypeId);
		products.add(product1);

		Club_Product__c product2 = new Club_Product__c(Name = 'product2',
														RecordTypeId = clubProdSectionRecordTypeId);
		products.add(product2);

		Club_Product__c product3 = new Club_Product__c(Name = 'product3',
														RecordTypeId = clubProdSectionRecordTypeId);
		products.add(product3);

		insert products;

		// Set up Price__c records.
		Price__c[] prices = new List<Price__c>();
		for (Club_Product__c product : products) {
			Price__c price = new Price__c(Price__c = 5,
										Product__c = product.id,
										Start_Date__c = Date.newInstance(1970, 01, 01),
										End_Date__c = Date.newInstance(2270, 01, 01));
			prices.add(price);

		}
		insert prices;



		// Run test.
		Test.startTest();
		List<String> inputs = new List<String>();
		for (Integer i = 0; i < 100; i++) {
			inputs.add('product1:product2:product3');
		}
		Decimal[] outputs = NewMembershipUtil.calculateTotalSectionPrice(inputs);
		Test.stopTest();

		// Validate results.
		for (Decimal output : outputs) {
			System.assertEquals(15.0, output);
		}


	}

	@isTest static void testCalculateTotalSectionPriceNegative() {
		// Run test.
		Test.startTest();
		List<String> inputs = new List<String>();
		for (Integer i = 0; i < 100; i++) {
			inputs.add('product1:product2:product3');
		}
		Decimal[] outputs = NewMembershipUtil.calculateTotalSectionPrice(inputs);
		Test.stopTest();

		// Validate results.
		for (Decimal output : outputs) {
			System.assertEquals(0, output);
		}
	}
	
}