force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Allowed_Payment_Types__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Payment_Types__c</fullName>
    <label>Allowed Payment Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeMembershipPaymentController.cls
public with sharing class ChangeMembershipPaymentController {

    @AuraEnabled(Cacheable=true)
    public static List<String> getPaymentOptions(String membershipCodes){

        List<Club_Product__c> clubProducts = [SELECT Allowed_Payment_Types__c FROM Club_Product__c WHERE Name = :membershipCodes];


        if(clubProducts.isEmpty()) return new List<String>();

        List<String> paymentTypes = new List<String>();

        if(clubProducts.get(0).Allowed_Payment_Types__c != null){
            for(String paymentType : clubProducts.get(0).Allowed_Payment_Types__c.split(';')){
                paymentTypes.add(paymentType);
            }
        }

        return paymentTypes;
    }

    @AuraEnabled
    public static String updateLead(String leadJson) {

        Lead lead = (Lead) JSON.deserialize(leadJson, Lead.class);

        try {
            update lead;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return lead.Id;
    }
}