force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Card_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Card_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Card Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Cash_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Cash_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cash Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/isOverseas__c.field-meta.xml
<CustomField>
    <fullName>isOverseas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOverseas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>IMAGE(
CASE( Name ,
&quot;50 Years&quot;, &quot;/resource/0000000000000/fifty&quot;, /* fifty*/
&quot;Certificated Sites - Digital&quot;, &quot;/resource/0000000000000/other&quot;, /* other*/
&quot;CHH - Digital&quot;, &quot;/resource/0000000000000/chh3&quot;, /* chh*/
&quot;Complimentary&quot;, &quot;/resource/0000000000000/complimentary&quot;, /* complimentary*/
&quot;Honorary&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Honorary (VP)&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Digital&quot;, &quot;/resource/0000000000000/digital&quot;, /* online*/
&quot;Overseas - Digital Membership&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Overseas - Paper&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Paper&quot;, &quot;/resource/0000000000000/paper2&quot;, /* paper*/
&quot;Press Card Holder&quot;, &quot;/resource/0000000000000/press&quot;, /* press*/
&quot;Senior Youth - Digital&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Senior Youth - Paper&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Staff&quot;, &quot;/resource/0000000000000/staff&quot;, /* staff*/
&quot;Technical&quot;, &quot;/resource/0000000000000/tech&quot;, /* tech*/
&quot;Temporary Overseas Membership&quot;, &quot;/resource/0000000000000/tempoverseas&quot;, /* tempoverseas*/
&quot;Veteran - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran - Paper&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran Overseas - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Vice President&quot;, &quot;/resource/0000000000000/vp2&quot;, /* vp*/
&quot;Youth - Digital&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Youth - Paper&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Site Paper&quot;, &quot;/resource/0000000000000/ccc_site_paper&quot;, /* site*/
&quot;Site Digital&quot;, &quot;/resource/0000000000000/ccc_site_digital&quot;, /* site*/
&quot;/resource/0000000000000/trans_circle&quot;), /* Other */
&quot;Membership Status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Membership Code</fullName>
            </value>
            <value>
                <fullName>Associate Membership</fullName>
            </value>
            <value>
                <fullName>Section Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Visible_to_Admin_Users_Only__c.field-meta.xml
<CustomField>
    <fullName>Visible_to_Admin_Users_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible to Admin Users Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/website_product_prompt__c.field-meta.xml
<CustomField>
    <fullName>website_product_prompt__c</fullName>
    <label>website product prompt</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Change_Fee__c.field-meta.xml
<CustomField>
    <fullName>Change_Fee__c</fullName>
    <label>Change Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Joining_Fee__c.field-meta.xml
<CustomField>
    <fullName>Joining_Fee__c</fullName>
    <label>Joining Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price_Description__c.field-meta.xml
<CustomField>
    <fullName>Price_Description__c</fullName>
    <label>Price Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price_Detail__c.field-meta.xml
<CustomField>
    <fullName>Price_Detail__c</fullName>
    <label>Price Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Price_Prompt__c</fullName>
    <label>Price Prompt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Show_in_Web__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Web__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show in Web</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Products.cls
@RestResource(urlMapping='/Products/*')
global class  Products {

        global class Error{
            global integer id;
            global String Message;
        }

        global class Price {
            Global String PaymentType;
            global Date StartDate;
            global Date EndDate;
            global Decimal Price;
            global Decimal JoiningFee;
            global String PriceDescription;
            global String PricePrompt;
            global boolean ShowinWeb;
            global String PriceDetail;
        }
        global class Result{
            global String status;
            global List<Error> Errors;
            global List<MProductPrice> Memberships;
            global List<ProductPrice> Associate;
            global List<ProductPrice> Sections;
        }
        
        global virtual class ProductPrice {
            global String ProductId;
            global String ProductName;
            global String ProductDetail;
            global String Description;
            global String ProductPrompt;
            global List<Price> Prices;
        }
        
        global class MProductPrice extends ProductPrice{
            global boolean ShowInNewMembershipPicklist;
            global boolean OverseasMembership;
            global boolean SectionsAllowed;
            global boolean AssociateAllowed;
            global boolean PartnerAllowed;
            //global boolean CashPaymentAllowed;
            //global boolean CardPaymentAllowed;
            //global boolean DDPaymentAllowed;
        }
        
    
    @HttpGet
    global static Result getProductPriceDetails(){

        RestRequest req = RestContext.request;
        Date theDate;
        String ds = req.params.get('PriceDate');
        List<Error> Errors = new List<Error>();
        Result res = new Result();

        if(ds!=null){
            try{
                theDate = date.valueof(ds);
            }
            catch(exception ex){
                Error e = new error();
                e.message = 'Invalid date';
                e.id=1;
                Errors.add(e);
            }
        }
        else{
            Error e = new error();
            e.message = 'No Date supplied';
            e.id=2;
            Errors.add(e);
        }
        
        if(Errors.size()==0){
            List<MProductPrice> ppm = new List<MProductPrice>();
            List<ProductPrice> pps = new List<ProductPrice>();
            List<ProductPrice> ppa = new List<ProductPrice>();
    
            List<Club_Product__c> cplist = [Select Id, Name, RecordType.Name, 
                                            Product_Detail__c, Membership__c, Show_in_New_Membership_Picklist__c, 
                                            Product_Type__c, Active__c, Visible_to_Admin_Users_Only__c, 
                                            Product_Description__c, Sections_Allowed__c, 
                                            Associate_Allowed__c, PartnerAllowed__c, 
                                            //DD_Payment_Allowed__c, Card_Payment_Allowed__c, 
                                            //Cash_Payment_Allowed__c,
                                            isOverseas__c,
                                            website_product_prompt__c, 
                                            (Select Id, 
                                                    Name, Product__c, Price__c, 
                                                    Start_Date__c, End_Date__c, 
                                                    Change_Fee__c, Joining_Fee__c,
                                                    Payment_Type__c,Price_Description__c,
                                                    Price_Prompt__c,Show_in_Web__c,
                                                    Price_Detail__c
                                                    from Prices__r 
                                                    where ((start_date__c =null or start_date__c <= :theDate) and (End_Date__c=null or End_Date__c >= :theDate))
                                                    order by start_date__c desc) from Club_Product__c
                                            order by RecordType.Name,Name];
    
            for(Club_Product__c cp:cplist){
                List<Price> pl = new List<Price>();
                ProductPrice p = new ProductPrice();
                MProductPrice m = new MProductPrice();
                p.ProductId = cp.Id;
                m.ProductId = cp.Id;
                p.ProductName = cp.Name;
                m.ProductName = cp.Name;
                p.ProductDetail = cp.Product_Detail__c;
                m.ProductDetail = cp.Product_Detail__c;
                p.Description = cp.Product_Description__c;
                m.Description = cp.Product_Description__c;
                p.ProductPrompt = cp.website_product_prompt__c;
                m.ProductPrompt = cp.website_product_prompt__c;
                for(Price__c price:cp.Prices__r){
                    Price pr = new Price();
                    pr.PaymentType = price.Payment_Type__c;
                    pr.PriceDescription =  price.Price_Description__c;
                    pr.PricePrompt = price.Price_Prompt__c;
                    pr.ShowinWeb = price.Show_in_Web__c;
                    pr.PriceDetail = price.Price_Detail__c;
                    pr.EndDate = price.End_Date__c;
                    pr.StartDate = price.Start_Date__c;
                    pr.Price = price.Price__c;
                    pr.JoiningFee = price.Joining_Fee__c;
                    pl.add(pr);
                }
                p.Prices = pl;
                m.Prices = pl;
                if(cp.RecordType.Name=='Associate Membership')ppa.add(p);
                if(cp.RecordType.Name=='Section')pps.add(p);
                if(cp.RecordType.Name=='Membership Code'){
                    m.ShowInNewMembershipPicklist = cp.Show_in_New_Membership_Picklist__c;
                    m.OverseasMembership = cp.isOverseas__c;
                    m.AssociateAllowed = cp.Associate_Allowed__c;
                    //m.CardPaymentAllowed = cp.Card_Payment_Allowed__c;
                    //m.CashPaymentAllowed = cp.Cash_Payment_Allowed__c;
                    //m.DDPaymentAllowed = cp.DD_Payment_Allowed__c;
                    m.PartnerAllowed = cp.PartnerAllowed__c;
                    m.SectionsAllowed = cp.Sections_Allowed__c;
                    ppm.add(m);
                }
            }
    
            res.Memberships = ppm;
            res.Associate = ppa;
            res.Sections = pps;
        }
        res.Errors = Errors;
        return res;     
    }

}