force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Access_Member__c.field-meta.xml
<CustomField>
    <fullName>Access_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Access Member)</relationshipLabel>
    <relationshipName>Correspondence4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Age_Concession__c.field-meta.xml
<CustomField>
    <fullName>Age_Concession__c</fullName>
    <formula>Member__r.Age_Concession__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age Concession</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Amendment_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amendment/Renewal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Amendment_Renewal__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Associate_Member__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Associate Member)</relationshipLabel>
    <relationshipName>Correspondence1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <formula>Lead_Member__r.Birthdate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Camping_Unit__c.field-meta.xml
<CustomField>
    <fullName>Camping_Unit__c</fullName>
    <formula>TEXT (Membership__r.Camping_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Camping Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Cancellation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation</label>
    <referenceTo>Cancellation__c</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Contact_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record_Type_Name__c</fullName>
    <formula>Lead_Member__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type_MailingHouse__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type_MailingHouse__c</fullName>
    <label>Correspondence Type (MH)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
                <isActive>false</isActive>
                <label>Cancellation</label>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
                <isActive>false</isActive>
                <label>Member Get Member</label>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
                <isActive>false</isActive>
                <label>Monthly Magazine</label>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
                <isActive>false</isActive>
                <label>New Associate Member</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
                <isActive>false</isActive>
                <label>Renewal</label>
            </value>
            <value>
                <fullName>Site Directory</fullName>
                <isActive>false</isActive>
                <label>Site Directory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>Membership__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <formula>Membership__r.Date_Joined__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Lead_Member__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Member__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TEXT (Member__r.Salutation ) + &quot;. &quot; +  Member__r.FirstName + &quot; &quot; +  Member__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <formula>Membership__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Home Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Member__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Lead Member)</relationshipLabel>
    <relationshipName>Correspondence3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_Country__c.field-meta.xml
<CustomField>
    <fullName>MGM_Country__c</fullName>
    <label>MGM Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_County__c.field-meta.xml
<CustomField>
    <fullName>MGM_County__c</fullName>
    <label>MGM County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>MGM_Organisation_Name__c</fullName>
    <label>MGM Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <formula>Lead_Member__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Old_DA__c.field-meta.xml
<CustomField>
    <fullName>Old_DA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old DA</label>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Opportunity_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type_Name__c</fullName>
    <formula>Amendment_Renewal__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Organisation_Name_c__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name_c__c</fullName>
    <label>Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Re_issue__c.field-meta.xml
<CustomField>
    <fullName>Re_issue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Re_issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Re_issue_Date__c</fullName>
    <label>Re-issue Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Lead_Member__r.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Replacement_renewal__c.field-meta.xml
<CustomField>
    <fullName>Replacement_renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Replacement Renewal (Opportunity)</relationshipLabel>
    <relationshipName>Correspondence1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <formula>TEXT (  Member__r.Salutation )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salutation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Secondary_Member__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Secondary Member)</relationshipLabel>
    <relationshipName>Correspondence2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>Valid_Until__c</fullName>
    <label>Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Voucher_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Expiry_Date__c</fullName>
    <label>Voucher Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExportCorrespondenceController.cls
public with sharing class ExportCorrespondenceController {

    public Correspondence__c    corr {get;set;}
    public Correspondence__c    corr2 {get;set;}
    
    public list<string>         queryFields  {get;set;}
    public string               fileName     {get;set;}
    public Integer pagesize{get{return 200;}set;}
//    public List<corrSelectWrapper> transactions {get;set;}
    private set<string> fieldstoexclude = new Set<string>{'lastvieweddate','lastreferenceddate','id','ownerid','isdeleted','createddate','createdbyid',
                                                          'lastmodifieddate','lastmodifiedbyid','systemmodstamp','lastactivitydate','membership2__c','member__c',
                                                          'amendment_renewal__c','cancellation__c','contact_record_type_name__c','opportunity_record_type_name__c',
                                                          'age_concession__c', 'amendment_renewal__c', 'amount__c', 'associate_member__c', 'birthdate__c',
                                                          'camping_unit__c', 'correspondence_type_mailinghouse__c', 'date_joined__c', 'email__c', 'first_name__c',
                                                          'full_name__c', 'home_phone__c', 'last_name__c', 'lead_member__c', 'mobile_phone__c',
                                                           'old_da__c', 'replacement_renewal__c', 'opportunity_record_type_name__c', 're_issue__c',
                                                           're_issue_date__c','salutation__c','voucher_expiry_date__c', 'country__c', 
                                                           'membership__c', 'region__c', 'secondary_member__c', 'organisation_name_c__c', 'valid_until__c',
                                                           'access_member__c', 'mgm_country__c','mgm_county__c', 'mgm_organisation_name__c', 'mgm_postcode__c',
                                                           'mgm_street__c', 'mgm_town_city__c', 'payment_method__c', 'name', 'Membership_Status__c'};  
    
    public ExportCorrespondenceController(){
        corr = new Correspondence__c(Correspondence_date__c=Date.today().adddays(-7));
        corr2 = new Correspondence__c(Correspondence_date__c=Date.today());
        fileName = 'Correspondence ' + string.valueOf(dateTime.now());
        //transactions =  new List<corrSelectWrapper>();
        transactions =  null;
        con=null;
    }

    public PageReference search(){

        transactions =  null;
        con=null;
/*      
        String queryFilts = '';
        Date sdate = corr.Correspondence_date__c;
        Date edate = corr2.Correspondence_date__c;
        Decimal bnum = corr.Batch_Number__c;
        String ctype = corr.Correspondence_Type__c;
        transactions = new List<corrSelectWrapper>();
        if(corr.Batch_Number__c!=null){
            queryFilts += 'and Batch_Number__c = :bnum ';
        }

        if(corr.Correspondence_Type__c!=null){
            queryFilts += 'and Correspondence_Type__c = :ctype ';
        }
        list<Correspondence__c>     queryResults = new list<Correspondence__c>();
        Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Correspondence__c').getDescribe().fields.getMap();
        queryFields = new List<string>();
        String query = 'Select ';//'SELECT Name, Correspondence_Type__c, Correspondence_date__c, Membership_Number__c, Membership_Status__c';
        for(String s : objectFields.keySet()) {
            if(objectFields.get(s).getDescribe().isaccessible()){
                if(!fieldstoexclude.contains(s)){
                    query += ' ' + s + ',';
                    queryFields.add(s);
                    
                }
            }
        }
        if (query.subString(query.Length()-1,query.Length()) == ','){
            query = query.subString(0,query.Length()-1);
        }
        query += ' FROM Correspondence__c ';
        query += ' where Correspondence_date__c >= :sdate ';
        query += ' and Correspondence_date__c <= :edate ';
        query+= queryFilts;
        query+= ' ORDER BY Name DESC LIMIT 400';
        
       try{
            queryResults = Database.query(query);
            system.debug(queryResults);
            system.debug(queryFields);
       } catch (Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please narrow down the search. too many rows returned'));
            
       }


        for(Correspondence__c c: queryResults )
        {
            transactions.add(new corrSelectWrapper(c));
        }
        if(queryResults.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No records found for the selected criteria'));
        }
*/        
        return null;
        
    }

    public List<corrSelectWrapper> transactions {
        get{
            if(transactions==null){
                system.debug('get trans');
                transactions = new List<corrSelectWrapper>();
                for (Correspondence__c c : (List<Correspondence__c>)con.getRecords()){
                    transactions.add(new corrSelectWrapper(c));
                }
            }
            return transactions;
        }
        set;
    }


    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
//                String fam = filters.family;
//                Id pb2id = opp.Pricebook2Id;
                String queryFilts = '';
                Date sdate = corr.Correspondence_date__c;
                Date edate = corr2.Correspondence_date__c;
                Decimal bnum = corr.Batch_Number__c;
                String ctype = corr.Correspondence_Type__c;
                transactions = new List<corrSelectWrapper>();
                if(corr.Batch_Number__c!=null){
                    queryFilts += 'and Batch_Number__c = :bnum ';
                }
        
                if(corr.Correspondence_Type__c!=null){
                    queryFilts += 'and Correspondence_Type__c = :ctype ';
                }

                Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Correspondence__c').getDescribe().fields.getMap();
                queryFields = new List<string>();
                String query = 'Select ';//'SELECT Name, Correspondence_Type__c, Correspondence_date__c, Membership_Number__c, Membership_Status__c';
                for(String s : objectFields.keySet()) {
                    if(objectFields.get(s).getDescribe().isaccessible()){
                        if(!fieldstoexclude.contains(s)){
                            query += ' ' + s + ',';
                            queryFields.add(s);
                        }
                    }
                }
                if (query.subString(query.Length()-1,query.Length()) == ','){
                    query = query.subString(0,query.Length()-1);
                }
                query += ' FROM Correspondence__c ';
                query += ' where Correspondence_date__c >= :sdate ';
                query += ' and Correspondence_date__c <= :edate ';
                query+= queryFilts;
                query+= ' ORDER BY Name DESC LIMIT 10000';
        
                con = new ApexPages.StandardSetController(Database.getQueryLocator(Query));
                // sets the number of records in each page set
                con.setPageSize(pagesize);
                system.debug(con.getResultSize());
            }
            return con;
        }
        set;
    }

   public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    public Integer numResults {
        get {
            return con.getResultSize();
        }
        set;
    }

    public Integer numstart {
        get {
            return ((pagenumber-1)*pagesize)+1;
        }
        set;
    }

    public Integer numend {
        get {
            Integer pageend = ((pagenumber-1)*pagesize)+pagesize;
            if (pageend>numResults)pageend = numresults;
            return pageend;
        }
        set;
    }

    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

     public void first() {
         transactions=null;
         con.first();
     }

     public void last() {
         transactions=null;
         con.last();
     }

     public void previous() {
         transactions=null;
         con.previous();
     }

     public void next() {
         transactions=null;
         con.next();
     }

    
    public PageReference export(){

        if(transtoAdd.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select records for export.'));
            return null;
        }

        for(Correspondence__c c:transtoadd){
            if(c.Batch_Number__c==null)
                c.Batch_Number__c = batchId;
        }
        
        update transtoadd;
        
        PageReference pr = Page.ExportCorrespondenceCSV;
        pr.getHeaders().put( 'content-disposition', 'attachment; filename=AgressoExport.csv' );
        pr.setRedirect(false);
        
        return pr;
        
    }

    public Long batchId {
        get{
            if(batchId==null){
                batchId=getNextUniqueNumber();
            }
            return batchId;
        }
        set;
    }

    public static Long getNextUniqueNumber() {

        Savepoint sp = Database.setSavepoint();
 
        Unique_Number__c un = new Unique_Number__c();
        insert un;
 
        un = [select Name from Unique_Number__c where id = :un.id];
 
        Long num = Long.valueOf(un.Name);
 
        Database.rollback(sp);
 
        return num;
    }

    public static String getNewLine() {
      return '\n';
    }

    public List<Correspondence__c> transToAdd{
        get{
            List<Correspondence__c> m = new List<Correspondence__c>();
            if(transactions!=null)
            {
                for(corrSelectWrapper c: transactions)
                {
                    if(c.selected)
                    {
                        m.add(c.corr);
                    }
                }
            }
            system.debug(m);
            return m;
            
        }
        set;
    }   

    public class corrSelectWrapper {
        public Correspondence__c corr {get; set;}
        public Boolean selected {get; set;}
 
        public corrSelectWrapper(Correspondence__c c) { 
            this.corr = c;
            this.selected = false;
        }
    }


}