force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Get_Member__c/Member_Get_Member__c.object-meta.xml
<CustomObject>
    <description>Referral scheme to give existing members a gift when recommended friend joins</description>
    <label>Recommend A Friend</label>
    <nameField>
        <displayFormat>RAF-{00000000}</displayFormat>
        <label>Member Get Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommend A Friend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TriggerFactory.cls
public with sharing class TriggerFactory {

	/**
	 * @description 	Class which will be instanstiated if no handler can be located
	 */
	private class EmptyTriggerHandler extends TriggerHandler {}
	
	
	/**
	 * @description 	Locates and instantiates the registered handler for an sObject.
	 * @param soType 	The sObject type to locate the handler for
	 */
	public static void createHandler(Schema.sObjectType soType){
		getHandler(soType).execute();
	}
	

	/**
	 * @description 	Instantiates the correct handler for the sObject type being processed.
	 * @param soType 	The sObject type to instaniate the handler for
	 * @return 			Instance of a new trigger handler for the requested sObject type
	 */
	private static TriggerHandler getHandler(Schema.sObjectType soType){
         if(soType == Account.sObjectType) {
        	return new AccountTriggerHandler();
        }
			
         if(soType == Cancellation__c.sObjectType) {
        	return new CancellationTriggerHandler();
        }
			
         if(soType == Contact.sObjectType) {
        	return new ContactTriggerHandler(); 
        }
 		
         if(soType == Member_Get_Member__c.sObjectType) {
        	return new MemberGetMemberTriggerHandler();
        }
 		
         if(soType == Opportunity.sObjectType) {
        	return new OpportunityTriggerHandler();
        }
 		
         if(soType == Payment_Method__c.sObjectType) {
        	return new PaymentMethodTriggerHandler();
        }
 		
         if(soType == Transaction__c.sObjectType) {
        	return new TransactionTriggerHandler();
        }
 		
		return new EmptyTriggerHandler();
	}
	
}