force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Cancellation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation</label>
    <referenceTo>Cancellation__c</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExportCorrespondenceControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ExportCorrespondenceControllerTest {
	
	static ExportCorrespondenceController correspondence;
	static PageReference page;
	static Correspondence__c cor;
	
	static void init(){
	    
        TestDataFactory.createCorrespondenceRecord();
    	//cor = [Select Id, Correspondence_Type__c, Cancellation__c FROM Correspondence__c];
		correspondence = new ExportCorrespondenceController();  
		
	}

    static testMethod void ExportCorrespondenceControllerTestsearch() {
        // TO DO: implement unit test
        init();
        page = correspondence.search();
        
    }

    static testMethod void ExportCorrespondenceControllerTestGetTransactions() {
        // TO DO: implement unit test
        init();
        List<ExportCorrespondenceController.corrSelectWrapper> transactions = correspondence.transactions;
        
    }

    static testMethod void ExportCorrespondenceControllerTestGetCon() {
        // TO DO: implement unit test
        init();
        ApexPages.StandardSetController con = correspondence.con;        
    }

    static testMethod void ExportCorrespondenceControllerTestGetVariable() {
        // TO DO: implement unit test
        init();
        Boolean hasNext = correspondence.hasNext;  
        Boolean hasPrevious = correspondence.hasPrevious;  
        Integer numResults = correspondence.numResults;  
        Integer numstart = correspondence.numstart;  
        Integer numend = correspondence.numend;  
        Integer pageNumber = correspondence.pageNumber;  
        long batchId = correspondence.batchId;  
       	List<Correspondence__c> transToAdd = correspondence.transToAdd;        
    }

    static testMethod void ExportCorrespondenceControllerTestVoidFunction() {
        // TO DO: implement unit test
        init();
        correspondence.first(); 
        correspondence.last(); 
        correspondence.previous(); 
        correspondence.next();        
    }

    static testMethod void ExportCorrespondenceControllerTestExport() {
        // TO DO: implement unit test
        init();
        page = correspondence.export();        
    }
}