force-app/main/default/objects/Account/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <label>Cancellation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Stop_Communication__c.field-meta.xml
<CustomField>
    <fullName>Stop_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchSetNonRenewerCancelled.cls
global class BatchSetNonRenewerCancelled implements Database.Batchable<sObject> { 
    
    global String QUERY = 'SELECT Id FROM Account WHERE  renewal_date__c <= TODAY and membership_status__c = \'Non-Renewer\' '; 
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        if(Test.isRunningTest()) {
            return Database.getQueryLocator(QUERY + ' LIMIT 200');
        }

        return Database.getQueryLocator(QUERY);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {


        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.optAllOrNone = false; 
        
        constants sc = new constants();
        List<Cancellation__c> cancs = new List<Cancellation__c>();

        for(Account a : scope) {
            Cancellation__c c = new Cancellation__c(Membership__c=a.id); 
            c.Cancellation_Date__c = date.today();
            c.Comments__c = 'Auto Cancelled Non-Renewer';
            c.Stop_Communication__c=true;
            c.Cancellation_Type__c='Cancelled';
            cancs.add(c);
        }

        Database.insert(cancs, dmo);
        
    }
    
    global void finish(Database.BatchableContext BC) {}
}