force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opted_In__c.field-meta.xml
<CustomField>
    <fullName>Opted_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opted In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <formula>Parent_Region__r.Region_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Region Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Offices associated with the Regions</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Associate_Membership.recordType-meta.xml
<RecordType>
    <fullName>Associate_Membership</fullName>
    <active>true</active>
    <label>Associate Membership</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Associate_Membership.recordType-meta.xml
<RecordType>
    <fullName>Associate_Membership</fullName>
    <active>true</active>
    <label>Associate Membership</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <formula>Account.District_Association__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Association</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <description>Add a new Child to the Membership</description>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Secondary.recordType-meta.xml
<RecordType>
    <fullName>Secondary</fullName>
    <active>true</active>
    <description>Add a new Secondary Member to the Membership</description>
    <label>Secondary</label>
</RecordType>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Association Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <label>Parent Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasPartner__c.field-meta.xml
<CustomField>
    <fullName>hasPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Email__c</fullName>
    <label>Secondary Member Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_First_Name__c</fullName>
    <label>Secondary Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Surname__c</fullName>
    <label>Secondary Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeRenewalControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest

private class ChangeRenewalControllerTest {
	
	static Opportunity opp;
	static ChangeRenewalController changeRenwal;
	static PageReference page;
	
    static void init() {
        TestDataFactory.createRenewalTestRecords();
    	opp = [Select Id, AccountId,IsClosed, Renewal_Date__c, IsWon, RecordTypeId FROM Opportunity];
		changeRenwal = new ChangeRenewalController(new ApexPages.StandardController(opp)); 
    }
    
    static testMethod void ChangeRenewalStepsTest() {      
	    init();
	    
	    changeRenwal.lea = TestDataFactory.lead;
	    changeRenwal.step1();
	    changeRenwal.step2();
	    changeRenwal.step3();
	    changeRenwal.step4();	
	    Contact cAssocMember = changeRenwal.cAssocMember;
	    Contact cSecondaryMember = changeRenwal.cSecondaryMember;
	    List<Club_Opportunity_Product__c> oppli = changeRenwal.oppli;
	    List<SelectOption> membershipTypeOptions = changeRenwal.membershipTypeOptions;
	    Decimal mtCost = changeRenwal.mtCost;
	    List<Club_Product__c> mtList = changeRenwal.mtList;
	    List<Club_Product__c> pList= changeRenwal.pList;
	   // Decimal amCost = changeRenwal.amCost;
	    //Decimal costTotal = changeRenwal.costTotal;
	    //Map<string,club_product__c> mapPrices = changeRenwal.mapPrices;
//	    PageReference confirm = changeRenwal.confirm();
	    
    }
      /* Date sDate = Date.newInstance(2015, 10, 1);
       Date eDate = Date.newInstance(2016, 12, 31);
       Date joinDate = Date.newInstance(2016, 09, 24);
       Date assocdb =  Date.newInstance(1954, 09, 24);

        Account acc = new Account();
        Association__c da = new Association__c();
        Association__c region = new Association__c();
        DA_Postcode__c pc = new DA_Postcode__c();
        Club_Product__c cp = new Club_Product__c();
        Price__c p = new Price__c();
        Opportunity renewalOpp = new Opportunity();
        Date pStartDate = Date.newInstance(2016, 09, 24);
        constants c = new constants();
        
                
        acc.Name = 'Test Membership';
        acc.District_Association__c = da.Id;
        acc.BillingPostalCode = 'TE1 0YZ';
        acc.Date_Joined__c = joinDate;
        acc.payment_method2__c = 'Direct Debit';
        //acc.Opted_In__c = true;
        insert acc;
        
    

       RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];
       Contact con3 = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId =rt.Id, Account = acc);
       insert con3;
       RecordType rt1 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName='Membership_Code' limit 1 ];
       
       region.RecordTypeId = c.accRegionRecordTypeId;
        region.Name = 'Testing Region';
        region.Region_Code__c = '101';
        insert region;
        
        da.RecordTypeId = c.accDaRecordTypeId;
        da.Name = 'Test D A';
        da.Parent_Region__c = region.Id;
        da.Region_Code__c = region.Region_Code__c;
        insert da;
        
        pc.Association_Name__c = da.Id;
        pc.Association_Code__c = da.Region_Code__c;
        pc.Parent_Region_Name__c = region.Name;
        pc.Postcode_Part_1__c = 'TE1';
        insert pc;
        
        cp.RecordTypeId = rt1.Id;
        cp.Name = 'Online';
        cp.Product_Detail__c = 'Online Membership';
        cp.Active__c = true;
        cp.Show_in_New_Membership_Picklist__c = true;
        cp.Sections_Allowed__c = true;
        cp.Associate_Allowed__c = true;
        cp.PartnerAllowed__c = true;
        cp.DD_Payment_Allowed__c = true;
        insert cp;

   
       p.Product__c = cp.Id;
       p.Price__c = 36.00;
       p.Start_Date__c =  pStartDate;
       insert p;
       
       cp = new Club_Product__c();
       
        cp.RecordTypeId = c.clubProdAssociateRecordTypeId;
        cp.Name = 'Online';
        cp.Product_Detail__c = 'Online Membership';
        cp.Active__c = true;
        cp.Show_in_New_Membership_Picklist__c = true;
        cp.Sections_Allowed__c = true;
        cp.Associate_Allowed__c = true;
        cp.PartnerAllowed__c = true;
        cp.DD_Payment_Allowed__c = true;
        insert cp;
       
       p = new Price__c();
       
        p.Product__c = cp.Id;
        p.Price__c = 36.00;
       p.Start_Date__c =  pStartDate;
       insert p;
       
         renewalOpp.Name = 'Test Opp';
      renewalOpp.Amount = 44;
      renewalopp.CloseDate = system.Today();
      renewalopp.AccountId = acc.Id; 
      renewalopp.RecordTypeId = c.OppRenewalRecordTypeId;
      renewalopp.StageName = 'Due';
      //renewalopp.IsClosed = false;
      //renewalopp.IsWon = false;
      insert renewalopp;
       

       
       
       Lead lead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
                            Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
                            Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2', 
                            Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
                            Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6', 
                            Child_6_Surname__c='Golf', Payment_Method__c='Debit / Credit Card', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
                             Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.',Sort_Code__c='20-20-20', Bank_Account_Name__c = 'Test Account',
                             Bank_Account_Number__c = '41111111', Bank_Name__c='Test', street='Hello', PostalCode='ID1 0TT', City='Annoying City', Country='Testing', 
                             State='Hidden land', Associate_Member_Date_of_Birth__c = assocdb);
      insert lead;
      
       
       Lead lead2 = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
                            Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
                            Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2', 
                            Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
                            Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6', 
                            Child_6_Surname__c='Golf', Payment_Method__c='Direct Debit', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
                             Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.',  Membership_Code__c ='Online', street='Hello', 
                             PostalCode='ID1 0TT', City='Annoying City', Country='Testing',  Associate_Member_Date_of_Birth__c = assocdb, 
                             State='Hidden land');
      insert lead2;
      
      
        RecordType rt6 = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];
      Contact con4 = new Contact(FirstName = 'Bony', LastName = 'Wolf', Phone = '01232324', RecordTypeId =rt6.Id, Account = acc);
      insert con4;
      
      RecordType rt3 = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Associate' limit 1 ];
      Contact con = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId =rt3.Id, Account = acc);
      insert con;   
            
      RecordType rt2 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName='Associate_Membership' limit 1 ];
      Club_Product__c cp2 = new Club_Product__c(name = 'testing',Product_Detail__c = 'testing Club Product', RecordTypeId =rt2.Id);
      insert cp2;
      
      
      RecordType rt4 = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Secondary' limit 1 ];
      Contact con1 = new Contact(FirstName = 'Bony', LastName = 'Wolf', Phone = '01232324', RecordTypeId =rt4.Id, Account = acc);
      insert con1;
      
      RecordType rt5 = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Child' limit 1 ];
      Contact con2 = new Contact(FirstName = 'Bony', LastName = 'Wolf', Phone = '01232324', RecordTypeId =rt5.Id, Account = acc);
      insert con2;
      
       Price__c p2 = new Price__c(Start_Date__c = sDate, End_Date__c = eDate, Product__c= cp2.id, Price__c = 44);
      insert p2;
      
      renewalOpp.Name = 'Test Opp';
      renewalOpp.Amount = 44;
      renewalopp.CloseDate = system.Today();
      renewalopp.AccountId = acc.Id; 
      renewalopp.RecordTypeId = c.OppRenewalRecordTypeId;
      renewalopp.StageName = 'Due';
      //upsert renewalopp;
      
      Test.setCurrentPage(Page.ChangeRenewal);
      ChangeRenewalController controller = new ChangeRenewalController(new ApexPages.StandardController(renewalOpp));
      //controller.lea = lead;
      controller.step1();
      controller.step2();
      controller.step3();
      controller.step4();
     
        Map<string,club_product__c> mapPrices = new Map<string,club_product__c>();
      mapprices.put('Associate Member', cp2);
      controller.cAssocMember = con;
    
      controller.cAssocMember = null;
      Contact cAssocMember = controller.cAssocMember;
      
      system.debug(lead2);

     controller.lea = lead2;
     
     PageReference confirm = controller.confirm();
     
     

       
    }*/
}