force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Opted_In__c.field-meta.xml
<CustomField>
    <fullName>Opted_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opted In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>First digit of the Inward section of the Postcode i.e. 7FG - only includes the first digit and excludes the leading space and the final two letters. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>Inward section of the Postcode i.e. 7FG - does not include the leading space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/District_Association.recordType-meta.xml
<RecordType>
    <fullName>District_Association</fullName>
    <active>true</active>
    <description>Offices associated with the District Associations</description>
    <label>District Association</label>
</RecordType>

force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <label>Cancellation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <label>Postcode Part 2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@IsTest
public class AccountTriggerHandlerTest {

    @TestSetup
    static void setupTestData() {
        Id districtAssociationRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Association__c' AND DeveloperName = 'District_Association' LIMIT 1].Id;

        List<Association__c> associations = new List<Association__c>();
        associations.add(new Association__c(Name = 'Association1', RecordTypeId = districtAssociationRecordTypeId));
        associations.add(new Association__c(Name = 'Association2', RecordTypeId = districtAssociationRecordTypeId));
        insert associations;

        List<DA_Postcode__c> daPostcodes = new List<DA_Postcode__c>();
        daPostcodes.add(new DA_Postcode__c(Association_Name__c = associations[0].Id, Postcode_Part_1__c = '12345', Postcode_Part_2__c = 'A'));
        daPostcodes.add(new DA_Postcode__c(Association_Name__c = associations[1].Id, Postcode_Part_1__c = '67890', Postcode_Part_2__c = 'B'));
        insert daPostcodes;

        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Account1', BillingPostalCode = '12345 A1', District_Association__c = associations[0].Id, Membership_Status__c = 'Member'));
        accounts.add(new Account(Name = 'Account2', BillingPostalCode = '67890 B1', District_Association__c = associations[1].Id, Membership_Status__c = 'Member'));
        insert accounts;
    }

    @IsTest
    static void testBeforeUpdate() {
        List<Account> accounts = [SELECT Id, BillingPostalCode, District_Association__c, Opted_In__c FROM Account];
        for (Account acct : accounts) {
            acct.BillingPostalCode = '12345 A1';
        }
        Test.startTest();
        update accounts;
        Test.stopTest();

        List<Account> updatedAccounts = [SELECT BillingPostalCode, Opted_In__c FROM Account];
        for (Account acct : updatedAccounts) {
            System.assertEquals(true, true);
        }
    }

    @IsTest
    static void testAfterUpdate() {
        List<Account> accounts = [SELECT Id, Membership_Status__c FROM Account];
        for (Account acct : accounts) {
            acct.Membership_Status__c = 'Ex-Member';
        }
        Test.startTest();
        update accounts;
        Test.stopTest();

        List<Cancellation__c> cancellations = [SELECT Membership__c, Cancellation_Type__c, Cancellation_Date__c FROM Cancellation__c];
        System.assertEquals(2, cancellations.size(), 'There should be 2 cancellation records created.');
        for (Cancellation__c cn : cancellations) {
            System.assertEquals('Ex-Member', cn.Cancellation_Type__c, 'Cancellation_Type__c should be Ex-Member.');
            System.assertEquals(Date.today(), cn.Cancellation_Date__c, 'Cancellation_Date__c should be today.');
        }
    }

    @IsTest
    static void testAfterUndelete() {
        List<Account> accounts = [SELECT Id FROM Account];
        delete accounts;

        undelete accounts;

        Test.startTest();
        AccountTriggerHandler.restoreOpportunities(new Map<Id, Account>(accounts).keySet());
        Test.stopTest();
    }
}