force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Opted_In__c.field-meta.xml
<CustomField>
    <fullName>Opted_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opted In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>First digit of the Inward section of the Postcode i.e. 7FG - only includes the first digit and excludes the leading space and the final two letters. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <label>Cancellation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <label>Postcode Part 2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Before_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Stage_Before_Deletion__c</fullName>
    <label>Stage Before Deletion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler extends TriggerHandler {
    
    public AccountTriggerHandler(){
        preventRecursiveTrigger(false);
    }
    
    public override void beforeUpdate(List<SObject> oldObjects, List<SObject> newObjects, Map<Id,SObject> oldMap, Map<Id,SObject> newMap){
        
        List<DA_Postcode__c> dap = [select Association_Name__c,Postcode_Part_1__c,Postcode_Part_2__c from DA_Postcode__c];
        for(Account acct :(List<Account>) newObjects){
            if(acct.BillingPostalCode!=null && acct.District_Association__c !=null){
                Boolean found =false;
                List<String> parts = acct.BillingPostalCode.split(' ');
                if(parts.size()>1){
                    String pcodeout = parts[0];
                    String pcodein = parts[1].substring(0, 1); 
                    
                    for(DA_Postcode__c da: dap){
                        if (pcodeout == da.Postcode_Part_1__c && (pcodein == da.Postcode_Part_2__c || da.Postcode_Part_2__c == null) && acct.District_Association__c == da.Association_Name__c){
                            found = true;
                            system.debug(found);
                            break;
                        } 
                    } 
                    acct.Opted_In__c = !found;
                }
            }
        }
        
    }
    
    public override void afterUpdate(List<SObject> oldObjects, List<SObject> newObjects, Map<Id,SObject> oldMap, Map<Id,SObject> newMap){
        Map<Id, Account> oldAccountMap = (Map<Id, Account>) oldMap;
        List<Account> newAccountList = (List<Account>)newObjects;
        
        // reopen opps and club products when DD is rejected
        // WARNING - this method updates memberships (Account), Opp and Club Opp Product records
        OpportunityPaymentHandler.reopenOppsAndProducts(oldAccountMap, newAccountList);
        
        
        List<Cancellation__c> cancellationList = new List<Cancellation__c>(); 
        Map<Id, Account> oldAcct = (Map<Id, Account>) oldMap;
        for(Account acct :(List<Account>) newObjects){
            if(acct.Membership_Status__c == 'Ex-Member' &&
               oldAcct.get(acct.Id).Membership_Status__c != 'Ex-Member'){
                   system.debug(oldAcct.get(acct.Id).Membership_Status__c);
                   Cancellation__c cn = new Cancellation__c();
                   cn.Membership__c =  acct.Id;
                   cn.Cancellation_Type__c = 'Ex-Member';
                   cn.Cancellation_Date__c = system.today();
                   cancellationList.add(cn);
               }
        }
        insert cancellationList;
        
        
        
    }

    public override void afterUndelete(List<SObject> newObjects) {
        List<Account> newAccountList = (List<Account>)newObjects;
        if (!System.isBatch() && !System.isFuture()) {
            restoreOpportunities(new Map<Id, Account>(newAccountList).keySet());
        }
    }

    @Future
    public static void restoreOpportunities(Set<Id> accountIds) {
        List<Opportunity> oppys = [
                SELECT Id, Stage_Before_Deletion__c, StageName
                FROM Opportunity
                WHERE AccountId IN :accountIds
        ];
        for (Opportunity oppy: oppys) {
            if (String.isNotBlank(oppy.Stage_Before_Deletion__c)) {
                oppy.StageName = oppy.Stage_Before_Deletion__c;
            }
        }
        update oppys;
    }
    
}