force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Parent_Region__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Offices associated with the Regions</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <formula>Lead_Member__r.District_Association__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Association</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CorrespondenceRestTest.cls
@IsTest
private class CorrespondenceRestTest {
    @TestSetup
    static void setup() {
        Account a = new Account();
        Association__c da = new Association__c();
        Association__c region = new Association__c();
        constants c = new constants();

        region.RecordTypeId = c.accRegionRecordTypeId;
        region.Name = 'Testing Region';
        region.Region_Code__c = '101';
        insert region;

        da.RecordTypeId = c.accDaRecordTypeId;
        da.Name = 'Test D A';
        da.Parent_Region__c = region.Id;
        da.Region_Code__c = region.Region_Code__c;
        insert da;


        a.Name = 'Test Membership';
        a.District_Association__c = da.Id;
        a.BillingPostalCode = 'TE1 0YZ';
        insert a;
    }

    @IsTest
    static void updateMemberDetailsTest() {

        Account account = [SELECT Id FROM Account LIMIT 1];

        CorrespondenceRest.RequestDataWrapper cDataWrapper = new CorrespondenceRest.RequestDataWrapper();
        cDataWrapper.membership = account.Id;
        cDataWrapper.correspondenceType = 'Replacement Card';

        RestContext.request = getRestRequest(JSON.serialize(cDataWrapper));

        Test.startTest();
        CorrespondenceRest.ResponseWrapper responseWrapper = CorrespondenceRest.updateMemberDetails();

        System.debug('JS = ' + JSON.serialize(responseWrapper));

        Test.stopTest();

        List<Correspondence__c> correspondences = [SELECT Id FROM Correspondence__c];

        System.assert(responseWrapper.success);
        System.assertEquals(201, responseWrapper.statusCode);
        System.assertEquals(1, correspondences.size());
    }

    @IsTest
    static void updateMemberDetailsNegative() {

        Account account = [SELECT Id FROM Account LIMIT 1];

        CorrespondenceRest.RequestDataWrapper cDataWrapper = new CorrespondenceRest.RequestDataWrapper();
        cDataWrapper.membership = account.Id;
        cDataWrapper.correspondenceType = 'test';

        RestContext.request = getRestRequest(JSON.serialize(cDataWrapper));

        Test.startTest();
        CorrespondenceRest.ResponseWrapper responseWrapper = CorrespondenceRest.updateMemberDetails();
        System.debug('JS = ' + JSON.serialize(responseWrapper));


        Test.stopTest();

        List<Correspondence__c> correspondences = [SELECT Id FROM Correspondence__c];

        System.assert(!responseWrapper.success);
        System.assertEquals(400, responseWrapper.statusCode);
        System.assertEquals(0, correspondences.size());
    }

    private static RestRequest getRestRequest(String jsonBody) {
        RestRequest request = new RestRequest();
        request.addHeader('Content-Type', 'application/json');
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(jsonBody);
        request.requestURI = '/services/apexrest/correspondence';
        return request;
    }

}