force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <formula>Parent_Region__r.Region_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Region Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Offices associated with the Regions</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Association Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <label>Parent Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AccountTriggerTests {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Account a = new Account();
        Association__c da = new Association__c();
        Association__c region = new Association__c();
        DA_Postcode__c pc = new DA_Postcode__c();
        constants c = new constants();
        
        region.RecordTypeId = c.accRegionRecordTypeId;
        region.Name = 'Testing Region';
        region.Region_Code__c = '101';
        insert region;
        
        da.RecordTypeId = c.accDaRecordTypeId;
        da.Name = 'Test D A';
        da.Parent_Region__c = region.Id;
        da.Region_Code__c = region.Region_Code__c;
        insert da;
        
        pc.Association_Name__c = da.Id;
        pc.Association_Code__c = da.Region_Code__c;
        pc.Parent_Region_Name__c = region.Name;
        pc.Postcode_Part_1__c = 'TE1';
        insert pc;
        
        a.Name = 'Test Membership';
        a.District_Association__c = da.Id;
        a.BillingPostalCode = 'TE1 0YZ';
        insert a;
        
    }
}