force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <formula>Parent_Region__r.Region_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Region Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Offices associated with the Regions</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>IMAGE(
CASE( Name ,
&quot;50 Years&quot;, &quot;/resource/0000000000000/fifty&quot;, /* fifty*/
&quot;Certificated Sites - Digital&quot;, &quot;/resource/0000000000000/other&quot;, /* other*/
&quot;CHH - Digital&quot;, &quot;/resource/0000000000000/chh3&quot;, /* chh*/
&quot;Complimentary&quot;, &quot;/resource/0000000000000/complimentary&quot;, /* complimentary*/
&quot;Honorary&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Honorary (VP)&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Digital&quot;, &quot;/resource/0000000000000/digital&quot;, /* online*/
&quot;Overseas - Digital Membership&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Overseas - Paper&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Paper&quot;, &quot;/resource/0000000000000/paper2&quot;, /* paper*/
&quot;Press Card Holder&quot;, &quot;/resource/0000000000000/press&quot;, /* press*/
&quot;Senior Youth - Digital&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Senior Youth - Paper&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Staff&quot;, &quot;/resource/0000000000000/staff&quot;, /* staff*/
&quot;Technical&quot;, &quot;/resource/0000000000000/tech&quot;, /* tech*/
&quot;Temporary Overseas Membership&quot;, &quot;/resource/0000000000000/tempoverseas&quot;, /* tempoverseas*/
&quot;Veteran - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran - Paper&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran Overseas - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Vice President&quot;, &quot;/resource/0000000000000/vp2&quot;, /* vp*/
&quot;Youth - Digital&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Youth - Paper&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Site Paper&quot;, &quot;/resource/0000000000000/ccc_site_paper&quot;, /* site*/
&quot;Site Digital&quot;, &quot;/resource/0000000000000/ccc_site_digital&quot;, /* site*/
&quot;/resource/0000000000000/trans_circle&quot;), /* Other */
&quot;Membership Status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <formula>Account.District_Association__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Association</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Association Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <label>Parent Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AutoCreateTransactionTriggerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AutoCreateTransactionTriggerTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Payment_Method__c pm =  new Payment_Method__c();
        
         Date joinedDate = System.today();
       RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];
       RecordType rt1 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName='Membership_Code' limit 1 ];
       
	    Account acc = new Account();
	    Association__c da = new Association__c();
	    Association__c region = new Association__c();
	    DA_Postcode__c pc = new DA_Postcode__c();
	    Club_Product__c cp = new Club_Product__c();
	    Price__c p = new Price__c();
        Date pStartDate = Date.newInstance(2016, 09, 24);
	    constants c = new constants();
	    
	    region.RecordTypeId = c.accRegionRecordTypeId;
	    region.Name = 'Testing Region';
	    region.Region_Code__c = '101';
	    insert region;
	    
	    da.RecordTypeId = c.accDaRecordTypeId;
	    da.Name = 'Test D A';
	    da.Parent_Region__c = region.Id;
	    da.Region_Code__c = region.Region_Code__c;
	    insert da;
	    
	    pc.Association_Name__c = da.Id;
	    pc.Association_Code__c = da.Region_Code__c;
	    pc.Parent_Region_Name__c = region.Name;
	    pc.Postcode_Part_1__c = 'TE1';
	    insert pc;
	    
	    cp.RecordTypeId = rt1.Id;
	    cp.Name = 'Online';
	    cp.Product_Detail__c = 'Online Membership';
	    cp.Active__c = true;
	    cp.Show_in_New_Membership_Picklist__c = true;
	    cp.Sections_Allowed__c = true;
	    cp.Associate_Allowed__c = true;
	    cp.PartnerAllowed__c = true;
	    cp.DD_Payment_Allowed__c = true;
	    insert cp;
	    
	    
	    acc.Name = 'Test Membership';
	    acc.District_Association__c = da.Id;
	    acc.BillingPostalCode = 'TE1 0YZ';
	    acc.Date_Joined__c = system.today();
	    acc.Membership_Code__c = cp.Id;
	    //acct.Renewal_Date__c = 
	    insert acc;
   
       p.Product__c = cp.Id;
       p.Price__c = 36.00;
       p.Start_Date__c =  pStartDate;
       insert p;
       
       pm.Membership__c = acc.Id;
       pm.Mandate_Amount__c =37.00;
       pm.Bank_Account_Name__c = 'Test Account';
       pm.Bank_Account_Number__c ='41111111';
       pm.Bank_Name__c='Test';
       pm.Sort_Code__c='202020';
       pm.Status__c='Active';
       pm.Start_Date__c=system.today();
       pm.RecordTypeid = c.PaymentMethodDDRecordTypeId;
       insert pm;
    }
}