force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>First digit of the Inward section of the Postcode i.e. 7FG - only includes the first digit and excludes the leading space and the final two letters. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <label>Association Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Associations</relationshipLabel>
    <relationshipName>Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Code__c</fullName>
    <formula>Parent_Region__r.Region_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Region Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <formula>Parent_Region__r.Region_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Region Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Group__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Group__c</fullName>
    <label>Postcode Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>Inward section of the Postcode i.e. 7FG - does not include the leading space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Code__c</fullName>
    <label>Region Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Association__c/recordTypes/District_Association.recordType-meta.xml
<RecordType>
    <fullName>District_Association</fullName>
    <active>true</active>
    <description>Offices associated with the District Associations</description>
    <label>District Association</label>
</RecordType>

force-app/main/default/objects/Contact/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <formula>Account.District_Association__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Association</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <formula>Lead_Member__r.District_Association__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Association</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Old_DA__c.field-meta.xml
<CustomField>
    <fullName>Old_DA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old DA</label>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Code__c.field-meta.xml
<CustomField>
    <fullName>Association_Code__c</fullName>
    <label>Association Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Parent_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Region_Name__c</fullName>
    <label>Parent Region Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <label>Postcode Part 2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisbandDAAllocationExtension.cls
public with sharing class DisbandDAAllocationExtension {
	
	private final Association__c asso;
    ApexPages.StandardController sController; 
	public String selectedAllAsso { get; set;}
    public constants sc = new constants();
	
    
    public DisbandDAAllocationExtension(ApexPages.StandardController stdController) {
        sController = stdController;  
        
        List<String> accfields = new list<String>();

        Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Association__c').getDescribe().fields.getMap();
        for(String s : objectFields.keySet()) {
            accfields.add(s);
            //system.debug(s);
        }
        
        if(!test.isRunningTest()) 
            stdController.addFields(accfields);
        this.asso = (Association__c)stdController.getRecord();
        this.daName = this.asso.Name;
    }
    
    public List<DA_Postcode__c> daRelatedPostcodes{
        get{
            if(daRelatedPostcodes==null){
                daRelatedPostcodes = new List<DA_Postcode__c>();
                daRelatedPostcodes = [SELECT id, Name, Association_Code__c, Association_Name__c, Parent_Region_Name__c, Association_Name__r.Name, Postcode_Part_1__c, Postcode_Part_2__c FROM DA_Postcode__c WHERE Association_Name__c =: asso.Id];
            }
            system.debug('daRelatedPostcodes ' + daRelatedPostcodes);
            return daRelatedPostcodes;
        }
        set;
    }
    
    public String daName{
    	get{
    		return daName;    		
    	}
    	set;
    }
    
    public List<Association__c> allAsso{
        get{
            if(allAsso==null){
                allAsso = new List<Association__c>();
                allAsso = [SELECT id, Name, Association_Code__c, Association_Name__c, Contact_Name__c, Notes__c, Parent_Region__c, Parent_Region_Code__c, Parent_Region_Name__c, Postcode_Group__c,
                						Postcode_Part_1__c, Postcode_Part_2__c, Region_Code__c, Region_Name__c, isActive__c FROM Association__c WHERE Id !=: asso.Id AND RecordTypeId = :daRecType.Id
                						 AND isActive__c = true Order by Name];
            }
            system.debug('allAsso ' + allAsso);
            return allAsso;
        }
        set;
    }

    public RecordType daRecType{
        get{
            if(daRecType==null){
                daRecType = new RecordType();
                daRecType = [SELECT id, Name FROM RecordType WHERE SobjectType = 'Association__c' AND developerName = 'District_Association'];
            }
            system.debug('daRecType ' + daRecType);
            return daRecType;
        }
        set;
    }
    
    public List<SelectOption> getItems() {
		List<SelectOption> op = new List<SelectOption>();

    	for(Association__c a : allAsso) 
    		op.add(new SelectOption(a.Id, a.Name));

   		return op;
	}
	
	 public List<DAPostcodeWrapper> allocatePostcodeWrapper {
        get{
            if(allocatePostcodeWrapper==null){
                allocatePostcodeWrapper = new List<DAPostcodeWrapper>();
                for (DA_Postcode__c p : daRelatedPostcodes){
                    allocatePostcodeWrapper.add(new DAPostcodeWrapper(p, false));
            	}
            }
            return allocatePostcodeWrapper;
        }
        set;
	}
	
	public pagereference  clearAllData(){
		system.debug('cleared bed list');
		allocatePostcodeWrapper=null;
		selectedAllAsso = null;
		return null;
	}
    
    
    public PageReference saveData(){
    	DA_Postcode__c postcode;    	
		List<DAPostcodeWrapper> poWrapper = new List<DAPostcodeWrapper>();
		List<DA_Postcode__c> poList = new List<DA_Postcode__c>();
		List<Account> memberships = new List<Account>();
		List<Correspondence__c> corrList = new List<Correspondence__c>();
		List<Contact> members = new List<Contact>();
		List<String> selectedpoList = new List<String>();
		
        for (DAPostcodeWrapper pcw : allocatePostcodeWrapper){
        	if(pcw.selected){
        		poWrapper.add(pcw);        		
        	}
        }	
    	if(selectedAllAsso == null || selectedAllAsso == ''){
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please select a DA Association.'));
    		return null;
    	}	
    	if(poWrapper.size() == 0){
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please select atleast one postcode.'));	
    		return null;
    	}
    	
    	for(DAPostcodeWrapper dpw : poWrapper){
    		if(dpw.selected = true){
	    		dpw.pc.Association_Name__c = selectedAllAsso;
	    		poList.add(dpw.pc);
	    		String p = dpw.pc.Postcode_Part_1__c + ' ';
	    		if(dpw.pc.Postcode_Part_2__c != null){
		    		p += dpw.pc.Postcode_Part_2__c;
	    		}
	    		p+= '%';
		    	selectedpoList.add(p);
    		}
    	}
    	
    	system.debug('selectedpoList ' + selectedpoList);
    	if(selectedAllAsso != null || selectedAllAsso != ''){
    		memberships = [SELECT Id, Name, District_Association__c, BillingPostalCode FROM Account WHERE District_Association__c =: asso.Id AND BillingPostalCode LIKE :selectedpoList];
    	}
    	system.debug(memberships);
    	if(memberships.size() > 0){
    		members = [select id, accountId from contact where accountid IN :memberships and recordtypeid=:sc.leadContactRecordTypeId];
    		for(Account a : memberships){
    			a.District_Association__c = selectedAllAsso;
    			
    			//creating correspondence
    			for(Contact c: members){
    				if(c.accountId == a.Id){
		    			Correspondence__c corr = new Correspondence__c();
						corr.Member__c = c.id;
						corr.Correspondence_date__c = Date.today();
						corr.Correspondence_Type__c='Disband DA';
						corr.Membership__c = a.Id;
						corr.Old_DA__c = asso.id;
						corrList.add(corr);
    				}
    			}				
    		}   		
    	}
    	if(poList.size() > 0){
    		update poList;
    	}
    	if(memberships.size() > 0){
    		update memberships;
    	}
    	if(corrList.size() > 0){
    		insert corrList;
    	}
    	clearAllData();
    	return new PageReference('/' +asso.Id);
    }

}