force-app/main/default/objects/Account/fields/District_Association__c.field-meta.xml
<CustomField>
    <fullName>District_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Association</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>Memberships (DA)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <description>Outward section of the Postcode i.e. PR1 or L15 - does not include the trailing space. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <description>First digit of the Inward section of the Postcode i.e. 7FG - only includes the first digit and excludes the leading space and the final two letters. Used to determine the Region and DA allocation</description>
    <label>Postcode Part 2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/DA_Postcode__c.object-meta.xml
<CustomObject>
    <label>DA Postcode</label>
    <nameField>
        <displayFormat>DAP-{00000000}</displayFormat>
        <label>DA Postcode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DA Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DA_Postcode__c/fields/Association_Name__c.field-meta.xml
<CustomField>
    <fullName>Association_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Association Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Association__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>District Association</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Association__c</referenceTo>
    <relationshipLabel>DA Postcodes</relationshipLabel>
    <relationshipName>DA_Postcodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_1__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_1__c</fullName>
    <label>Postcode Part 1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DA_Postcode__c/fields/Postcode_Part_2__c.field-meta.xml
<CustomField>
    <fullName>Postcode_Part_2__c</fullName>
    <label>Postcode Part 2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ValidatePostcodeExtension.cls
public with sharing class ValidatePostcodeExtension {

    private final Account acct;
    ApexPages.StandardController sController;  
    
    public ValidatePostcodeExtension(ApexPages.StandardController stdController) {
        sController = stdController;  
        this.acct = (Account)stdController.getRecord();
        wizardStep = 1;
    }

    public Integer wizardStep {get;set;}
    public String selAddr {get;set;}

    public Map<Integer,hopewiserSoapaddrsvr.addressMatchType> addMatch {
        get{
            if(addMatch==null){
                addMatch = new Map<Integer,hopewiserSoapaddrsvr.addressMatchType>();
            }
            return addMatch;
        }
        set;
    }


    public PageReference validate()
    {
            hopewiserSoapaddrsvr pclook = new hopewiserSoapaddrsvr();
            hopewiserSoapaddrsvr.postcodeLookupRequestOptionsType plro = new hopewiserSoapaddrsvr.postcodeLookupRequestOptionsType();
            hopewiserSoapaddrsvr.formattedLabelOptionsType flo = new hopewiserSoapaddrsvr.formattedLabelOptionsType();
            hopewiserSoapaddrsvr.dataType dt = new hopewiserSoapaddrsvr.dataType();
            hopewiserSoapaddrsvr.dataType ed = new hopewiserSoapaddrsvr.dataType();
            String postcode = acct.BillingPostalCode;
            //postcode = 'L1 4GF';
            String Premise = '';
            String MAF = '';
            
            docsOasisOpenOrgWss200401Oasis20040.securityType sectype = new docsOasisOpenOrgWss200401Oasis20040.securityType();
            docsOasisOpenOrgWss200401Oasis20040.usernameTokenType sectoken = new docsOasisOpenOrgWss200401Oasis20040.usernameTokenType();
            sectoken.Username ='stuart.greig@sandyxsystems.co.uk';
            sectoken.password ='K4RfVEVL';
            
            hopewiserSoapaddrsvr.soapaddrsvrInterfaceSoap11 r= new hopewiserSoapaddrsvr.soapaddrsvrInterfaceSoap11();
            sectype.UsernameToken = sectoken;
            r.Security = sectype;
            if(!test.isRunningTest()){
            hopewiserSoapaddrsvr.PostcodeLookupResponse_element rv = r.PostcodeLookup(postcode,premise,MAF,plro,flo,dt,ed);
            
            system.debug(rv);
                        
            if(rv.Match!=null)
            {
                wizardstep=2;
                Integer i=0;
                for(hopewiserSoapaddrsvr.addressMatchType m: rv.Match)
                {
                    addMatch.put(i,m);
                    system.debug(m.Address);
                    ++i;
                }
            } 
                for(integer s=0;s<addMatch.size();s++)
                {
                    system.debug(addMatch.get(s).Address.Line1);
                }
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Postcode not Found'));
            }

        return null;
    }

    public List<SelectOption> addressOptions{
        get{
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('','--Please Select--'));
            for(integer s=0;s<addMatch.size();s++)
            {
                options.add(new SelectOption(String.valueOf(s), soAddress(addMatch.get(s).Address)));
            }
            return options;
        }
        set;
    }

    private String soAddress(hopewiserSoapaddrsvr.addressType addr){
        String address ='';
        if(addr.Line1 !=null)address+=addr.Line1+' ,';
        if(addr.Line2 !=null)address+=addr.Line2+' ,';
        if(addr.Line3 !=null)address+=addr.Line3+' ,';
        if(addr.Line4 !=null)address+=addr.Line4+' ,';
        if(addr.Line5 !=null)address+=addr.Line5+' ,';
        if(addr.TOWN !=null)address+=addr.TOWN+' ,';
        if(addr.County !=null)address+=addr.County+' ,';
        if(addr.Postcode !=null)address+=addr.Postcode+' ,';
        address = address.removeEnd(',');
        
        return address;
        
    }

    private String billAddress(hopewiserSoapaddrsvr.addressType addr){
        String address ='';
        if(addr.Line1 !=null)address+=addr.Line1+'\r\n';
        if(addr.Line2 !=null)address+=addr.Line2+'\r\n';
        if(addr.Line3 !=null)address+=addr.Line3+'\r\n';
        if(addr.Line4 !=null)address+=addr.Line4+'\r\n';
        if(addr.Line5 !=null)address+=addr.Line5+'';
        
        return Address;
    }

    public PageReference updateAddress(){
        if(seladdr==null)
        {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'No Address Selected'));
                return null;
        }

        List<DA_Postcode__c> dap = new List<DA_Postcode__c>();
        
        acct.BillingStreet = billAddress(addMatch.get(integer.valueOf(seladdr)).Address);
        acct.BillingCity = addMatch.get(integer.valueOf(seladdr)).Address.Town;
        acct.BillingState = addMatch.get(integer.valueOf(seladdr)).Address.County;
        acct.BillingPostalCode = addMatch.get(integer.valueOf(seladdr)).Address.Postcode;

        List<String> parts = acct.BillingPostalCode.split(' ');
        String pcodeout = parts[0];
        String pcodein = parts[1].substring(0, 1); 
        
        dap = [select Association_Name__c,Postcode_Part_1__c,Postcode_Part_2__c
                from DA_Postcode__c where Postcode_Part_1__c =:pcodeout
                and (Postcode_Part_2__c = :pcodein or Postcode_Part_2__c = null ) limit 1];
                
        if(dap.size()>0)
        {
            acct.District_Association__c = dap[0].Association_Name__c;
        }
        else
        {
            acct.District_Association__c = null;
        }

        
        PageReference pr = sController.save(); 
        
        return pr;
    }

}