force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>This is the primary Email contact for the Membership. Typically the Email address of the Lead Member.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promotional_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotional Code</label>
    <referenceTo>Promotional_Code__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/recordTypes/Associate_Membership.recordType-meta.xml
<RecordType>
    <fullName>Associate_Membership</fullName>
    <active>true</active>
    <label>Associate Membership</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Dealer_Advert__c/Dealer_Advert__c.object-meta.xml
<CustomObject>
    <label>Dealer / Advert</label>
    <nameField>
        <label>Dealer / Advert</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers / Adverts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Dealer_Ad_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Ad_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer / Ad Code</label>
    <referenceTo>Dealer_Advert__c</referenceTo>
    <relationshipLabel>Incomplete Memberships</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promotional_Code__c/Promotional_Code__c.object-meta.xml
<CustomObject>
    <label>Promotional Code</label>
    <nameField>
        <label>Promotional Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentProcessorControllerTest.cls
/**
 * @description       :
 * @author            : Kev Cadger (Wipro)
 * @group             :
 * @last modified on  : 18-08-2022
 * @last modified by  : Kev Cadger (Wipro)
 * Modifications Log
 * Ver   Date         Author               Modification
 * 1.0   17-08-2022   Kev Cadger (Wipro)   Initial Version
 **/
@IsTest
public without sharing class PaymentProcessorControllerTest {
    @TestSetup
    static void makeData() {
        createClubProduct('Membership_Code');
        createClubProduct('Associate_Membership');
        createClubProduct('Section');
        TestDataFactory.createSObject(new Dealer_Advert__c());
        TestDataFactory.createSObject(new Promotional_Code__c());
    }

    @IsTest
    static void testProcessPaymentCard() {
        // Initialise any variables.
        Map<String, Object> result = null;
        Map<String, Object> cardDetails = new Map<String, Object>{
                'card_number' => '40000000000000000',
                'cvv' => '123',
                'expiry_month' => '01',
                'expiry_year' => '24'
        };
        Integer amount = 100;

        Test.startTest();
        try {
            PaymentProcessorController.processPaymentCard(cardDetails, amount, '');
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

    @IsTest
    static void testProcessPaymentCash() {
        Test.startTest();
        try {
            PaymentProcessorController.processPaymentCash();
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

    @IsTest
    static void testProcessPaymentDirectDebit() {
        Test.startTest();
        try {
            PaymentProcessorController.processPaymentDirectDebit();
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

    @IsTest
    static void testProcessMembershipCash() {
        Lead leadPaid = createLead();
        Lead leadUnpaid = createLead();
        leadUnpaid.Amount__c = 0;
        update leadUnpaid;

        Test.startTest();
        try {
            PaymentProcessorController.processMembership(
                    leadPaid.Id,
                    'Cash/Cheque',
                    'Test',
                    0
            );
            PaymentProcessorController.processMembership(
                    leadUnpaid.Id,
                    'Cash/Cheque',
                    null,
                    0
            );
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

    @IsTest
    static void testProcessMembershipCard() {
        Lead leadPaid = createLead();
        Lead leadUnpaid = createLead();

        Test.startTest();
        try {
            PaymentProcessorController.processMembership(
                    leadPaid.Id,
                    'Debit/Credit Card',
                    'Test',
                    0
            );
            PaymentProcessorController.processMembership(
                    leadUnpaid.Id,
                    'Debit/Credit Card',
                    null,
                    0
            );
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

    @IsTest
    static void testProcessMembershipDebit() {
        Lead lead = createLead();

        Test.startTest();
        try {
            PaymentProcessorController.processMembership(
                    lead.Id,
                    'Direct Debit',
                    'Test',
                    0
            );
        } catch (Exception e) {
            Utilities.logException(e);
        }
        Test.stopTest();
    }

  @IsTest
  static void testProcessMembershipCashAccount() {
    Account account = createAccount();

    Test.startTest();
    try {
      PaymentProcessorController.processMembership(
              account.Id,
              'Cash/Cheque',
              'Test',
              99
      );
    } catch (Exception e) {
      Utilities.logException(e);
    }
    Test.stopTest();
  }

    // !------------------------------------------------------------! //
    // * Helper Methods

    private static void createClubProduct(String recordTypeName) {
        SObject clubProduct = TestDataFactory.createSObject(
                new Club_Product__c(
                        RecordTypeId = Utilities.getRecordTypeId(
                                Club_Product__c.getSObjectType().getDescribe().getName(),
                                recordTypeName
                        )
                )
        );

        TestDataFactory.createSObject(
                new Price__c(Payment_Type__c = 'Cash/Cheque', Product__c = clubProduct.Id)
        );
        TestDataFactory.createSObject(
                new Price__c(
                        Payment_Type__c = 'Debit/Credit Card',
                        Product__c = clubProduct.Id
                )
        );
        TestDataFactory.createSObject(
                new Price__c(
                        Payment_Type__c = 'Direct Debit',
                        Product__c = clubProduct.Id
                )
        );
    }

    private static Lead createLead() {
        TestDataDefaults.LeadDataExtension leadDataExtensions = new TestDataDefaults.LeadDataExtension();

        Lead lead = (Lead) TestDataFactory.getSObject(new Lead());
        leadDataExtensions.setPartnerMemberDetails(lead);
        leadDataExtensions.setAssociateMemberDetails(lead);
        leadDataExtensions.setChildMemberDetails(lead, 1);
        lead.Dealer_Ad_Code__c = [
                SELECT Id
                FROM Dealer_Advert__c
                WHERE Name = 'TestShow'
        ]
                .Id;
        lead.Membership_Code__c = 'TestClubProduct';
        lead.Sections__c = 'TestClubProduct';
        lead.Voucher_Code__c = 'TestPromoCode';

        upsert lead;
        return lead;
    }

    private static Account createAccount() {
      Account account = new Account();
      account.Name = 'Test Account';
      account.Email__c = 'test@gmail.com';
      insert account;

      return account;
    }
}