force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>This is the primary Email contact for the Membership. Typically the Email address of the Lead Member.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lead member associated with the membership.</description>
    <inlineHelpText>The lead member associated with the membership.</inlineHelpText>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Ended__c.field-meta.xml
<CustomField>
    <fullName>Date_Ended__c</fullName>
    <label>Date Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Secondary.recordType-meta.xml
<RecordType>
    <fullName>Secondary</fullName>
    <active>true</active>
    <description>Add a new Secondary Member to the Membership</description>
    <label>Secondary</label>
</RecordType>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Associate_Member__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Associate Member)</relationshipLabel>
    <relationshipName>Correspondence1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <formula>Membership__r.Date_Joined__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Lead_Member__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Lead Member)</relationshipLabel>
    <relationshipName>Correspondence3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Last_Name__c</fullName>
    <label>Lead Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Salutation__c</fullName>
    <label>Lead Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <formula>Lead_Member__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler  extends TriggerHandler{

    public ContactTriggerHandler(){
        preventRecursiveTrigger(false);
    }
    
    public override void beforeUpdate(List<SObject> oldObjects, List<SObject> newObjects, Map<Id,SObject> oldMap, Map<Id,SObject> newMap){
        Set<id> accountids = new Set<id>();
        constants c = new constants();

        List<Contact> newContacts = (List<Contact>) newObjects;
        Map<Id,Contact> oldContactMap = (Map<Id,Contact>) oldmap;

        for (Contact cn: newContacts) {
            if(cn.email!=null && cn.email != oldContactMap.get(cn.id).email && !cn.email.contains('@example.com')){
                if(cn.RecordTypeId == c.leadContactRecordTypeId || cn.recordtypeid == c.secondaryContactRecordTypeId){
                    accountids.add(cn.accountid);
                }
            }
        }            

        List<id> contactrecids = new List<Id>();
        contactrecids.add(c.leadContactRecordTypeId);
        contactrecids.add(c.secondaryContactRecordTypeId);

        Map<Id,Account> accwithCons = new Map<Id,Account>([select id,(select id,email,recordtypeid from contacts where recordtypeid in :contactrecids) from account where id in :accountids]);

        for (Contact cn: newContacts) {
            if(cn.email!=null &&  cn.email != oldContactMap.get(cn.id).email && !cn.email.contains('@example.com')){
                if(cn.RecordTypeId == c.leadContactRecordTypeId || cn.recordtypeid == c.secondaryContactRecordTypeId){
                    for (Contact co: accwithCons.get(cn.accountid).contacts){
                        if(cn.id!= co.id && cn.email == co.email && cn.email!=null){
                            cn.adderror('Lead and Secondary members emails cannot be the same');
                        }
                    }
                }
            }
        }            
    }

    public override void afterUpdate(List<SObject> oldObjects, List<SObject> newObjects, Map<Id,SObject> oldMap, Map<Id,SObject> newMap){

        List<Contact> newContacts = (List<Contact>) newObjects;

        Set<id> accountids = new Set<id>();
        constants c = new constants();
        List<Correspondence__c> corrList = new List<Correspondence__c>();
        
        for(Contact cn:newContacts){
            accountids.add(cn.AccountId);       
        }
        
        system.debug('in ContactTrigger ' + accountids);
        
        Map<id,Account> accMap = new Map<id,Account>([select id, Renewal_Date__c, (Select Id, Salutation,FirstName,LastName, Date_Joined__c from Contacts where RecordTypeId = :c.leadContactRecordTypeId ) FROM Account WHERE Id in :accountids]);

        List<Account> memshipsToUpdate = new List<Account>(); 
        for (Contact cn: newContacts) {
            if(cn.RecordTypeId == c.leadContactRecordTypeId && cn.Status__c == 'Active' ){
                if(accMap.size() > 0){
                    system.debug(accMap.get(cn.AccountId).Id);
                    Account mem = new Account();
                    mem.Id = accMap.get(cn.AccountId).Id;
                    mem.Name = cn.LastName;
                    mem.Phone = cn.Phone;
                    mem.Mobile_Phone__c =cn.MobilePhone;
                    mem.Email__c = cn.Email;
                    mem.Date_Joined__c = cn.Date_Joined__c;
                    memshipsToUpdate.add(mem);
                  }
            }
        }
        
        update memshipsToUpdate;

    }

    public override void afterInsert(List<SObject> newObjects, Map<Id,SObject> newMap){
        List<Contact> newContacts = (List<Contact>) newObjects;
        
        Set<id> accountids = new Set<id>();
        constants c = new constants();
        List<Correspondence__c> corrList = new List<Correspondence__c>();
        
        for(Contact cn:newContacts){
        	system.debug(cn.accountId);
        	system.debug(cn);
            accountids.add(cn.AccountId);       
        }
        
        system.debug('in ContactTrigger ' + accountids);
        
        Map<id,Account> accMap = new Map<id,Account>([select id, Renewal_Date__c, Payment_Method2__c, (Select Id, Salutation,FirstName,LastName from Contacts where RecordTypeId = :c.leadContactRecordTypeId ) FROM Account WHERE Id in :accountids]);
        system.debug(accMap);
        for(Contact cn:newContacts){
            if(cn.RecordTypeId == c.associateContactRecordTypeId){
                Correspondence__c corr = new Correspondence__c();
                corr.Correspondence_Type__c = 'New Associate Member';
                corr.Correspondence_date__c =  system.today();
                corr.Renewal_Date__c = accMap.get(cn.AccountId).Renewal_Date__c;
                corr.Payment_Method__c = accMap.get(cn.AccountId).Payment_Method2__c;
                System.debug(cn);
                
                corr.Membership__c = cn.AccountId;
               // corr.Lead_Member__c = cn.Id;
                if(accMap.size() > 0){
                    system.debug(accMap.get(cn.AccountId).Contacts);
                    for(Contact lc: accMap.get(cn.AccountId).Contacts){
                        corr.Lead_Member__c = lc.id;
                        corr.Lead_Member_Salutation__c =  lc.Salutation;
                        corr.Lead_Member_First_Name__c =  lc.FirstName;
                        corr.Lead_Member_Last_Name__c =  lc.LastName;
                    }
                }
                corr.Associate_Member__c =  cn.id;
                corrList.add(corr);
            }      
        }
        
        insert corrList;
        
    
          //  Set<id> accids = new Set<id>();
        List <Contact> alist =  New List<Contact>();
        
          Map<id,Account> accMap2 = new Map<id,Account>([select id, (Select Id, Name,  Status__c, RecordTypeId from Contacts where RecordTypeId = :c.secondaryContactRecordTypeId) FROM Account WHERE  Id IN: accountids]);
      
    
        for(Contact cn: newContacts){
            if(accMap2.size() > 0){
                for (Contact co: accMap2.get(cn.AccountId).Contacts) {
                    Contact updateC = co;
                    if (co.RecordTypeId == c.secondaryContactRecordTypeId && co.Status__c == 'Active' && co.Id != cn.Id && cn.RecordTypeId == c.secondaryContactRecordTypeId){
                        updateC.Date_Ended__c = System.today();
                        alist.add(updateC);
                        }
                }
            
            }
            
        }
        
        
        
        update alist;
       
        
        
        
        
        
        
        
        
        
        
        
        //RecordType rt = [SELECT Id from RecordType WHERE SobjectType = 'Contact' AND Name = 'Lead' AND DeveloperName ='Lead'];
        /*constants c = new constants();
        
        for (contact con: Trigger.new) {
            
                system.debug(con.RecordTypeId);
            
                if (con.RecordTypeId == c.associateContactRecordTypeId)
                    con.addError('Associate Members should be added using the [Change Membership] button');
                if (con.RecordTypeId == c.leadContactRecordTypeId)
                    con.addError('New Lead Members cannot be added to the Membership');
                    system.debug(RecordType.Name);
                    break;
        }
        
     */

    }

}