force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>This is the primary Email contact for the Membership. Typically the Email address of the Lead Member.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Lead_Member__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Mandate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Amount__c</fullName>
    <label>Mandate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>CASESAFEID(Payment_Method__r.Membership__r.Id)</formula>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentMethodTriggerHandlerTest.cls
@isTest
private class PaymentMethodTriggerHandlerTest {
    
    @testSetup
    static void setup() {

    	// test memberships
    	List<Account> memberships = new List<Account>();

    	// test membership with dummy email address
    	Account membershipDummyEmail = new Account(
    		Name = 'testMembershipDummyEmail',
    		Email__c = 'example@example.com'
    	);
    	memberships.add(membershipDummyEmail);

    	Account membershipRealEmail = new Account(
    		Name = 'testMembershipRealEmail',
    		Email__c = 'test@email.com'
    	);
    	memberships.add(membershipRealEmail);
    	insert memberships;


    	// test members
    	List<Contact> members = new List<Contact>();
    	Id contactLeadRecordType = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Lead').RecordTypeId;

    	// test member associated to membership with dummy email
    	Contact memberDummyEmail = new Contact(
    		RecordTypeId = contactLeadRecordType,
    		Salutation = 'Mr',
    		FirstName = 'firstName',
    		LastName = 'testMemberDummyEmail',
    		AccountId = membershipDummyEmail.Id
    	);
    	members.add(memberDummyEmail);

    	// test member associated to membership with real email
    	Contact memberRealEmail = new Contact(
    		RecordTypeId = contactLeadRecordType,
    		Salutation = 'Dr',
    		FirstName = 'firstName',
    		LastName = 'testMemberRealEmail',
    		AccountId = membershipRealEmail.Id
    	);
    	members.add(memberRealEmail);

    	insert members;

    	// test payment methods
    	List<Payment_Method__c> paymentMethods = new List<Payment_Method__c>();
    	Id paymentMethodDirectDebitRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Direct Debit').RecordTypeId;

    	// test payment method associated to membership with dummy email
		Payment_Method__c paymentMethodDummyEmail = new Payment_Method__c(
			RecordTypeId = paymentMethodDirectDebitRecordTypeId,
			Status__c = 'Active',
			Membership__c = membershipDummyEmail.Id,
			Bank_Account_Name__c = 'testBankAccount'
		);
		paymentMethods.add(paymentMethodDummyEmail);

		// test payment method associated to membership with dummy email
		Payment_Method__c paymentMethodRealEmail = new Payment_Method__c(
			RecordTypeId = paymentMethodDirectDebitRecordTypeId,
			Membership__c = membershipRealEmail.Id,
			Status__c = 'Active',
			Mandate_Amount__c = 1.0,
			Bank_Account_Name__c = 'testBankAccount'
		);
		paymentMethods.add(paymentMethodRealEmail);

		insert paymentMethods;
        
    }

    @isTest
    static void testCorrespondenceCreatedForDummyEmail(){
    	List<Correspondence__c> correspondences = [SELECT Id FROM Correspondence__c];
    	System.assertEquals(1, correspondences.size());
    }

    @isTest
    static void testNewPendingTransactionCreated(){
    	List<Transaction__c> transactions = [SELECT Id FROM Transaction__c];

    	// since we are testing various scenarios, we insert various payment methods
    	// need to assert correct number of transactions created
    	System.assertEquals(2, transactions.size());
    }

    @isTest
    static void testPaymentMethodStatusCancelTransactionRejected(){
    	// update payment method
    	Payment_Method__c paymentMethod = [SELECT Id FROM Payment_Method__c WHERE Status__c = 'Active' LIMIT 1].get(0);
    	paymentMethod.Status__c = 'Cancelled';
    	update paymentMethod;

    	// assert that a new transaction record has been created
    	List<Transaction__c> transactions = [SELECT Id FROM Transaction__c WHERE Status__c = 'Cancelled'];
    	System.assertEquals(1, transactions.size());

    }

    @isTest
    static void testPaymentMethodStatusRejectTransactionRejected(){
    	// update payment method
    	Payment_Method__c paymentMethod = [SELECT Id FROM Payment_Method__c WHERE Status__c = 'Active' LIMIT 1].get(0);
    	paymentMethod.Status__c = 'Rejected';
    	update paymentMethod;

    	// assert that a new transaction record has been created
    	List<Transaction__c> transactions = [SELECT Id FROM Transaction__c WHERE Status__c = 'Rejected'];
    	System.assertEquals(1, transactions.size());

    }

    @isTest
    static void testPaymentMethodMandateAmountChangeCorrespondenceCreated(){
    	// assert 1 correspondence record in db from dummy email membership
    	List<Correspondence__c> correspondences = [SELECT Id FROM Correspondence__c];
    	System.assertEquals(1, correspondences.size());


    	Payment_Method__c paymentMethod = [SELECT Id FROM Payment_Method__c WHERE Status__c = 'Active' LIMIT 1].get(0);
    	paymentMethod.Mandate_Amount__c = 2.0;
    	update paymentMethod;

    	// assert new correspondence record created from payment method update
    	correspondences = [SELECT Id FROM Correspondence__c];
    	System.assertEquals(2, correspondences.size());
    }

    @isTest 
    static void testNewPaymentMethodCorrespondenceCreated(){
    	TriggerRecursionCheck.preventCorrespondenceCreation = false;

    	// assert 1 correspondence record in db from dummy email membership
    	List<Correspondence__c> correspondences = [SELECT Id FROM Correspondence__c];
    	System.assertEquals(1, correspondences.size());

    	// get existing membership from db
    	Account membership = [SELECT Id FROM Account WHERE Name = 'testMembershipDummyEmail'];

    	// create new payment method and associate to existing account
    	Id paymentMethodDirectDebitRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Direct Debit').RecordTypeId;
    	Payment_Method__c newPaymentMethod = new Payment_Method__c(
    		RecordTypeId = paymentMethodDirectDebitRecordTypeId,
			Membership__c = membership.Id,
			Status__c = 'Active',
			Mandate_Amount__c = 11.0,
			Bank_Account_Name__c = 'testBankAccountNew'
    	);
    	insert newPaymentMethod;

    	// assert number of correspondences in db from new payment method creation
    	correspondences = [SELECT Id FROM Correspondence__c];
    	System.assertEquals(2, correspondences.size());
    }





















}