force-app/main/default/objects/Account/fields/Email_Stop__c.field-meta.xml
<CustomField>
    <fullName>Email_Stop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mag_Stop__c.field-meta.xml
<CustomField>
    <fullName>Mag_Stop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Magazine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mail_Stop__c.field-meta.xml
<CustomField>
    <fullName>Mail_Stop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Direct Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Promotional_Mailstop__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Mailstop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Marketing Direct Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stop_Marketing_Email__c.field-meta.xml
<CustomField>
    <fullName>Stop_Marketing_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Marketing Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stop_Marketing_SMS__c.field-meta.xml
<CustomField>
    <fullName>Stop_Marketing_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Marketing SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Cancellation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <label>Cancellation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cancellation__c/fields/Stop_Communication__c.field-meta.xml
<CustomField>
    <fullName>Stop_Communication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Communication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Non_Renewer_flag__c.field-meta.xml
<CustomField>
    <fullName>Non_Renewer_flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Renewer flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IMAGE( 
CASE(   RecordType.Name  , 
&quot;Direct Debit&quot;, &quot;/resource/0000000000000/dd&quot;, /* dd */ 
&quot;Debit/Credit Card&quot;, &quot;/resource/0000000000000/cc2&quot;, /* cc */ 
&quot;Cash/Cheque&quot;, &quot;/resource/0000000000000/cash2&quot;, /* cash */ 
&quot;/resource/0000000000000/transparent3d&quot;), /* Transparent */ 
&quot;status color&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CancellationTriggerHandler.cls
public with sharing class CancellationTriggerHandler extends TriggerHandler {

    public CancellationTriggerHandler(){
        preventRecursiveTrigger(false);
    }

	public override void afterInsert(List<SObject> newObjects, Map<Id,SObject> newMap){

		List<Cancellation__c> newCancellations = (List<Cancellation__c>) newObjects;
		List<Club_Opportunity_Product__c> prodsToDelete = new List<Club_Opportunity_Product__c>();
	    Set<id> accountids = new Set<id>();
	    constants sc = new constants();
	    
	    for(Cancellation__c cn:newCancellations){
        	accountids.add(cn.Membership__c);       
	    }
	
	    Map<id,Account> accMap = new Map<id,account>([select id,Membership_Status__c,Mail_Stop__c,Email_Stop__c,
	                                                (select id,Non_Renewer_flag__c,status__c from Club_Opportunity_Products__r where status__c='Active' OR Status__c ='Pending'),
	                                                (select id,StageName from Opportunities where isclosed=FALSE),
	                                                (SELECT Id, Status__c, Type__c, recordTypeId FROM DD_Mandates__r WHERE Status__c ='Active'  AND recordTypeId = :sc.PaymentMethodDDRecordTypeId)
	                                                 from Account where id in :accountids]);
	    List<Club_Opportunity_Product__c> cprodstoupdate = new List<Club_Opportunity_Product__c>();
	    List<Payment_Method__c> pmListtoupdate = new List<Payment_Method__c>();
	    List<Opportunity> oppstoupdate = new List<Opportunity>();
	
	    for(Cancellation__c cn:newCancellations){
	        accMap.get(cn.Membership__c).Membership_Status__c = cn.Cancellation_Type__c;
	    	if(cn.Cancellation_Type__c=='Cancelled' || cn.Cancellation_Type__c=='Ex-Member'){
		        if(cn.Stop_Communication__c){
		            accMap.get(cn.Membership__c).Mail_Stop__c = true;
		            accMap.get(cn.Membership__c).Email_Stop__c = true;
		            accMap.get(cn.Membership__c).Mag_Stop__c = true;
		            accMap.get(cn.Membership__c).Promotional_Mailstop__c = true;
		            accMap.get(cn.Membership__c).Stop_Marketing_Email__c = true;
		            accMap.get(cn.Membership__c).Stop_Marketing_SMS__c = true;
		        }
		        for(Opportunity op: accMap.get(cn.Membership__c).Opportunities){
		        	op.StageName='Cancelled';
		            oppstoupdate.add(op);
		        }
		        for(Club_Opportunity_Product__c cop: accMap.get(cn.Membership__c).Club_Opportunity_Products__r){
		            Club_Opportunity_Product__c cp = cop;
		          /*  if(cn.Cancellation_Type__c=='Cancelled'){
		                cp.status__c = 'Cancelled';
		            }
		            else{
		                cp.Non_Renewer_flag__c = true;
		                if(cp.status__c=='Pending')cp.status__c = 'Cancelled';
		            }*/
		            if(cp.Status__c == 'Pending'){
		                //cp.status__c = 'Cancelled';
		                prodsToDelete.add(cp);
		            } else if(cp.Status__c == 'Active'){
		            	cp.Status__c = 'Cancelled';
		            	cprodstoupdate.add(cp);
		            }
		        }
		        for(Payment_Method__c pm: accMap.get(cn.Membership__c).DD_Mandates__r){
		           // Payment_Method__c p = pm;
		            pm.status__c = 'Cancelled';
		            pmListtoupdate.add(pm);
		        }                 
	    	}  
	    }
	    
	    update accMap.values();
	    update cprodstoupdate;
	    update oppstoupdate;
	    update pmListtoupdate;
	    delete prodsToDelete;

	}
}