force-app/main/default/objects/Account/fields/FreeSections__c.field-meta.xml
<CustomField>
    <fullName>FreeSections__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Free Sections?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/membership_renewal_code__c.field-meta.xml
<CustomField>
    <fullName>membership_renewal_code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Renewal Code</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts (membership renewal code)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <formula>Membership_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Type (Name)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Re_run_Batch_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Re_run_Batch_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-run Batch Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure (yrs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Member_Section__c.field-meta.xml
<CustomField>
    <fullName>Member_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member / Section</label>
    <referenceTo>Member_Section__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Renewable__c.field-meta.xml
<CustomField>
    <fullName>Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/SectionsAreFree__c.field-meta.xml
<CustomField>
    <fullName>SectionsAreFree__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections are Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/VIClass__c.field-meta.xml
<CustomField>
    <fullName>VIClass__c</fullName>
    <description>For Internal system use, do not modify</description>
    <label>VIClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Club_Product_Change__c/Club_Product_Change__c.object-meta.xml
<CustomObject>
    <label>Club Product Change</label>
    <nameField>
        <label>Club Product Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Product Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product_Change__c/fields/Allow_Auto_Switch__c.field-meta.xml
<CustomField>
    <fullName>Allow_Auto_Switch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Auto-Switch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product_Change__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Product Changes</relationshipLabel>
    <relationshipName>Club_Product_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Product_Change__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Product Changes (To)</relationshipLabel>
    <relationshipName>Club_Product_Changes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/Member_Section__c.object-meta.xml
<CustomObject>
    <label>Member / Section</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Member / Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members / Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Section__c/fields/Club_Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Club_Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Club Opportunity Product</label>
    <referenceTo>Club_Opportunity_Product__c</referenceTo>
    <relationshipLabel>Members / Sections</relationshipLabel>
    <relationshipName>Members_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Club_Opportunity_Product__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Club_Opportunity_Product__r.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RerunBatchCreateRenewals.cls
global class RerunBatchCreateRenewals implements Database.Batchable<sObject> { 
    
    global String query; 
    
    global RerunBatchCreateRenewals(){
        query = 'SELECT Id, FreeSections__c, Membership_Renewal_Code__c, Tenure2__c, Renewal_Date__c, Payment_Method2__c, Membership_Type_Name__c, ';
       query +=     '(SELECT Id, Name, Birthdate, Youth_Test_Passed_Date__c FROM Contacts WHERE RecordType.Name=\'Lead\' LIMIT 1), ';
       query +=     '(SELECT Id, RecordTypeId, Product__c, Product__r.VIClass__c, Product__r.SectionsAreFree__c FROM Club_Opportunity_Products__r WHERE Status__c = \'Active\') ';
       query += 'FROM Account ';
       query += 'WHERE Re_run_Batch_Renewal__c = true  AND Membership_Status__c != \'Cancelled\' AND Membership_Status__c != \'Non-Renewer\''; 
       query += 'AND Membership_Status__c != \'DD Payment Rejected\' AND Membership_Status__c != \'DD Rejected\' AND Membership_Status__c != \'DD Mandate Rejected\''; 
    
    }  
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('[BatchCreateRenewals.start]');
        if(Test.isRunningTest()) {
            return Database.getQueryLocator(query + ' LIMIT 200');
        }
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        System.debug('[BatchCreateRenewals.exe]');
        System.debug('[BatchCreateRenewals.execute] scope: ' +scope);

        Map<id,Club_Product__c> cpMap = new Map<id,Club_Product__c>([select id,name,Product_Detail__c, SectionsAreFree__c, Renewable__c,viclass__c,recordtypeid,(select Price__c,start_date__c,end_date__c, Payment_Type__c from Prices__r order by Start_Date__c) from club_product__c ]);


        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.optAllOrNone = false; 
        
        constants sc = new constants();

        Set<Id> accids = new Set<id>();
        List<Opportunity> newopps = new List<Opportunity>();
        Map<Integer,Opportunity> newoppMap = new Map<Integer,Opportunity>();
        
        Map<Integer,List<Club_Opportunity_Product__c>> newoppcpMap = new Map<Integer,List<Club_Opportunity_Product__c>>();
        
        Id opprenewalid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();  

        List<Account> accstoUpdate = new List<Account>();
        
        List<Club_Product_Change__c> cpclist = [select id,From__c,To__c from Club_Product_Change__c where Allow_Auto_Switch__c=TRUE];

        Integer i = 0;      
        for(Account a : scope) {
            Opportunity o = new Opportunity(accountid=a.id); 
            o.name = 'Renewal';
            o.RecordTypeId = opprenewalid;  
            o.StageName='Due';
            o.CloseDate = a.Renewal_Date__c;
            newopps.add(o);
            accids.add(a.id);
            List<Club_Opportunity_Product__c> cop = new List<Club_Opportunity_Product__c>();
            
            Decimal OppPrice = 0;
            boolean prodrenewable=false;
            id mtprod;
            for(Club_Opportunity_Product__c c : a.Club_Opportunity_Products__r) {
                if(c.recordtypeid==sc.mtsectRecordTypeId){
                    id prodtoget = c.product__c;
                    if(a.membership_renewal_code__c!=null){                     
                        prodtoget = a.membership_renewal_code__c;
                    }
                    mtprod = c.product__c;
                    prodrenewable = cpMap.get(prodtoget).Renewable__c;
                }
            }
            if(prodrenewable){
                for(Club_Opportunity_Product__c c : a.Club_Opportunity_Products__r) {
                    Club_Opportunity_Product__c cp = new Club_Opportunity_Product__c(Account__c=a.id,recordtypeid=c.recordtypeid,Product__c=c.Product__c,status__c='Pending');
                    Decimal Price=0;
                    id prodtoget = cp.product__c;
                    if(c.recordtypeid==sc.mtsectRecordTypeId){
                        if(a.membership_renewal_code__c!=null){
                            prodtoget = a.membership_renewal_code__c;
                            cp.Product__c = a.membership_renewal_code__c;
                        }
                        for(Club_Product_Change__c cpc : cpclist){
                            if(cpc.From__c==prodtoget){ 
                                String viclass ='';
                                viclass = cpmap.get(cpc.to__c).viclass__c;
                                system.debug(viclass);
                                Type t;
                                t = Type.forName('VI'+viclass);
                                if(t==null)t = Type.forName('VIDefault');
                                ValidationInterface v = (ValidationInterface)t.newInstance();
                                ID newprod = v.autoswitch(a,a.contacts[0],o,prodtoget,cpc.to__c);
                                cp.Product__c = newprod;
                                prodtoget = newprod;
                                mtprod = newprod;
                            }
                        }
                    }
                    system.debug(cpMap.get(prodtoget));
                    for(Price__c p:cpMap.get(prodtoget).Prices__r){
                        if(p.Start_Date__c<=a.renewal_date__c && (p.end_date__c>= a.renewal_date__c || p.end_date__c==null) && ((c.recordtypeid==sc.mtsectRecordTypeId && a.Payment_Method2__c == p.Payment_Type__c) || c.recordtypeid==sc.amsectRecordTypeId || c.recordtypeid == sc.sectionRecordTypeId)){
                            if(c.recordtypeid==sc.mtsectRecordTypeId || c.recordtypeid==sc.amsectRecordTypeId){
                                system.debug('Membership or Associate Type');
                                Price = p.Price__c;
                            }
                            else if((a.FreeSections__c != true && cpMap.get(mtprod).SectionsAreFree__c != true) && c.recordtypeid!=sc.mtsectRecordTypeId){
                                system.debug('Non-free Section');
                                Price = p.Price__c;
                            }
                            else if((a.FreeSections__c == true || cpMap.get(mtprod).SectionsAreFree__c == true) && c.recordtypeid!=sc.mtsectRecordTypeId){
                                 system.debug('Free Section');
                                 Price = 0;
                            }
                            break;
                        }
                    }
                    OppPrice += Price; 
                    cp.Price__c = price;
                    cop.add(cp);
                
                }
                if(a.membership_renewal_code__c!=null){
                    Account au = new Account(id=a.id);
                    au.membership_renewal_code__c = null;
                    accstoUpdate.add(au);
                }
                
                o.amount = OppPrice;
                newoppMap.put(i,o);
                
                newoppcpMap.put(i,cop);
                i++;
            }
        }
        
        if(accstoUpdate.size()>0)Database.update(accstoUpdate, dmo);
        Database.insert(newoppMap.values(), dmo);

        List<Club_Opportunity_Product__c> cops = new List<Club_Opportunity_Product__c>();

        for(integer i1:newoppMap.keySet()){
            for(Club_Opportunity_Product__c cop: newoppcpMap.get(i1)){
                cop.Opportunity__c = newoppMap.get(i1).id;
            }
            
            cops.addall(newoppcpMap.get(i1));
        }

        Database.insert(cops, dmo);
        
        List<Club_Opportunity_Product__c > activeprods = [select id,name,Account__c,product__c,product__r.name,status__c,(select id,name,Member__c from Members_Sections__r) from club_opportunity_product__c where status__c='Active' and Account__c in :accids];

        List<Member_Section__c> ms = new List<Member_Section__c>();
        
        for(Club_Opportunity_Product__c c: activeprods){
            for(Club_Opportunity_Product__c pendingprod: cops){
                if(pendingprod.account__c == c.account__c && c.product__c == pendingprod.product__c){
                    for(Member_Section__c m : c.Members_Sections__r){
                        Member_Section__c nms = new Member_Section__c(Club_Opportunity_Product__c = pendingprod.id, Member__c= m.member__c);
                        ms.add(nms);
                    }
                    
                }
            }
        }

        Database.insert(ms, dmo);
        for(Account a : scope){
            a.Re_run_Batch_Renewal__c = false;
        }
        update scope;
        
    }
    
    global void finish(Database.BatchableContext BC) {
        BatchUpdateCorrRenewals Batch = new BatchUpdateCorrRenewals();
        ID batchProcessId = Database.executeBatch(Batch);
    }
}