force-app/main/default/objects/Account/fields/FreeSections__c.field-meta.xml
<CustomField>
    <fullName>FreeSections__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Free Sections?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Renewable__c.field-meta.xml
<CustomField>
    <fullName>Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/SectionsAreFree__c.field-meta.xml
<CustomField>
    <fullName>SectionsAreFree__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections are Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/VIClass__c.field-meta.xml
<CustomField>
    <fullName>VIClass__c</fullName>
    <description>For Internal system use, do not modify</description>
    <label>VIClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Amendment_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amendment/Renewal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Associate_Member_Fee__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Fee__c</fullName>
    <label>Associate Member Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Date_Processed__c.field-meta.xml
<CustomField>
    <fullName>Date_Processed__c</fullName>
    <description>This is the date and time the entry was processed by Salesforce and added to the CSV export file</description>
    <label>Date Processed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>Membership_Subscription_Fee__c</fullName>
    <label>Membership Subscription Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Sections_fee__c.field-meta.xml
<CustomField>
    <fullName>Sections_fee__c</fullName>
    <label>Sections fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Total_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Fee__c</fullName>
    <label>Total Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchRenPriceFix.cls
global class BatchRenPriceFix implements Database.Batchable<sObject> { 
    
    global String QUERY = 'select id,name,createddate,account.FreeSections__c,account.renewal_date__c,account.Payment_Method2__c,(select id,recordtypeid,Product__c,product__r.viclass__c, Product__r.SectionsAreFree__c from Line_Items__r ),(select id,name,Sections_fee__c,Associate_Member_Fee__c, Membership_Subscription_Fee__c, Total_fee__c from Correspondence__r) from Opportunity where createddate=LAST_N_DAYS:5 and stagename=\'Due\''; 
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator(QUERY);
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> opps) {

        Map<id,Club_Product__c> cpMap = new Map<id,Club_Product__c>([select id,name,Product_Detail__c, SectionsAreFree__c, Renewable__c,viclass__c,recordtypeid,(select Price__c,start_date__c,end_date__c, Payment_Type__c from Prices__r order by Start_Date__c) from club_product__c ]);

		List<Club_Opportunity_Product__c> coptoupdate = new List<Club_Opportunity_Product__c>();

		List<Correspondence__c> corrstoupdate = new List<Correspondence__c>();

        constants sc = new constants();
	
        for(Opportunity o : opps) {
            Decimal OppPrice = 0;
            Decimal AmPrice = 0;
            Decimal SecPrice = 0;
            Decimal MtPrice = 0;
			id mtprod;
            for(Club_Opportunity_Product__c c : o.Line_Items__r) {
            	if(c.recordtypeid==sc.mtsectRecordTypeId){
                	mtprod = c.product__c;
                }
            }

            for(Club_Opportunity_Product__c c : o.Line_Items__r) {
	            Decimal Price=0;
	            id prodtoget = c.product__c;

                for(Price__c p:cpMap.get(prodtoget).Prices__r){
                    if(p.Start_Date__c<=o.account.renewal_date__c && (p.end_date__c>= o.account.renewal_date__c || p.end_date__c==null) && ((c.recordtypeid==sc.mtsectRecordTypeId && o.account.Payment_Method2__c == p.Payment_Type__c) || c.recordtypeid==sc.amsectRecordTypeId || c.recordtypeid == sc.cpsectRecordTypeId)){
                        if(c.recordtypeid==sc.mtsectRecordTypeId || c.recordtypeid==sc.amsectRecordTypeId){
                        	system.debug('Membership or Associate Type');
                        	Price = p.Price__c;
                        	if(c.recordtypeid==sc.mtsectRecordTypeId){
                        		MtPrice = p.Price__c;
                        	}
                        	else{
                        		AmPrice = p.Price__c;
                        	}
                        	
                        }
                        else if((o.account.FreeSections__c != true && cpMap.get(mtprod).SectionsAreFree__c != true) && c.recordtypeid!=sc.mtsectRecordTypeId){
                        	system.debug('Non-free Section');
                        	Price = p.Price__c;
                        	SecPrice += p.Price__c;
                        }
                       	else if((o.account.FreeSections__c == true || cpMap.get(mtprod).SectionsAreFree__c == true) && c.recordtypeid!=sc.mtsectRecordTypeId){
                       		 system.debug('Free Section');
                       		 Price = 0;
                       	}
                    }
                }
                OppPrice += Price; 
                c.Price__c = price;
                coptoupdate.add(c);
				
            }
            o.Amount = oppPrice;
            o.Correspondence__r[0].Sections_fee__c = SecPrice; 	
            o.Correspondence__r[0].Associate_Member_Fee__c = AmPrice;
            o.Correspondence__r[0].Membership_Subscription_Fee__c = MtPrice;    	
            o.Correspondence__r[0].Total_fee__c = oppPrice;    	
            o.Correspondence__r[0].Date_Processed__c = null;     	
			corrstoupdate.add(o.Correspondence__r[0]);
        }
        
        update opps;
        update coptoupdate;
        update corrstoupdate;

    	
    }


    global void finish(Database.BatchableContext BC) {}
    
}