force-app/main/default/objects/Account/fields/Hybrid_Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Hybrid_Membership_Number__c</fullName>
    <formula>IF(
 Old_MN__c = &quot;&quot;, 
 Membership_Number__c , 
 Old_MN__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hybrid Membership Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure (yrs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Hybrid_Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Hybrid_Membership_Number__c</fullName>
    <formula>Account__r.Hybrid_Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hybrid Membership Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Member_Section__c.field-meta.xml
<CustomField>
    <fullName>Member_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member / Section</label>
    <referenceTo>Member_Section__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Non_Renewer_flag__c.field-meta.xml
<CustomField>
    <fullName>Non_Renewer_flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Renewer flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Ended__c.field-meta.xml
<CustomField>
    <fullName>Date_Ended__c</fullName>
    <label>Date Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hybrid_Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Hybrid_Membership_Number__c</fullName>
    <formula>Account.Hybrid_Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hybrid Membership Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Amendment_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amendment/Renewal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/Member_Section__c.object-meta.xml
<CustomObject>
    <label>Member / Section</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Member / Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members / Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Section__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Club_Opportunity_Product__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Club_Opportunity_Product__r.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchUpdateCorrRenewals.cls
global class BatchUpdateCorrRenewals implements Database.Batchable<sObject> { 
    
    global String QUERY = 'select id,name,createddate,Amendment_Renewal__c,amendment_renewal__r.accountid from correspondence__c where correspondence_type__c=\'Renewal\' and Amendment_Renewal__c!=null and createddate=LAST_N_DAYS:5'; 
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator(QUERY);
    }
    
    global void execute(Database.BatchableContext BC, List<Correspondence__c> corrs) {

		Set<id> oppids = new set<id>();
		Set<id> accountids = new Set<id>();

		constants sc = new constants();


		for (correspondence__c c: corrs){
			oppids.add(c.Amendment_Renewal__c);
			accountids.add(c.Amendment_Renewal__r.accountid);
		}


		Map<id,Account> leadAccMap = new Map<id,Account>([select id, Renewal_Date__c, (Select Id, Salutation,FirstName,LastName, Youth_Test_Passed_Date__c, Tenure2__c,RecordTypeId,status__c,date_ended__c  from Contacts where  RecordTypeId = :sc.leadContactRecordTypeId AND Status__c = 'Active')  FROM Account WHERE Id in :accountids]);

		Map<id,Account> secAccMap = new Map<id,Account>([select id, Renewal_Date__c, (Select Id, Salutation,FirstName,LastName, Youth_Test_Passed_Date__c, Tenure2__c,RecordTypeId,status__c,date_ended__c  from Contacts where  RecordTypeId = :sc.secondaryContactRecordTypeId AND Status__c = 'Active')  FROM Account WHERE Id in :accountids]);

		Map<id,Account> assAccMap = new Map<id,Account>([select id, Renewal_Date__c, (Select Id, Salutation,FirstName,LastName, Youth_Test_Passed_Date__c, Tenure2__c,RecordTypeId,status__c,date_ended__c  from Contacts where  RecordTypeId = :sc.associateContactRecordTypeId AND Status__c = 'Active')  FROM Account WHERE Id in :accountids]);


 		Map<id,Opportunity> purchasedProductList = new Map<id,Opportunity>([SELECT Id , (select id, Hybrid_Membership_Number__c, Member_Section__c,
        									                                			Non_Renewer_flag__c, Opportunity__c, 
                                        												Member_Section__r.name, account__r.Renewal_Date__c,
                                        												Product__c, product__r.Name, Price__c, 
                                        												account__r.Membership_Code__c, Status__c,recordtypeid
                                        												from Line_Items__r)
                                        									FROM Opportunity
                                        									WHERE  Id IN :oppIds]);

		for(correspondence__c corr: corrs){

    		corr.date_processed__c=null;
    
    		string sections='';
    		decimal memprice=0;
    		decimal secprice=0;
    		decimal assprice=0;

        	for(Club_Opportunity_Product__c cop : purchasedProductList.get(corr.Amendment_Renewal__c).Line_Items__r){

				if(cop.recordtypeid==sc.cpsectRecordTypeId){sections+=cop.product__r.Name+' ';secprice+=cop.Price__c;}
				if(cop.recordtypeid==sc.mtsectRecordTypeId){corr.Renewal_Product_Code__c=cop.product__r.Name;memprice+=cop.Price__c;}
				if(cop.recordtypeid==sc.amsectRecordTypeId){assprice+=cop.Price__c;}
			}

			system.debug(corr.name+'---'+corr.amendment_renewal__r.accountid);
			system.debug('mem price---'+memprice);
			system.debug('sec price---'+secprice);
			system.debug('as price---'+assprice);

			corr.Associate_Member_Fee__c = assprice;
			corr.Sections_fee__c = secprice;corr.Sections__c=sections;
			corr.Membership_Subscription_Fee__c = memprice;
			corr.Total_Fee__c = memprice+secprice+assprice;

			for(Contact lc: leadAccMap.get(corr.Amendment_Renewal__r.AccountId).Contacts){
    			if(lc.status__c=='Active'){
					corr.Lead_Member__c = lc.Id;
/*                    corr.Lead_Member_Salutation__c =  lc.Salutation;
                    corr.Lead_Member_First_Name__c =  lc.FirstName;
                    corr.Lead_Member_Last_Name__c =  lc.LastName;
                    corr.Youth_Test_Passed_Date__c = lc.Youth_Test_Passed_Date__c;
*/
                    corr.Renewal_Date__c = leadAccMap.get(corr.Amendment_Renewal__r.AccountId).Renewal_Date__c.addmonths(12);
                    if(lc.Tenure2__c == null){
                        corr.Tenure__c =1;
                    } else {
                        corr.Tenure__c = lc.Tenure2__c+1;
                    }
                }
			}

			for(Contact sec: secAccMap.get(corr.Amendment_Renewal__r.AccountId).Contacts){
    			if(sec.status__c=='Active'){
					corr.Secondary_Member__c =  sec.Id;
/*                        corr.Second_Member_Salutation__c =  sc.Salutation;
                        corr.Second_Member_First_Name__c =  sc.FirstName;
                        corr.Second_Member_Last_Name__c =  sc.LastName;
*/
					if(sec.Tenure2__c == null ){
						corr.Tenure_Secondary__c = 1;
					} else {
						corr.Tenure_Secondary__c = sec.Tenure2__c+1;
					}
				}
			}

			for(Contact sec: assAccMap.get(corr.Amendment_Renewal__r.AccountId).Contacts){
				if(sec.status__c=='Active'){
					corr.Associate_Member__c =  sec.Id;
				}
			}
		}
		update corrs;        
    }
    
    global void finish(Database.BatchableContext BC) {}
}