force-app/main/default/objects/Account/fields/Last_Replacement_Card_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Replacement_Card_Date__c</fullName>
    <label>Last Replacement Card Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lead member associated with the membership.</description>
    <inlineHelpText>The lead member associated with the membership.</inlineHelpText>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure (yrs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>IMAGE(
CASE( Name ,
&quot;50 Years&quot;, &quot;/resource/0000000000000/fifty&quot;, /* fifty*/
&quot;Certificated Sites - Digital&quot;, &quot;/resource/0000000000000/other&quot;, /* other*/
&quot;CHH - Digital&quot;, &quot;/resource/0000000000000/chh3&quot;, /* chh*/
&quot;Complimentary&quot;, &quot;/resource/0000000000000/complimentary&quot;, /* complimentary*/
&quot;Honorary&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Honorary (VP)&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Digital&quot;, &quot;/resource/0000000000000/digital&quot;, /* online*/
&quot;Overseas - Digital Membership&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Overseas - Paper&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Paper&quot;, &quot;/resource/0000000000000/paper2&quot;, /* paper*/
&quot;Press Card Holder&quot;, &quot;/resource/0000000000000/press&quot;, /* press*/
&quot;Senior Youth - Digital&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Senior Youth - Paper&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Staff&quot;, &quot;/resource/0000000000000/staff&quot;, /* staff*/
&quot;Technical&quot;, &quot;/resource/0000000000000/tech&quot;, /* tech*/
&quot;Temporary Overseas Membership&quot;, &quot;/resource/0000000000000/tempoverseas&quot;, /* tempoverseas*/
&quot;Veteran - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran - Paper&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran Overseas - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Vice President&quot;, &quot;/resource/0000000000000/vp2&quot;, /* vp*/
&quot;Youth - Digital&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Youth - Paper&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Site Paper&quot;, &quot;/resource/0000000000000/ccc_site_paper&quot;, /* site*/
&quot;Site Digital&quot;, &quot;/resource/0000000000000/ccc_site_digital&quot;, /* site*/
&quot;/resource/0000000000000/trans_circle&quot;), /* Other */
&quot;Membership Status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Lead Member)</relationshipLabel>
    <relationshipName>Correspondence3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Last_Name__c</fullName>
    <label>Lead Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Salutation__c</fullName>
    <label>Lead Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Second_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Second_Member_First_Name__c</fullName>
    <label>Second Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Second_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Second_Member_Last_Name__c</fullName>
    <label>Second Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Second_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Second_Member_Salutation__c</fullName>
    <label>Second Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Secondary_Member__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Secondary Member)</relationshipLabel>
    <relationshipName>Correspondence2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Lead Tenure</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member_Section__c/Member_Section__c.object-meta.xml
<CustomObject>
    <label>Member / Section</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Member / Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members / Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Section__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Member / Sections</relationshipLabel>
    <relationshipName>Member_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CorrespondenceRest.cls
@RestResource(UrlMapping='/correspondence')
global class CorrespondenceRest {

    private static final String CORRESPONDENCE_TYPE_REPLACEMENT_CARD = 'Replacement Card';
    private static final constants sc = new constants();

    @HttpPost
    global static ResponseWrapper updateMemberDetails() {

        RestRequest req = RestContext.request;

        RequestDataWrapper requestData = (RequestDataWrapper) JSON.deserialize(req.requestBody.toString(), RequestDataWrapper.class);

        if(String.isBlank(requestData.membership) || String.isBlank(requestData.correspondenceType)) return buildResponse('', 'Invalid input parameters', false, 400);

        List<Account> memberships = [SELECT Payment_Method2__c, Renewal_Date__c, Last_Replacement_Card_Date__c FROM Account WHERE Id = :requestData.membership];        

        if(memberships.isEmpty()) return buildResponse('', 'The requested membership could not be found', false, 404);

        Account membershipToUse = memberships.get(0);

        if(membershipToUse.Last_Replacement_Card_Date__c == Date.today()) return buildResponse('', 'Replacement forbidden. Only one Replacement allowed per day', false, 403);

        Correspondence__c correspondenceToCreate = new Correspondence__c();

        if(requestData.correspondenceType == CORRESPONDENCE_TYPE_REPLACEMENT_CARD){
            buildCorrespondenceForReplacementCard(correspondenceToCreate, membershipToUse);
        } else {
            return buildResponse('', 'Incorrect Correspondence Type', false, 400);
        }

        try {
            insert correspondenceToCreate;
            updateMembership(membershipToUse);
        } catch (Exception ex) {
            return buildResponse('', ex.getMessage(), false, 500);
        }

        return buildResponse(correspondenceToCreate.Id, '', true, 201);
    }

    private static void buildCorrespondenceForReplacementCard(Correspondence__c correspondence, Account membership) {

        Contact nonRenewalLeadMember = getLeadMember(membership.Id);
        Contact secondaryMember = getSecondaryMember(membership.Id);

        correspondence.Membership__c = membership.Id;
        correspondence.Payment_Method__c = membership.Payment_Method2__c;
        correspondence.Member__c = nonRenewalLeadMember.Id;
        correspondence.Correspondence_date__c = Date.today();
        correspondence.Correspondence_Type__c = 'Replacement Card';
        correspondence.Lead_Member__c = nonRenewalLeadMember.Id;
        correspondence.Lead_Member_Salutation__c =  nonRenewalLeadMember.Salutation;
        correspondence.Lead_Member_First_Name__c =  nonRenewalLeadMember.FirstName;
        correspondence.Lead_Member_Last_Name__c =  nonRenewalLeadMember.LastName;
        correspondence.Youth_Test_Passed_Date__c =  nonRenewalLeadMember.Youth_Test_Passed_Date__c;
        correspondence.Tenure__c = nonRenewalLeadMember.Tenure2__c;
        correspondence.Renewal_Date__c = membership.Renewal_Date__c;

        if(secondaryMember != null){
            correspondence.Secondary_Member__c =  secondaryMember.Id;
            correspondence.Second_Member_Salutation__c =  secondaryMember.Salutation;
            correspondence.Second_Member_First_Name__c =  secondaryMember.FirstName;
            correspondence.Second_Member_Last_Name__c =  secondaryMember.LastName;
            correspondence.Tenure_Secondary__c = secondaryMember.Tenure2__c != null ? secondaryMember.Tenure2__c : 1.0;
        }
        correspondence.Sections__c = getNonRenewalSections(nonRenewalLeadMember);
    }

    private static void updateMembership(Account membership) {
        Account thisMembership = new Account();
        thisMembership.Id = membership.Id;
        thisMembership.Last_Replacement_Card_Date__c = Date.today();
        update thisMembership;
    }

    private static Contact getSecondaryMember(String membershipId) {
        List<Contact> secondaryMembers = [SELECT Salutation,FirstName,LastName, Tenure2__c, Age_Concession__c FROM Contact WHERE RecordTypeId = :sc.secondaryContactRecordTypeId AND AccountId = :membershipId AND Status__c = 'Active'];
        return secondaryMembers.isEmpty() ? null : secondaryMembers.get(0);
    }

    private static Contact getLeadMember(String membershipId) {
        List<Contact> leadMembers = [SELECT Id, Salutation,FirstName,LastName, Tenure2__c,Age_Concession__c, Youth_Test_Passed_Date__c, (SELECT Id,Price__c, Club_Opportunity_Product__c,
                                                    Club_Opportunity_Product__r.Hybrid_Membership_Number__c, Club_Opportunity_Product__r.Non_Renewer_flag__c, Club_Opportunity_Product__r.Opportunity__c,
                                                    Name,Club_Opportunity_Product__r.Product__c, Product_Name__c, Club_Opportunity_Product__r.Account__r.Membership_Code__c,
                                                    Status__c, Member__c, Membership_Number__c, Club_Opportunity_Product__r.RecordTypeId, Club_Opportunity_Product__r.Product__r.Name
                                            FROM Member_Sections__r
                                            WHERE Club_Opportunity_Product__r.RecordTypeId  = :sc.sectionRecordTypeId) FROM Contact WHERE RecordTypeId = :sc.leadContactRecordTypeId
                                            AND AccountId = :membershipId];
        return leadMembers.isEmpty() ? new Contact() : leadMembers.get(0);
    }

    private static String getNonRenewalSections(Contact nonRenewalLeadMember) {
        String nonRenewalSections = '';

        Double nonRenewalSectionPrice = 0;
        for(Member_Section__c cop : nonRenewalLeadMember.Member_Sections__r){
            if(cop.Status__c == 'Active'){
                if(nonRenewalSections != null){
                    nonRenewalSections += cop.Club_Opportunity_Product__r.Product__r.Name + ',';
                } else {
                    if(nonRenewalLeadMember.Member_Sections__r.size() > 1){
                        nonRenewalSections = cop.Club_Opportunity_Product__r.Product__r.Name + ',';
                    } else if (nonRenewalLeadMember.Member_Sections__r.size()== 1){
                        nonRenewalSections = cop.Club_Opportunity_Product__r.Product__r.Name;
                    }
                }

                if(nonRenewalSectionPrice != 0){
                    nonRenewalSectionPrice += cop.Price__c;
                } else {
                    nonRenewalSectionPrice = cop.Price__c;
                }

            }
        }

        nonRenewalSections = nonRenewalSections.removeEnd(',');
        return nonRenewalSections;
    }

    private static ResponseWrapper buildResponse(String recordId, String error, Boolean success, Integer statusCode) {
        ResponseWrapper responseWrapper = new ResponseWrapper();
        responseWrapper.id = recordId;
        responseWrapper.error = error;
        responseWrapper.success = success;
        responseWrapper.statusCode = statusCode;
        return responseWrapper;
    }

    global class RequestDataWrapper {
        global String membership;
        global String correspondenceType;
    }

    global class ResponseWrapper {
        global String id;
        global String error;
        global Boolean success;
        global Integer statusCode;
    }
}