force-app/main/default/objects/Account/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lead member associated with the membership.</description>
    <inlineHelpText>The lead member associated with the membership.</inlineHelpText>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <label>Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Gift_Code__c.field-meta.xml
<CustomField>
    <fullName>Gift_Code__c</fullName>
    <label>Gift Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Correspondence (Lead Member)</relationshipLabel>
    <relationshipName>Correspondence3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Last_Name__c</fullName>
    <label>Lead Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Salutation__c</fullName>
    <label>Lead Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_Country__c.field-meta.xml
<CustomField>
    <fullName>MGM_Country__c</fullName>
    <label>MGM Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_County__c.field-meta.xml
<CustomField>
    <fullName>MGM_County__c</fullName>
    <label>MGM County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>MGM_Organisation_Name__c</fullName>
    <label>MGM Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/MGM_Street__c.field-meta.xml
<CustomField>
    <fullName>MGM_Street__c</fullName>
    <label>MGM Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <formula>Membership__r.Organisation_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organisation Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/Member_Get_Member__c.object-meta.xml
<CustomObject>
    <description>Referral scheme to give existing members a gift when recommended friend joins</description>
    <label>Recommend A Friend</label>
    <nameField>
        <displayFormat>RAF-{00000000}</displayFormat>
        <label>Member Get Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommend A Friend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Get_Member__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lead</value>
        </filterItems>
        <filterItems>
            <field>Contact.Membership_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled,Ex-Member,Lapsed,Refer to Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Member_Get_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <description>The picklist field values should only represent the current gifts that are available for selection. However, the field will retain previous gift values that have been updated via data import, or from picklist values that are no longer available for selection.</description>
    <label>Gift</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club Site Voucher</fullName>
            </value>
            <value>
                <fullName>Foldable Camping Chair</fullName>
                <label>RAF - Camping Chair</label>
            </value>
            <value>
                <fullName>Golf Umbrella</fullName>
                <label>RAF - Umbrella</label>
            </value>
            <value>
                <fullName>Insulated Picnic Bag</fullName>
                <label>RAF - Cooler Bags</label>
            </value>
            <value>
                <fullName>1 - Small Fleece</fullName>
                <isActive>false</isActive>
                <label>1 - Small Fleece</label>
            </value>
            <value>
                <fullName>2 - Medium Fleece</fullName>
                <isActive>false</isActive>
                <label>2 - Medium Fleece</label>
            </value>
            <value>
                <fullName>3 - Large Fleece</fullName>
                <isActive>false</isActive>
                <label>3 - Large Fleece</label>
            </value>
            <value>
                <fullName>4 - X Large Fleece</fullName>
                <isActive>false</isActive>
                <label>4 - X Large Fleece</label>
            </value>
            <value>
                <fullName>5 - XX Large Fleece</fullName>
                <isActive>false</isActive>
                <label>5 - XX Large Fleece</label>
            </value>
            <value>
                <fullName>6 - XXX Large Fleece</fullName>
                <isActive>false</isActive>
                <label>6 - XXX Large Fleece</label>
            </value>
            <value>
                <fullName>Adventure Bottle</fullName>
                <isActive>false</isActive>
                <label>Adventure Bottle</label>
            </value>
            <value>
                <fullName>Badge</fullName>
                <isActive>false</isActive>
                <label>Badge</label>
            </value>
            <value>
                <fullName>CCC1-13324-Camper Hamper (Caravan)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Caravan)</label>
            </value>
            <value>
                <fullName>CCC1-13325-Camper Hamper (Motorhome)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Motorhome)</label>
            </value>
            <value>
                <fullName>CCC1-13326-Camper Hamper (Tent)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Tent)</label>
            </value>
            <value>
                <fullName>Camping in the Forest Voucher</fullName>
                <isActive>false</isActive>
                <label>Camping in the Forest Voucher</label>
            </value>
            <value>
                <fullName>Club Care Key Protection Policy</fullName>
                <isActive>false</isActive>
                <label>Club Care Key Protection Policy</label>
            </value>
            <value>
                <fullName>Coin</fullName>
                <isActive>false</isActive>
                <label>Coin</label>
            </value>
            <value>
                <fullName>European Drivers&apos; Handbook</fullName>
                <isActive>false</isActive>
                <label>European Drivers&apos; Handbook</label>
            </value>
            <value>
                <fullName>F - CITF</fullName>
                <isActive>false</isActive>
                <label>F - CITF</label>
            </value>
            <value>
                <fullName>F - CITF Voucher</fullName>
                <isActive>false</isActive>
                <label>F - CITF Voucher</label>
            </value>
            <value>
                <fullName>Five Pound Club Site Voucher</fullName>
                <isActive>false</isActive>
                <label>Five Pound Club Site Voucher</label>
            </value>
            <value>
                <fullName>Games Cards Club Sites</fullName>
                <isActive>false</isActive>
                <label>Games Cards Club Sites</label>
            </value>
            <value>
                <fullName>Gelert Camping Essentials Bottle</fullName>
                <isActive>false</isActive>
                <label>Gelert Camping Essentials Bottle</label>
            </value>
            <value>
                <fullName>Indy</fullName>
                <isActive>false</isActive>
                <label>Indy</label>
            </value>
            <value>
                <fullName>Lantern</fullName>
                <isActive>false</isActive>
                <label>Lantern</label>
            </value>
            <value>
                <fullName>Large Fleece</fullName>
                <isActive>false</isActive>
                <label>Large Fleece</label>
            </value>
            <value>
                <fullName>Medium Fleece</fullName>
                <isActive>false</isActive>
                <label>Medium Fleece</label>
            </value>
            <value>
                <fullName>Phillips Club Atlas</fullName>
                <isActive>false</isActive>
                <label>Phillips Club Atlas</label>
            </value>
            <value>
                <fullName>Pitch Up, Eat Local Book</fullName>
                <isActive>false</isActive>
                <label>Pitch Up, Eat Local Book</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/fields/Introduced_Membership__c.field-meta.xml
<CustomField>
    <fullName>Introduced_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Introduced Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Member_Get_Member_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MemberGetMemberTriggerHandler.cls
public with sharing class MemberGetMemberTriggerHandler  extends TriggerHandler{

    public MemberGetMemberTriggerHandler(){
        preventRecursiveTrigger(false);
    }

    public override void afterInsert(List<SObject> newObjects, Map<Id,SObject> newMap){
    
        List<Member_Get_Member__c> newRecords = (List<Member_Get_Member__c>) newObjects;
        Set<id> accountids = new Set<id>();
        Set<id> mgmIds = new Set<id>();
        constants c = new constants();
        List<Correspondence__c> corrList = new List<Correspondence__c>();
        
        for(Member_Get_Member__c cn:newRecords){
            accountids.add(cn.Introduced_Membership__c);
            mgmIds.add(cn.Id);     
        }
            
        Map<id,Account> accMap = new Map<id,Account>([select id, Renewal_Date__c, BillingStreet, BillingCountry, Payment_Method2__c, BillingState, Organisation_Name__c, BillingPostalCode, BillingCity, (Select Id, Salutation,FirstName,LastName from Contacts where RecordTypeId = :c.leadContactRecordTypeId ) FROM Account WHERE Id in :accountids]);
        List<Member_Get_Member__c> mgmList = new List<Member_Get_Member__c>([SELECT Id, Existing_Member__c, Existing_Member__r.Salutation,Existing_Member__r.FirstName, Existing_Member__r.AccountId,
                                                                        Existing_Member__r.LastName, Existing_Member__r.Account.BillingStreet, Existing_Member__r.Account.BillingCountry,
                                                                        Existing_Member__r.Account.BillingState, Existing_Member__r.Account.Organisation_Name__c,
                                                                        Existing_Member__r.Account.BillingCity, Existing_Member__r.Account.BillingPostalCode
                                                                         FROM  Member_Get_Member__c WHERE Id = : mgmIds]);
        for(Member_Get_Member__c cn:newRecords){ 
            //if(cn.RecordTypeId == c.associateContactRecordTypeId){
                Correspondence__c corr = new Correspondence__c();
                corr.Correspondence_Type__c = 'Member Get Member';
                corr.Correspondence_date__c =  system.today();
                corr.Lead_Member__c = cn.Existing_Member__c;
                //corr.Renewal_Date__c = accMap.get(cn.AccountId).Renewal_Date__c;
                corr.Gift_Code__c = cn.Gift__c;
                if(mgmList.size() > 0){
                    //system.debug(mgmList.get(cn.Introduced_Membership__r.Id).Contacts);
                    for(Member_Get_Member__c lc: mgmList){
                        if(lc.Id == cn.Id){
                            corr.Lead_Member_Salutation__c =  lc.Existing_Member__r.Salutation;
                            corr.Lead_Member_First_Name__c =  lc.Existing_Member__r.FirstName;
                            corr.Lead_Member_Last_Name__c =  lc.Existing_Member__r.LastName;    
                            corr.MGM_Street__c = lc.Existing_Member__r.Account.BillingStreet;
                            corr.MGM_Country__c = lc.Existing_Member__r.Account.BillingCountry;
                            corr.MGM_County__c = lc.Existing_Member__r.Account.BillingState;
                            corr.MGM_Organisation_Name__c = lc.Existing_Member__r.Account.Organisation_Name__c;
                            corr.MGM_Postcode__c = lc.Existing_Member__r.Account.BillingPostalCode;
                            corr.MGM_Town_City__c = lc.Existing_Member__r.Account.BillingCity;   
                            corr.Membership__c = lc.Existing_Member__r.AccountId; 
                            //corr.Payment_Method__c = accMap.get(lc.Existing_Member__r.AccountId).Payment_Method2__c;                                                                    
                    }
                }
                if(accMap.size() > 0){
                   // system.debug(accMap.get(cn.AccountId).Contacts);
                   /* for(Account am: accMap.get(cn.AccountId)){
                        corr.MGM_Street__c = am.BillingStreet;
                        corr.MGM_Country__c = am.BillingCountry;
                        corr.MGM_County__c = am.BillingState;
                        corr.MGM_Organisation_Name__c = am.Organisation_Name__c;
                        corr.MGM_Postcode__c = am.BillingPostalCode;
                        corr.MGM_Town_City__c = am.BillingCity;
                        
                        
                    }*/
                }
        
                if((cn.Gift__c).contains('Voucher')){
                    corr.Voucher_Expiry_Date__c = system.today().addMonths(18);
                }
                corrList.add(corr);
            }      
        }
        
        insert corrList;

    }

}