force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <description>Add a new Child to the Membership</description>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Associate_Member_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Date_of_Birth__c</fullName>
    <label>Associate Member Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_First_Name__c</fullName>
    <label>Associate Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Surname__c</fullName>
    <label>Associate Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_Title__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Title__c</fullName>
    <label>Associate Member Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Rev</fullName>
            </value>
            <value>
                <fullName>Sir</fullName>
            </value>
            <value>
                <fullName>Capt</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Sgt</fullName>
            </value>
            <value>
                <fullName>Corp</fullName>
            </value>
            <value>
                <fullName>Dr</fullName>
            </value>
            <value>
                <fullName>Prof</fullName>
            </value>
            <value>
                <fullName>Cllr</fullName>
            </value>
            <value>
                <fullName>Rt Hon</fullName>
            </value>
            <value>
                <fullName>Lady</fullName>
            </value>
            <value>
                <fullName>Lord</fullName>
            </value>
            <value>
                <fullName>Dame</fullName>
            </value>
            <value>
                <fullName>Duke</fullName>
            </value>
            <value>
                <fullName>Duchess</fullName>
            </value>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Countess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_1_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_1_Date_of_Birth__c</fullName>
    <label>Child 1 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_1_First_Name__c</fullName>
    <label>Child 1 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_1_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_1_Surname__c</fullName>
    <label>Child 1 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_2_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_2_Date_of_Birth__c</fullName>
    <label>Child 2 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_2_First_Name__c</fullName>
    <label>Child 2 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_2_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_2_Surname__c</fullName>
    <label>Child 2 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_3_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_3_Date_of_Birth__c</fullName>
    <label>Child 3 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_3_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_3_First_Name__c</fullName>
    <label>Child 3 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_3_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_3_Surname__c</fullName>
    <label>Child 3 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_4_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_4_Date_of_Birth__c</fullName>
    <label>Child 4 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_4_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_4_First_Name__c</fullName>
    <label>Child 4 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_4_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_4_Surname__c</fullName>
    <label>Child 4 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_5_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_5_Date_of_Birth__c</fullName>
    <label>Child 5 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_5_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_5_First_Name__c</fullName>
    <label>Child 5 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_5_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_5_Surname__c</fullName>
    <label>Child 5 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_6_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Child_6_Date_of_Birth__c</fullName>
    <label>Child 6 Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_6_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_6_First_Name__c</fullName>
    <label>Child 6 First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Child_6_Surname__c.field-meta.xml
<CustomField>
    <fullName>Child_6_Surname__c</fullName>
    <label>Child 6 Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasAssociate__c.field-meta.xml
<CustomField>
    <fullName>hasAssociate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Associate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasPartner__c.field-meta.xml
<CustomField>
    <fullName>hasPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Children__c</fullName>
    <label>Number of Children</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Email__c</fullName>
    <label>Secondary Member Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_First_Name__c</fullName>
    <label>Secondary Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Surname__c</fullName>
    <label>Secondary Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChangeRenewalControllerTests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ChangeRenewalControllerTests {

    static testMethod void ChangeRenewalTest() {
        // TO DO: implement unit test
        Date sDate = Date.newInstance(2015, 10, 1);
     	Date eDate = Date.newInstance(2016, 12, 31);
       RecordType rt = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Lead' limit 1 ];
       
       RecordType rt5 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName='Membership_Code' limit 1 ];
       Club_Product__c cp2 = new Club_Product__c(name = 'testing2',Product_Detail__c = 'testing Club Product', RecordTypeId =rt5.Id);
       insert cp2;
       
       Account acc = new Account (Name = 'Patel', Membership_Code__c = cp2.Id, Renewal_Date__c = Date.newInstance(2018,01,29));
       insert acc;
       
       Lead lead = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
      						Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
      						Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2', 
      						Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
      						Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6', 
      						Child_6_Surname__c='Golf', Payment_Method__c='Debit / Credit Card', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
      						 Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.',
                           Child_1_Date_of_Birth__c = Date.today(),  Child_2_Date_of_Birth__c = Date.today(),  Child_3_Date_of_Birth__c = Date.today(),
                           Child_4_Date_of_Birth__c = Date.today(),  Child_5_Date_of_Birth__c = Date.today(),  Child_6_Date_of_Birth__c = Date.today(),
                           Associate_Member_Date_of_Birth__c = Date.today(), Secondary_Member_Title__c = 'Mr.');
      insert lead;
      
       
       Lead lead2 = new Lead(LastName = 'Golf', Email = 'yo@yo.com', sections__c = 'Association of Lightweight Camper', Company='Testco', hasPartner__c =true,
      						Secondary_Member_First_Name__c = 'Mrs Golf', Secondary_Member_Surname__c = 'Golf', Secondary_Member_Email__c = 'golf@yo.com',
      						Number_of_Children__c = '6', Child_1_First_Name__c ='Child 1', Child_1_Surname__c='Golf',  Child_2_First_Name__c ='Child 2', 
      						Child_2_Surname__c='Golf', Child_3_First_Name__c ='Child 3', Child_3_Surname__c='Golf',  Child_4_First_Name__c ='Child 4',
      						Child_4_Surname__c='Golf', Child_5_First_Name__c ='Child 5', Child_5_Surname__c='Golf', Child_6_First_Name__c ='Child 6', 
      						Child_6_Surname__c='Golf', Payment_Method__c='Direct Debit', hasAssociate__c = true, Associate_Member_First_Name__c = 'Assoic',
      						 Associate_Member_Surname__c = 'Assoc Surname', Associate_Member_Title__c = 'Mr.',
                           Child_1_Date_of_Birth__c = Date.today(),  Child_2_Date_of_Birth__c = Date.today(),  Child_3_Date_of_Birth__c = Date.today(),
                           Child_4_Date_of_Birth__c = Date.today(),  Child_5_Date_of_Birth__c = Date.today(),  Child_6_Date_of_Birth__c = Date.today(),
                           Associate_Member_Date_of_Birth__c = Date.today(), Secondary_Member_Title__c = 'Mr.');
      insert lead2;
      
      RecordType rt3 = [Select Id from RecordType Where SobjectType = 'Contact' AND DeveloperName='Associate' limit 1 ];
      Contact con = new Contact(FirstName = 'Tony', LastName = 'Golf', Phone = '01232324', RecordTypeId =rt3.Id, AccountId = acc.Id);
      insert con;
            
      RecordType rt2 = [Select Id from RecordType Where SobjectType = 'Club_Product__c' AND DeveloperName='Membership_Code' limit 1 ];
      Club_Product__c cp = new Club_Product__c(name = 'testing',Product_Detail__c = 'testing Club Product', RecordTypeId =rt2.Id);
      insert cp; 
            
      Price__c p = new Price__c(Start_Date__c = sDate, End_Date__c = eDate, Product__c= cp.id, Price__c = 44);
      insert p;
      
      //Date sDate = Date.newInstance(2015, 10, 15);
      RecordType rt4 = [Select Id from RecordType Where SobjectType = 'Opportunity' AND Name='Renewal' limit 1 ];
      Opportunity opp = new Opportunity(Name='testing2', CloseDate= sDate,StageName='Closed Won', Account=acc, RecordTypeId=rt4.Id);
      insert opp;
      
      Test.setCurrentPage(Page.ChangeRenewal);
     /* ChangeRenewalController controller = new ChangeRenewalController(new ApexPages.StandardController(opp));
      controller.lea = lead;
      controller.step1();
      controller.step2();
      controller.step3();
      controller.step4();
     // controller.changepayment();
      Map<string,club_product__c> mapPrices = new Map<string,club_product__c>();
      mapprices.put('Associate Member', cp);
      //ChangeRenewalController.sectionSelectWrapper ssw= new ChangeRenewalController.sectionSelectWrapper(cp);
      //ChangeRenewalController.sectionSelectWrapper ssw1= new ChangeRenewalController.sectionSelectWrapper(cp, 99.9);
      //ChangeRenewalController.sectionSelectWrapper ssw2= new ChangeRenewalController.sectionSelectWrapper(cp, true);
      //ChangeRenewalController.sectionSelectWrapper ssw3= new ChangeRenewalController.sectionSelectWrapper(cp, 99.9, true);
      //List<ChangeRenewalController.sectionSelectWrapper> sections = new List<ChangeRenewalController.sectionSelectWrapper>();
      //sections.add(ssw);
     // sections.add(ssw1);
     // sections.add(ssw2);
      //sections.add(ssw2);
      //controller.sections = sections;
      
     // ChangeRenewalController.sectionSelectWrapper ssw4= new ChangeRenewalController.sectionSelectWrapper(cp, 99.9);
      //List<ChangeRenewalController.sectionSelectWrapper> sections2 = new List<ChangeRenewalController.sectionSelectWrapper>();
      //sections2.add(ssw4);
      //controller.sections = sections2;
      controller.cAssocMember = con;
     // controller.mapPrices = mapPrices;
//      String payform = controller.payform;
      controller.cAssocMember = null;
      Contact cAssocMember = controller.cAssocMember;
      List<SelectOption> membershipTypeOptions = controller.membershipTypeOptions;
      controller.lea = lead2;
      PageReference confirm = controller.confirm();*/
    }
}