force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Reinstatement.recordType-meta.xml
<RecordType>
    <fullName>Reinstatement</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Reinstatement</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/OpportunityPaymentHandler.cls
/*
 * @Who   Alasdair Leggat <alasdair.leggat@weare4c.com>
 * @What  Class to reopen Opps and Club Products when Direct Debit payments rejected
 * @When  2019-08-29
 */

public class OpportunityPaymentHandler {
    private static final String REJECTED_STATUS = 'DD Rejected';

    /*
     *    reopenOppsAndProducts
     *    Method to reopen Opps and Club Products with Rejected Payment Methods
     *    Return void
     */
    public static void reopenOppsAndProducts(Map<Id, Account> oldMemberships, List<Account> updatedMemberships){
        // get rejected payment methods
        List<Account> rejectedMemberships = getRejectedMemberships(oldMemberships, updatedMemberships);
        
        if(rejectedMemberships.isEmpty()){
            return;
        }
        
        // get opportunities
        List<Opportunity> opps = getOpportunities(rejectedMemberships);
        
        if(opps.isEmpty()){
            return;
        }
        
        // get club opportunity products
        List<Club_Opportunity_Product__c> clubOppProducts = getOpportunityProducts(rejectedMemberships);
        
        if(clubOppProducts.isEmpty()){
            return;
        }
        
        // update opportunities stage
        updateOpportunitiesStage(opps);
        
        // update club opportunity products status
        updateClubOppProductsStatus(clubOppProducts);
        
        // update membership renewal dates
        updateMembershipRenewalDates(rejectedMemberships);
          
    }
    
    
    /*
     *    getRejectedMemberships
     *    Method to filter Memberships with Status changed to DD Rejected and return them
     *    Return List<Account>
     */
    private static List<Account> getRejectedMemberships(Map<Id, Account> oldMemberships, List<Account> updatedMemberships){
        Set<Id> rejectedMembershipIds = new Set<Id>();
        
        // loop over new memberhips
        for(Account updatedMembership: updatedMemberships){
            
            // get old payment method
            Account oldMembership = oldMemberships.get(updatedMembership.Id);
            
            // check if status changed to DD Rejected
            if(updatedMembership.Membership_Status__c  == REJECTED_STATUS && oldMembership.Membership_Status__c  != REJECTED_STATUS){
                rejectedMembershipIds.add(updatedMembership.Id);
            }
        }
        
        // set which opp record types to filter on
        List<String> oppRecordTypes = new List<String>{
            'Renewal',
            'New Membership',
            'Reinstatement'
        };
		
        // get payment methods
        List<Account> memberships = [SELECT Id, Renewal_Date__c,
                                     (
                                         SELECT Id, StageName
                                         FROM Opportunities
                                         WHERE RecordTypeId IN :getOppRecordTypeIds(oppRecordTypes)
                                         ORDER BY CreatedDate DESC
                                         LIMIT 1
                                     ),
                                     (
                                         SELECT Id, Status__c
                                         FROM Club_Opportunity_Products__r
                                         ORDER BY CreatedDate DESC
                                         LIMIT 1
                                     )
                                     FROM Account 
                                     WHERE Id IN :rejectedMembershipIds];
        
        return memberships;
        
    }
    
    
    /*
     *    getOppRecordTypeIds
     *    Method to get record type ids
     *    Return List<Id>
     */
    private static List<Id> getOppRecordTypeIds(List<String> recordTypes){
        List<Id> recordTypeIds = new List<Id>();
        
        // get opp record type ids
        for(String recordType: recordTypes){
            recordTypeIds.add(
            	Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(recordType).getRecordTypeId()
            );
        }
        
        return recordTypeIds;
    }
    
    
    /*
     *    getOpportunities
     *    Method to get club opportunities
     *    Return List<Opportunity>
     */
    private static List<Opportunity> getOpportunities(List<Account> memberships){
        List<Opportunity> opps = new List<Opportunity>();
        
        // loop over memberships
        for(Account membership: memberships){
            opps.addAll(membership.Opportunities);
        }
        
        return opps;
    }
    
    /*
     *    getOpportunityProducts
     *    Method to get club opportunity products
     *    Return List<Club_Opportunity_Product__c>
     */
    private static List<Club_Opportunity_Product__c> getOpportunityProducts(List<Account> memberships){
        List<Club_Opportunity_Product__c> clubOppProducts = new List<Club_Opportunity_Product__c>();
        
        // loop over memberships
        for(Account membership: memberships){
            clubOppProducts.addAll(membership.Club_Opportunity_Products__r);
        }
        
        return clubOppProducts;
    }
    
    
    /*
     *    updateMembershipRenewalDates
     *    Method to update parent Memberships renewal date field back by 1 year
     *    Return void
     */
    private static void updateMembershipRenewalDates(List<Account> memberships){            
		// loop over memberships
        for(Account membership: memberships){
            // get renewal date value
            Date renewalDate = membership.Renewal_Date__c;
            
            // put renewal date back 1 year
            membership.Renewal_Date__c = renewalDate.addDays(-365);
        }    
        
        System.debug('memberships: ' + memberships);
        
        // update membership
        try{
            update memberships;
        } catch(DMLException e){
            System.debug('[OpportunityPaymentHandler] Error updating Memberships: ' + e.getMessage());
        }
        
    }
    

	/*
     *    updateOpportunitiesStage
     *    Method to update Opportunities stages to Due 
     *    Return void
     */    
    private static void updateOpportunitiesStage(List<Opportunity> opps){
        
        // loop over payment methods
        for(Opportunity opp: opps){
            opp.StageName = 'Due';
        }
        
        // update opp
        try{
            update opps;
        } catch(DMLException e){
            System.debug('[OpportunityPaymentHandler] Error updating Opportunities: ' + e.getMessage());
        }
    }
    

	/*
     *    updateClubOppProductsStatus
     *    Method to update club opportunity products statuses to Pending
     *    Return void
     */     
    private static void updateClubOppProductsStatus(List<Club_Opportunity_Product__c> clubOppProducts){
        // loop over club opp products and update status field
        for(Club_Opportunity_Product__c clubOppProduct: clubOppProducts){
            clubOppProduct.Status__c = 'Pending';
        }
        
        // update club opp products
        try{
            update clubOppProducts;
        } catch(DMLException e){
            System.debug('[OpportunityPaymentHandler] Error updating Club Opportunity Products: ' + e.getMessage());
        }
    }
    

}