force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Renewable__c.field-meta.xml
<CustomField>
    <fullName>Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product_Change__c/Club_Product_Change__c.object-meta.xml
<CustomObject>
    <label>Club Product Change</label>
    <nameField>
        <label>Club Product Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Product Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product_Change__c/fields/Allow_Auto_Switch__c.field-meta.xml
<CustomField>
    <fullName>Allow_Auto_Switch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Auto-Switch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product_Change__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Product Changes</relationshipLabel>
    <relationshipName>Club_Product_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Product_Change__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Product Changes (To)</relationshipLabel>
    <relationshipName>Club_Product_Changes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <formula>TEXT ( Account.Membership_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/MembershipRenewalFilterControllerTest.cls
/*
 * @Who   Alasdair Leggat <alasdair.leggat@weare4c.com>
 * @What  Test class for MembershipRenewalFilterController 
 * @When  2019-09-05
 */

@isTest
public class MembershipRenewalFilterControllerTest {

    @testSetup
    static void setup(){
        List<Account> memberships = new List<Account>();
        
        // test cancelled membership
        Account cancelledMembership = new Account(
            Name = 'Cancelled',
            Membership_Status__c = 'Cancelled'
        );
        memberships.add(cancelledMembership);
        
        // test non renewer, renewal over 2 months from today
        Account nonRenewerOutsideRenewalPeriod = new Account(
            Name = 'Non Renewer, Outside Renewal Period',
            Membership_Status__c = 'Non-Renewer',
            Renewal_Date__c = Date.today().addDays(90)
        );
        memberships.add(nonRenewerOutsideRenewalPeriod);
        
        // test non renewer, renewal within 2 months of today
        Account nonRenewerWithinRenewalPeriod = new Account(
            Name = 'Non Renewer, Within Renewal Period',
            Membership_Status__c = 'Non-Renewer',
            Renewal_Date__c = Date.today().addDays(30)
        );
        memberships.add(nonRenewerWithinRenewalPeriod);
        
        insert memberships;
    }
    
    @isTest
    static void testCancelledStatus(){
        Id membershipId = [SELECT Id FROM Account WHERE Name='Cancelled' LIMIT 1].get(0).Id;
        
        // run filter method
        String returnMessage = MembershipRenewalFilterController.doFilterMembership(membershipId);
        
        // check return message is the cancelled one
        System.assertEquals(MembershipRenewalFilterController.CANCELLED_MSG, returnMessage);
    }
    
    @isTest
    static void testNonRenewerOutsideRenewalPeriod(){
        // membership not in renewal period yet
        Id membershipId = [SELECT Id FROM Account WHERE Name='Non Renewer, Outside Renewal Period' LIMIT 1].get(0).Id;
        
        // run filter method
        String returnMessage = MembershipRenewalFilterController.doFilterMembership(membershipId);
        
        // check return message is the cancelled one
        System.assertEquals(MembershipRenewalFilterController.RENEWAL_MSG, returnMessage);
    }
    
    @isTest
    static void testNonRenewerWithinRenewalPeriod(){
        // membership in renewal period 
        Account membership = [SELECT Id FROM Account WHERE Name='Non Renewer, Within Renewal Period' LIMIT 1].get(0);
        
        // run filter method
        String returnMessage = MembershipRenewalFilterController.doFilterMembership(membership.Id);
        
        // check return message is the cancelled one
        System.assertEquals(MembershipRenewalFilterController.NON_RENEWER_MSG, returnMessage);
        
        MembershipRenewalFilterController.doNonRenewalContinue(membership.Id);
        
        // check membership status updated
        membership = [SELECT Id, Membership_Status__c FROM Account WHERE Name='Non Renewer, Within Renewal Period' LIMIT 1].get(0);
        
        System.assertEquals('Paid', membership.Membership_Status__c);
    }

    @isTest
    static void testNonRenewerWithinRenewalPeriodRenewableProduct(){
        Club_Product__c productFrom = new Club_Product__c(Renewable__c=true);
        Club_Product__c productTo = new Club_Product__c(Renewable__c=true);
        insert new List<Club_Product__c>{productTo,productFrom};

        Opportunity opp = new Opportunity(Name='Test opp',StageName='Prospecting',CloseDate=Date.today());
        insert opp;
        // membership in renewal period 
        Account membership = [SELECT Id FROM Account WHERE Name='Non Renewer, Within Renewal Period' LIMIT 1].get(0);

        Contact contact = new Contact(AccountId=membership.Id, LastName='Test con');
        insert contact;

        Id sectionRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.getRecordTypeInfosByName().get('Membership Code').getRecordTypeId();
        Club_Opportunity_Product__c oppProduct = new Club_Opportunity_Product__c(Status__c='Active',Account__c=membership.Id, Product__c = productFrom.Id, Opportunity__c=opp.Id,RecordTypeId=sectionRecordTypeId);
        insert oppProduct;

        Club_Product_Change__c productChange = new Club_Product_Change__c(Allow_Auto_Switch__c=true, From__c=productFrom.Id, To__c=productTo.Id);
        insert productChange;
        // run filter method
        String returnMessage = MembershipRenewalFilterController.doFilterMembership(membership.Id);
        
        // check return message is the cancelled one
        System.assertEquals(MembershipRenewalFilterController.NON_RENEWER_MSG, returnMessage);
        
        MembershipRenewalFilterController.doNonRenewalContinue(membership.Id);
        
        // check membership status updated
        membership = [SELECT Id, Membership_Status__c FROM Account WHERE Name='Non Renewer, Within Renewal Period' LIMIT 1].get(0);
        
        System.assertEquals('Paid', membership.Membership_Status__c);
    }
}