force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReinstatePaymentController.cls
public with sharing class ReinstatePaymentController {


    @AuraEnabled
    public static MembershipInfo getMembershipInfo(String recordId) {

        List<Account> accounts = [SELECT Renewal_Date__c, Payment_Method2__c, Membership_Code__r.Name, BillingStreet, BillingPostalCode, BillingCity, BillingCountry, BillingState
                                    FROM Account WHERE Id = :recordId];

        if(accounts.isEmpty()) return new MembershipInfo();

        Account accountToUse = accounts.get(0);

        Lead lead = setupLead(accountToUse);

        List<Club_Product__c> clubProducts = [SELECT RecordType.Name, Name, Product_Detail__c,
                                                    (SELECT Price__c, Start_Date__c, End_Date__c, Payment_Type__c FROM Prices__r ORDER BY Start_Date__c)
                                              FROM Club_Product__c  ORDER BY Name];

        Decimal membershipCost = calculateMembershipCost(accountToUse, lead, clubProducts);
        Decimal associateMemberCost = calculateAssociateMemberCost(accountToUse);
        List<Section> allSections = getAllSections(accountToUse);
        List<Section> selectedSections = getSelectedSections(allSections, accountToUse, lead);

        Decimal totalCost = calculateTotalCost(membershipCost, associateMemberCost, selectedSections);

        return new MembershipInfo(membershipCost, associateMemberCost, totalCost, selectedSections, lead);
    }

    private static Lead setupLead(Account account) {

        constants sc = new constants();

        List<Contact> primaryMembers = [SELECT Salutation, Title, FirstName, LastName, Birthdate, Email FROM Contact WHERE AccountId = :account.Id AND RecordTypeId = :sc.leadContactRecordTypeId LIMIT 1];

        Lead lead = new Lead();
        lead.LastName = account.Id;
        lead.Company = account.Id;
        lead.Status = 'Open';
        lead.Payment_Method__c = account.Payment_Method2__c;
        lead.Email = primaryMembers.isEmpty() ? '' : primaryMembers.get(0).Email;
        lead.Membership_Code__c = account.Membership_Code__r.Name;
        lead.Street = account.BillingStreet;
        lead.PostalCode = account.BillingPostalCode;
        lead.City = account.BillingCity;
        lead.Country = account.BillingCountry;
        lead.State = account.BillingState;

        return lead;
    }

    private static Decimal calculateMembershipCost(Account account, Lead lead, List<Club_Product__c> clubProducts) {
        Decimal memberShipCost = 0;

        Date renewalDate = account.Renewal_Date__c;

        while(renewalDate <= Date.today()){

            for(Club_Product__c clubProduct : clubProducts){
                if(clubProduct.Name == lead.Membership_Code__c && clubProduct.RecordType.Name == 'Membership Code'){

                    Boolean found = false;

                    for(Price__c priceFromClubProduct : clubProduct.Prices__r){
                        if(priceFromClubProduct.Start_Date__c <=renewalDate && (priceFromClubProduct.End_Date__c >=renewalDate || priceFromClubProduct.End_Date__c==null) && priceFromClubProduct.Payment_Type__c == lead.Payment_Method__c){
                            memberShipCost += priceFromClubProduct.Price__c;
                            found = true;
                            break;
                        }
                    }

                    if(!found){
                        for(Price__c priceFromClubProduct : clubProduct.Prices__r){
                            if(priceFromClubProduct.Start_Date__c <=renewalDate && (priceFromClubProduct.End_Date__c >=renewalDate || priceFromClubProduct.End_Date__c==null)){
                                memberShipCost += priceFromClubProduct.Price__c;
                                found = true;
                                break;
                            }
                        }
                    }
                }
            }
            renewalDate = renewalDate.addMonths(12);
        }

        return memberShipCost;
    }

    private static Decimal calculateAssociateMemberCost(Account account) {
        constants sc = new constants();

        Decimal associateMemberCost = 0;

        Date renewalDate = account.Renewal_Date__c;

        List<Club_Opportunity_Product__c> clubOpportunityProducts = [SELECT Product__r.Product_Detail__c, Product__r.Name FROM Club_Opportunity_Product__c
                                                                        WHERE Account__c = :account.Id
                                                                        AND Status__c = 'Cancelled'
                                                                        AND RecordTypeId = :sc.amsectRecordTypeId];

        List<Club_Product__c> clubProducts =  [SELECT Name, Product_Detail__c, (SELECT Price__c,Start_Date__c,End_Date__c FROM Prices__r  ORDER BY Start_Date__c)
                                                FROM Club_Product__c WHERE RecordType.Name='Associate Membership' ORDER BY Name];

        while(renewalDate <= Date.today()){

            for(Club_Opportunity_Product__c c : clubOpportunityProducts){

                for(Club_Product__c clubProduct : clubProducts){

                    for(Price__c priceFromClubProduct : clubProduct.Prices__r){
                        if(priceFromClubProduct.Start_Date__c <= renewalDate && (priceFromClubProduct.End_Date__c >= renewalDate || priceFromClubProduct.End_Date__c == null)){
                            if(associateMemberCost==null) associateMemberCost = 0;
                            associateMemberCost += priceFromClubProduct.Price__c;
                        }
                    }
                }
            }
            renewalDate = renewalDate.addMonths(12);
        }
        return associateMemberCost;
    }

    private static List<Section> getAllSections(Account account) {
        List<Section> sections = new List<Section>();


        for (Club_Product__c clubProduct : [SELECT Name, Product_Detail__c, (SELECT Price__c, Start_Date__c, End_Date__c FROM Prices__r ORDER BY Start_Date__c)
                                            FROM Club_Product__c WHERE RecordType.Name = 'Section' ORDER BY Name]) {

            Decimal totalPrice = 0;

            Date renewalDate = account.Renewal_Date__c;

            while (renewalDate <= Date.today()) {

                for (Price__c priceFromClubProduct : clubProduct.Prices__r) {

                    if (priceFromClubProduct.Start_Date__c <= renewalDate && (priceFromClubProduct.End_Date__c >= renewalDate || priceFromClubProduct.End_Date__c == null)) {
                        totalPrice += priceFromClubProduct.Price__c;
                    }
                }
                renewalDate = renewalDate.addMonths(12);
            }
            sections.add(new Section(clubProduct.Name, clubProduct.Product_Detail__c, totalPrice));
        }
        return sections;
    }

    private static List<Section> getSelectedSections(List<Section> sections, Account account, Lead lead) {

        List<Section> selectedSections = new List<Section>();

        constants sc = new constants();
        List<String> cancelledClubProducts = new List<String>();

        for (Club_Opportunity_Product__c opportunityProduct : [SELECT Product__r.Product_Detail__c, Product__r.Name FROM Club_Opportunity_Product__c
                                            WHERE Account__c = :account.Id
                                            AND Status__c = 'Cancelled'
                                            AND RecordTypeId = :sc.sectionRecordTypeId]){
            cancelledClubProducts.add(opportunityProduct.Product__r.Name);
        }

        lead.sections__c = String.join(cancelledClubProducts,':');

        if(lead.sections__c != null){

            Set<String> selectedSectionNames = new Set<String>(lead.sections__c.split(':',-2));

            for (Section section : sections){

                if(selectedSectionNames.contains(section.name)){
                    section.selected = true;
                    selectedSections.add(section);
                }
            }
        }
        return selectedSections;
    }

    private static Decimal calculateTotalCost(Decimal membershipCost, Decimal associateMemberCost, List<Section> selectedSections) {
        Decimal totalCost = 0;

        if(membershipCost != null) totalCost += membershipCost;
        if(associateMemberCost != null) totalCost += associateMemberCost;

        for(Section section : selectedSections){
            if(section.selected) totalCost += section.price;
        }

        return totalCost;
    }


    @AuraEnabled
    public static String createLead(String leadJson) {

        Lead lead = (Lead) JSON.deserialize(leadJson, Lead.class);

        try {
            insert lead;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return lead.Id;
    }

    public class MembershipInfo {
        @AuraEnabled
        public Decimal membershipCost;
        @AuraEnabled
        public Decimal associateMemberCost;
        @AuraEnabled
        public Decimal totalCost;
        @AuraEnabled
        public List<Section> selectedSections;
        @AuraEnabled
        public Lead lead;


        public MembershipInfo() {}

        public MembershipInfo(Decimal membershipCost, Decimal associateMemberCost, Decimal totalCost, List<Section> selectedSections, Lead lead) {
            this.membershipCost = membershipCost;
            this.associateMemberCost = associateMemberCost;
            this.totalCost = totalCost;
            this.selectedSections = selectedSections;
            this.lead = lead;
        }
    }

    public class Section {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String productDetail;
        @AuraEnabled
        public Decimal price;
        @AuraEnabled
        public Boolean selected;

        public Section(String name, String productDetail, Decimal price) {
            this.name = name;
            this.productDetail = productDetail;
            this.price = price;
            this.selected = false;
        }
    }
}