force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <formula>Membership_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Type (Name)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Membership_Length__c.field-meta.xml
<CustomField>
    <fullName>Membership_Length__c</fullName>
    <label>Membership Length (Months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>Account.Membership_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Type (Name)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership_Code__c/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <label>Membership Type (Name)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/VIDigital.cls
Public class VIDigital implements ValidationInterface {
    private static final String YOUTH_DIGITAL_MEMBERSHIP_TYPE = 'Youth - Digital';
    private static final String YOUNG_CAMPER_MEMBERSHIP_TYPE = 'Young Camper';

	//private Id adminProfileId = [SELECT Id FROM Profile WHERE Name like '%System Administrator%' LIMIT 1];
	//private Id memDdminProfileId = [SELECT Id FROM Profile WHERE Name like '%Membership Admin%' LIMIT 1];
    public void validateAtRenewal(lead l){}
    public void validate(lead l) {
        System.debug ('-------Inside digital validate-------');
        Account a;
        if(l.Company.startswith('006')){
        	Opportunity o = [select accountid from opportunity where id=:l.company limit 1];
        	a = [select id,Membership_Code__c,Date_Joined__c,renewal_date__c,(select id,name,closedate from opportunities where recordtype.name='Renewal' and stagename='Complete' order by CloseDate desc) from account where id=:o.accountid];
        }
        else{
	        a = [select id,Membership_Code__c,Date_Joined__c,renewal_date__c,(select id,name,closedate from opportunities where recordtype.name='Renewal' and stagename='Complete' order by CloseDate desc) from account where id=:l.company];
        }
        
//        Account a = [select id,Membership_Code__c,Date_Joined__c,(select id,name,closedate from opportunities where recordtype.name='Renewal' and stagename='Complete' order by CloseDate desc) from account where id=:l.company];
        Club_Product__c paper = [select id from Club_Product__c where recordtype.name='Membership Code' and Name='Paper' limit 1];
        system.debug(Paper);
        system.debug(a);
        system.debug(a.opportunities); 
        CustomPermissionsReader cpr = new CustomPermissionsReader();
        Boolean hasPermission = cpr.hasPermission('Ignore_8_Week_Rule');
        if(a.Membership_Code__c==paper.id ){
            if(a.opportunities.size()>0){
		        Opportunity o = [select account.id,account.Membership_Code__c,account.Date_Joined__c,id,name,closedate,(select id,name,product__r.name,product__r.Membership_Length__c from Line_Items__r where recordtype.name='Membership Code') from opportunity where accountid = :a.id and recordtype.name='Renewal' and stagename='Complete' order by CloseDate desc limit 1];
//                if(a.opportunities[0].closedate.adddays(56)<system.now() && !hasPermission){
				system.debug(a.renewal_date__c.addmonths(-1*integer.valueof(o.Line_Items__r[0].product__r.Membership_Length__c)).adddays(56));
                if(a.renewal_date__c.addmonths(-1*integer.valueof(o.Line_Items__r[0].product__r.Membership_Length__c)).adddays(56)<system.now().date()&& !hasPermission){
                    l.adderror('Cannot change from Paper to Digital membership after 8 weeks, please use change at renewal',true);      
                }   
            }
            else{
                if(a.Date_Joined__c.adddays(56)<system.now().date() && !hasPermission){
                    l.adderror('Cannot change from Paper to Digital membership after 8 weeks, please use change at renewal',true);      
                }
            } 
            
        }
    }
    public Id autoswitch(Account acc, Contact con, Opportunity opp, Id clubProductFromId, Id clubProductToId) {
        Integer membersAgeOnRenewalDate = con.Birthdate != null ? con.Birthdate.monthsBetween(acc.Renewal_Date__c) / 12 : null;
        if (acc.Membership_Type_Name__c == YOUNG_CAMPER_MEMBERSHIP_TYPE
                && membersAgeOnRenewalDate >= 25) {
            return clubProductToId;
        }
        if (acc.Membership_Type_Name__c == YOUTH_DIGITAL_MEMBERSHIP_TYPE
                && membersAgeOnRenewalDate >= 18 && con.Youth_Test_Passed_Date__c == null) {
            return clubProductToId;
        }
        return clubProductFromId;
    } 
}