force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Memberships.recordType-meta.xml
<RecordType>
    <fullName>Memberships</fullName>
    <active>true</active>
    <label>Memberships</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchAutoRenewMembershipsTest.cls
@IsTest
private class BatchAutoRenewMembershipsTest {
    @IsTest
    static void testBatchAutoRenewMembershipsScheduler() {
        TestDataFactory.createTestRecords();

        String cronTime = '0 0 0 * * ? *';

        Test.startTest();
        String jobId = System.schedule('Create Auto Renew Memberships', cronTime, new BatchAutoRenewMembershipsScheduler());
        Test.stopTest();

        // Get the information from the CronTrigger API object
        List<CronTrigger> cts = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];

        // Verify the job has been scheduled
        System.assertEquals(1, cts.size());
    }

    @IsTest
    static void testYouthDigitalToYoungCamperRenewMembership() {
        TestDataFactory.RenewalDataSetup dataSetup = new TestDataFactory.RenewalDataSetup();
        dataSetup.prodNameFrom = 'Youth - Digital';
        dataSetup.prodNameTo = 'Young Camper';
        dataSetup.paymentMethod = 'Direct Debit';
        dataSetup.memberBirthdate = Date.today().addYears(-18);
        dataSetup.renewalDate = Date.today().addMonths(2);
        dataSetup.youthTestDate = Date.today();
        dataSetup.VIClass1 = 'Youth';
        dataSetup.VIClass2 = 'YoungCamper';
        dataSetup.minAge1 = 12;
        dataSetup.minAge2 = 18;
        dataSetup.maxAge1 = 17;
        dataSetup.maxAge2 = 25;

        Id accId = TestDataFactory.prepareRecordsForMembershipRenewal(dataSetup);

        Id opportunityRenewalRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'Renewal' LIMIT 1].Id;
        Id membershipCodeRecordTypeId2 = [SELECT Id FROM RecordType WHERE SobjectType = 'Club_Opportunity_Product__c' AND DeveloperName = 'Membership_Code' LIMIT 1].Id;
        Id clubProductToId = [SELECT Id FROM Club_Product__c WHERE Name = 'Young Camper' LIMIT 1].Id;

        Opportunity opp = new Opportunity(
                RecordTypeId = opportunityRenewalRecordType,
                Name = 'Renewal',
                StageName = 'Due',
                Amount = 0,
                AccountId = accId,
                CloseDate = Date.today()
        );
        insert opp;

        Club_Opportunity_Product__c clubOpportunityProduct = new Club_Opportunity_Product__c(
                RecordTypeId = membershipCodeRecordTypeId2,
                Status__c = 'Pending',
                Price__c = 0,
                Account__c = accId,
                Product__c = clubProductToId,
                Opportunity__c = opp.Id
        );
        insert clubOpportunityProduct;

        update new Account(Id = accId, Renewal_Date__c = Date.today());

        Test.startTest();
        Database.executeBatch(new BatchAutoRenewMemberships());
        Test.stopTest();

        System.assertEquals('Young Camper', [SELECT Id, Membership_Code__r.Name FROM Account WHERE Id = :accId].Membership_Code__r.Name, 'Membership Type should be changed to Young Camper!');
    }
}