force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Old_MN__c.field-meta.xml
<CustomField>
    <fullName>Old_MN__c</fullName>
    <label>Old Membership Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Date_Ended__c.field-meta.xml
<CustomField>
    <fullName>Date_Ended__c</fullName>
    <label>Date Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <formula>TEXT ( Account.Membership_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateMemberChargeableRestTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class UpdateMemberChargeableRestTest {
  static Account acc;
  static Lead lead;
  static Club_Opportunity_Product__c cop;
  static constants sc;
  static Contact cAssocMember;
  static Opportunity opp;

  static void init() {
    TestDataFactory.createTestRecords();
    sc = new constants();
    acc = [SELECT Id, Membership_Status__c, date_joined__c FROM Account];
    //lead = [Select Id, LastName,Email,sections__c FROM Lead];
    //cop = [Select Id, recordtypeId from Club_Opportunity_Product__c limit 1];
    //cAssocMember = [select title,firstname,lastname,birthdate from Contact where date_ended__c = null and accountid=:acc.id and recordtypeid=:sc.associateContactRecordTypeId limit 1];
  }

  static testMethod void htmlPostTest() {
    // TO DO: implement unit test
    init();
    acc.Old_MN__c = '111111';
    update acc;
    String JSONMsg = '{"message":"success"}';
    RestRequest req = new RestRequest(); // Build the REST Request for testing
    UpdateMemberChargeableRest ctm = new UpdateMemberChargeableRest();
    UpdateMemberChargeableRest.Membership mem = new UpdateMemberChargeableRest.Membership();
    String jsonStr = '{"Membership" : {"MembershipName" : "An error", "MembershipSource" : false}}';
    req.addParameter('memberId', '111111');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = '<a target="_blank" href="https://campingandcaravanningclub--test.my.salesforce.com/services/apexrest/v1.0/MemberUpdate/111111'; //" rel="nofollow">https;//salesforce.com/services/apexrest/v1.0/CaseService';</a>
    req.httpMethod = 'POST'; // Perform a POST
    req.requestBody = Blob.valueof(jsonStr); // Add JSON Message as a POST

    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    UpdateMemberChargeableRest.updateMemberDetails(mem);
  }

  @IsTest
  static void testThisThing() {
    UpdateMemberChargeableRest.testThisThing();
  }
}