force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Access_Member_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Access_Member_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Access Member Allowed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Children_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Children_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Children Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChangeDetailsController.cls
public with sharing class ChangeDetailsController {
    
         public ApexPages.StandardController stdCntrlr {get; set;}
            public ChangeDetailsController(ApexPages.StandardController controller) {
            if (!Test.isRunningTest())
            {
                controller.addFields(new List<String>{'Membership_Code__c'});
            }
            stdCntrlr = controller;
            this.acc = (Account) controller.getRecord();
        }
        
        public Account acc {get;set;}
    
        
       String ids = ApexPages.currentPage().getParameters().get('id');
       public constants sc = new constants();
        
        public club_product__c cp {
            get{
                if(cp==null){
                    cp = [select id,name,access_member_allowed__c,PartnerAllowed__c,children_allowed__c from club_product__c where id=:acc.Membership_Code__c];
                }
                return cp;
            }
            private set;
        }
        
        public PageReference ChangePaymentDetails()
        {
        PageReference pr = new PageReference('/apex/ChangePaymentDetails');
        pr.getParameters().put('id',ApexPages.currentPage().getParameters().get('id'));
        return pr;
        }
    	public PageReference ChangeMem(){
	    	PageReference pr = new PageReference('/apex/MiddleDetailPage');
	        pr.getParameters().put('id',ApexPages.currentPage().getParameters().get('id'));
	        return pr;
    	}
        public PageReference ChangeMembership()
        {
        PageReference pr = new PageReference('/apex/ChangeMembership');
        pr.getParameters().put('id',ApexPages.currentPage().getParameters().get('id'));
        return pr;
        }
        
        public PageReference AddAssocSections(){
        	PageReference pr = new PageReference('/apex/ChangeAssociationSections');
        	pr.getParameters().put('id', ApexPages.currentPage().getParameters().get('id'));
        	return pr;
        }
    
        
        public PageReference ChangeAtRenewal()
        {
        PageReference pr = new PageReference('/apex/ChangeAtRenewal');
        pr.getParameters().put('id',ApexPages.currentPage().getParameters().get('id'));
        return pr;
        }
        
        public PageReference ChangeAddress()
        {
        PageReference pr = new PageReference('/apex/ChangeAddressDetails');
        pr.getParameters().put('id',ApexPages.currentPage().getParameters().get('id'));
        return pr;
        }
        
        public PageReference NewChildMember()
        {
        Pagereference retpage;
        
        retpage = new pagereference('/apex/NewChildMember');
        retpage.getParameters().put('rtid',sc.childContactRecordTypeId);
        //retpage.getParameters().put('ent','Contact');
        retpage.getParameters().put('accid',ApexPages.currentPage().getParameters().get('id'));
        retpage.getParameters().put('accName',ApexPages.currentPage().getParameters().get('name'));
        //retpage.getParameters().put('id',con.Id);
        retpage.getParameters().put('retURL','/'+ApexPages.currentPage().getParameters().get('id'));
        retpage.setRedirect(true);
        return retpage;
        }
        
        public PageReference NewSecondarymember()
        {
        Pagereference retpage;
        
        retpage = new pagereference('/apex/NewSecondaryMember');
        retpage.getParameters().put('rtid',sc.secondaryContactRecordTypeId);
        //retpage.getParameters().put('ent','Contact');
        retpage.getParameters().put('accid',ApexPages.currentPage().getParameters().get('id'));
        //retpage.getParameters().put('id',con.Id);
        retpage.getParameters().put('retURL','/'+ApexPages.currentPage().getParameters().get('id'));
        retpage.setRedirect(true);
        return retpage;
        }
        
        public PageReference NewAccessMember()
        {
        Pagereference retpage;
        
        retpage = new pagereference('/apex/NewAccessMember');
        retpage.getParameters().put('rtid',sc.accessContactRecordTypeId);
        //retpage.getParameters().put('ent','Contact');
        retpage.getParameters().put('accid',ApexPages.currentPage().getParameters().get('id'));
        //retpage.getParameters().put('id',con.Id);
        retpage.getParameters().put('retURL','/'+ApexPages.currentPage().getParameters().get('id'));
        retpage.setRedirect(true);
        return retpage;
        }
    
    
}