force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChangeDetailsControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ChangeDetailsControllerTest {

    private static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        constants c = new constants();
        test.startTest();
        PageReference pageRef = page.ChangeDetails;
        Club_Product__c cp = new Club_Product__c();
        cp.RecordTypeId = c.clubProdMembershipCodeRecordTypeId;
        cp.Name = 'Digital';
        cp.Product_Detail__c = 'Digital Membership';
        cp.Active__c = true;
        cp.Show_in_New_Membership_Picklist__c = true;
        cp.Sections_Allowed__c = true;
        cp.Associate_Allowed__c = true;
        cp.PartnerAllowed__c = true;
        cp.DD_Payment_Allowed__c = true;
        insert cp;
        
         Account acc = new Account();
         acc.Name = 'Test Membership';
         acc.Membership_Code__c = cp.Id;
        insert acc;
        Opportunity opp = new Opportunity ();
        opp.name = 'testOppty';
        opp.AccountId=acc.id;
        Opp.StageName='Open';
  		opp.CloseDate=System.today();        
        insert opp;
                
        
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',acc.id);
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        ChangeDetailsController cont = new ChangeDetailsController(sc);
        
        ChangeDetailsController cont2 = new ChangeDetailsController(sc);
        PageReference pageref2 = cont2.ChangePaymentDetails();
        
        ChangeDetailsController cont3 = new ChangeDetailsController(sc);
        PageReference pageref3 = cont3.ChangeMembership();
        
        ChangeDetailsController cont4 = new ChangeDetailsController(sc);
        PageReference pageref4 = cont4.ChangeAtRenewal();
        
        ChangeDetailsController cont5 = new ChangeDetailsController(sc);
        PageReference pageref5 = cont5.ChangeAddress();
        
        ChangeDetailsController cont6 = new ChangeDetailsController(sc);
        PageReference pageref6 = cont6.NewChildMember();
        
        ChangeDetailsController cont7 = new ChangeDetailsController(sc);
        PageReference pageref7 = cont7.NewSecondarymember();
        
        club_product__c cp2 = cont7.cp;
        PageReference NewAccessMember = cont7.NewAccessMember();
        
        
        
        
        
        test.stopTest();
        
        
        

        
        
        
        
        
        
        
        
        
    }
}