force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure (yrs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tenure2__c.field-meta.xml
<CustomField>
    <fullName>Tenure2__c</fullName>
    <formula>IF (MONTH(TODAY()) &gt; MONTH(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
IF (MONTH(TODAY()) = MONTH(Date_Joined__c), 
IF (DAY(TODAY()) &gt;= DAY(Date_Joined__c), 
(YEAR(TODAY()) - YEAR(Date_Joined__c) + 1), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
), 
YEAR(TODAY()) - YEAR(Date_Joined__c) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Amendment_Renewal__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Date_Monies_to_be_Taken__c.field-meta.xml
<CustomField>
    <fullName>Date_Monies_to_be_Taken__c</fullName>
    <label>Date Monies to be Taken</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Last_Name__c</fullName>
    <label>Lead Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Salutation__c</fullName>
    <label>Lead Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Total_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Fee__c</fullName>
    <label>Total Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Name__c</fullName>
    <formula>Payment_Method__r.Bank_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <formula>Payment_Method__r.Bank_Account_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sort_Code__c</fullName>
    <formula>Payment_Method__r.Sort_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Sort Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>CASESAFEID(Payment_Method__r.Membership__r.Id)</formula>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandler.cls
public with sharing class TransactionTriggerHandler  extends TriggerHandler{

    public TransactionTriggerHandler(){
        preventRecursiveTrigger(false);
    }

    static Long days7Milliseconds = 604800000;  
    List<Correspondence__c> correspondences = new List<Correspondence__c>();

    public override void afterInsert(List<SObject> newObjects, Map<Id,SObject> newMap){
        
        Set<Id> pmids = new Set<Id>();
        Set<Id> accids = new Set<Id>(); 
        constants c = new constants();
        List<Transaction__c> newTrans = (List<Transaction__c>)newObjects;
           
        for (Transaction__c newPaymentMethod: newTrans) {
            pmids.add(newPaymentMethod.Payment_Method__c);
        }
        
        Map<id, Payment_Method__c> pmlist =new Map<id,Payment_Method__c>([select id,Status__c,Membership__c from Payment_Method__c where id in :pmids]);
        
        for(Payment_Method__c p: pmlist.values()){
            accids.add(p.Membership__c);
        }
        
        Map<id, Account> leadMemMap = new Map<id, Account>([select id, Renewal_Date__c, 
        (Select Id, Salutation,FirstName,LastName, Youth_Test_Passed_Date__c, Tenure2__c from Contacts where RecordTypeId = :c.leadContactRecordTypeId )
        FROM Account WHERE Id in :accids ]);
            
        /*for(Transaction__c cn:newTrans){
            if(cn.Transaction_Type__c == '01'){
                Correspondence__c corr = new Correspondence__c();
                corr.Correspondence_Type__c='Auddis Letter';
                corr.Bank_Account_Name__c = cn.Customer_Account_Name__c;
                corr.Bank_Account_Number__c = cn.Customer_Account_Number__c;
                corr.Sort_Code__c = cn.Customer_Sort_Code__c;
                corr.Total_Fee__c = cn.Amount__c;
                corr.Membership__c = pmList.get(cn.Payment_Method__c).Membership__c;
                for(Contact lc: leadMemMap.get((pmList.get(cn.Payment_Method__c)).Membership__c).Contacts){
                        corr.Lead_Member_Salutation__c =  lc.Salutation;
                        corr.Lead_Member_First_Name__c =  lc.FirstName;
                        corr.Lead_Member_Last_Name__c =  lc.LastName;                       
                }
                corr.Correspondence_date__c = system.today();
                corr.Date_Monies_to_be_Taken__c = cn.Transaction_Date__c;
                correspondences.add(corr);
                
            }
        }
        if(correspondences.size()>0)
        insert correspondences;*/

    }

    public override void afterUpdate(List<SObject> oldObjects, List<SObject> newObjects, Map<Id,SObject> oldMap, Map<Id,SObject> newMap){
        Set<Id> pmids = new Set<Id>(); 
        Set<Id> pm2ids = new Set<Id>(); 
        Set<Id> accids = new Set<Id>();
        List<Transaction__c> trans01list = new List<Transaction__c>(); 
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];

        List<Transaction__c> newTrans = (List<Transaction__c>)newObjects;
        Map<Id,Transaction__c> oldTransMap = (Map<Id,Transaction__c>)oldMap;
    
        for(Transaction__c t : newTrans){ 
            if(t.status__c =='Complete' && t.transaction_type__c == '0N' && oldTransMap.get(t.id).status__c=='Pending' && t.Amount__c > 0){
                trans01list.add(new Transaction__c(
                        
//                  Customer_Sort_Code__c = t.Customer_Sort_Code__c,
//                  Customer_Account_Name__c = t.Customer_Account_Name__c,
//                  Customer_Account_Number__c = t.Customer_Account_Number__c,
                    Transaction_Date__c = BusinessHours.add(bh.id, system.now(), days7Milliseconds).date(),
                    recordtypeid=t.RecordTypeId,
                    Amount__c = t.Amount__c,
                    Status__c = 'Pending',
                    Transaction_Type__c = '01',
                    Payment_Method__c = t.Payment_Method__c)
                );
            }
            // System.debug('transaction: ' + t);
            if(t.Transaction_Type__c=='0N' && t.status__c =='Rejected' && oldTransMap.get(t.id).status__c!='Rejected'){
                pmids.add(t.Payment_Method__c);
            }
            if((t.Transaction_Type__c=='01' || t.Transaction_Type__c=='17') && t.status__c =='Rejected' && oldTransMap.get(t.id).status__c!='Rejected'){
                pm2ids.add(t.Payment_Method__c);
            }
        }
        
               
        List<Payment_Method__c> pmlist =[select id,Status__c from Payment_Method__c where id in :pmids AND Status__c != 'Rejected'];
        
        for(Payment_Method__c pm: pmlist){
            pm.Status__c = 'Rejected';
        }
        
        update pmlist; 
        
        
        Map<id,Payment_Method__c> pm2map = new Map<id,Payment_Method__c> ([select id, Membership__c from Payment_Method__c where id in :pm2ids]);
        For(Payment_Method__c pm2: pm2map.values()){
            accids.add(pm2.Membership__c);
        }
       
        
        List<Account> acclist =[select id,Membership_Status__c from Account where id in :accids];
        
        for(Account acc : acclist){
             acc.Membership_Status__c='DD Rejected';
        }
        
        update acclist; 
        
        if(trans01list.size()>0)insert trans01list;
        
        
        pmids = new Set<Id>();  
        accids = new Set<Id>();
        for(Transaction__c t : newTrans){ 
            if(t.status__c =='Complete' && (t.transaction_type__c == '01' || t.transaction_type__c == '17') && oldTransMap.get(t.id).status__c=='Pending'){
                 pmids.add(t.Payment_Method__c);
            }            
        }
        List<Payment_Method__c> pmlist2 =[select id, Membership__c from Payment_Method__c where id in :pmids];
        for(Payment_Method__c pm: pmlist2){
            accids.add(pm.Membership__c);
        }           
        List<Account> acclist2 =[select id,Membership_Status__c from Account where id in :accids];
                
        for(Account acc : acclist2){
             acc.Membership_Status__c='Paid';
        }
        
        update acclist2;
    }

}