force-app/main/default/objects/Account/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <label>Membership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <color>#33CC00</color>
                <label>Paid</label>
            </value>
            <value>
                <fullName>DD Pending</fullName>
                <color>#FF9900</color>
                <label>DD Pending</label>
            </value>
            <value>
                <fullName>DD Rejected</fullName>
                <color>#FF0000</color>
                <label>DD Rejected</label>
            </value>
            <value>
                <fullName>Lapsed</fullName>
                <color>#FF0000</color>
                <label>Lapsed</label>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
                <color>#330099</color>
                <label>Non-Renewer</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#999999</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ex-Member</fullName>
                <color>#3366FF</color>
                <label>Ex-Member</label>
            </value>
            <value>
                <fullName>Refer to Manager</fullName>
                <color>#000000</color>
                <label>Refer to Manager</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <color>#FFFF66</color>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Unpaid</fullName>
                <color>#FF9900</color>
                <label>Unpaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/SectionsAreFree__c.field-meta.xml
<CustomField>
    <fullName>SectionsAreFree__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections are Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Ended__c.field-meta.xml
<CustomField>
    <fullName>Date_Ended__c</fullName>
    <label>Date Ended</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>Membership_Status__c</fullName>
    <formula>TEXT ( Account.Membership_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/hasAssociate__c.field-meta.xml
<CustomField>
    <fullName>hasAssociate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Associate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasPartner__c.field-meta.xml
<CustomField>
    <fullName>hasPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_First_Name__c</fullName>
    <label>Secondary Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Surname__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Surname__c</fullName>
    <label>Secondary Member Surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Member_Title__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Member_Title__c</fullName>
    <label>Secondary Member Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Rev</fullName>
            </value>
            <value>
                <fullName>Sir</fullName>
            </value>
            <value>
                <fullName>Capt</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Sgt</fullName>
            </value>
            <value>
                <fullName>Corp</fullName>
            </value>
            <value>
                <fullName>Dr</fullName>
            </value>
            <value>
                <fullName>Prof</fullName>
            </value>
            <value>
                <fullName>Cllr</fullName>
            </value>
            <value>
                <fullName>Rt Hon</fullName>
            </value>
            <value>
                <fullName>Lady</fullName>
            </value>
            <value>
                <fullName>Lord</fullName>
            </value>
            <value>
                <fullName>Dame</fullName>
            </value>
            <value>
                <fullName>Duke</fullName>
            </value>
            <value>
                <fullName>Duchess</fullName>
            </value>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Countess</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/sections__c.field-meta.xml
<CustomField>
    <fullName>sections__c</fullName>
    <label>Sections</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentSuccessControllerTests.cls
@isTest
private class PaymentSuccessControllerTests {
	
	static PaymentSuccessController psc;
	static Account acc;
	static PageReference page;
	static Lead lead;
	static Club_Opportunity_Product__c cop;
	static constants sc;
	static Contact cAssocMember;
	static Opportunity o;
	
	static void init(){
	    
        TestDataFactory.testDataforPaymentMethod();
		sc = new constants();
    	acc = [Select Id, Membership_Status__c, date_joined__c FROM Account];  
    	lead = [Select Id, LastName,Email,sections__c FROM Lead];
    	cop = [Select Id, recordtypeId, price__c, Status__c from Club_Opportunity_Product__c limit 1];
		cAssocMember = [select title,firstname,lastname,birthdate from Contact where date_ended__c = null and accountid=:acc.id and recordtypeid=:sc.associateContactRecordTypeId limit 1];
		o = [select id,name,closedate,accountid,(select id,price__c,product__c,recordtypeid from Line_Items__r) from Opportunity where recordtypeid= :sc.OppRenewalRecordTypeId and isclosed=false and iswon=false];
		 
	}

    static testMethod void PaymentSuccessControllerTestWithCancelledResult() {
    	init();
		psc = new PaymentSuccessController();  
		psc.ref = lead.Id;
		psc.lea = lead; 
		psc.result = 'CANCELLED';
		psc.ConvertLead();
    }

    static testMethod void PaymentSuccessControllerTestWithNoResultAndNoAccount() {
    	init();
		psc = new PaymentSuccessController();   
		psc.result = 'CANCELLED';
		lead.Company = 'hello';
		update lead;
        acc.Membership_Status__c = 'Ex-Member';
        update acc;
		psc.ref = lead.Id;
		psc.lea = lead;
		psc.ConvertLead();
    }

	static testMethod void PaymentSuccessControllerTestWithNoResultAndNoAccount2() {
		init();
		psc = new PaymentSuccessController();
		psc.result = 'FAILED';
		lead.Company = '1hello';
		update lead;
		acc.Membership_Status__c = 'Cancelled';
		update acc;
		psc.ref = lead.Id;
		psc.lea = lead;
		psc.ConvertLead();
	}

    static testMethod void PaymentSuccessControllerTestWithFailedResult() {
    	init();
		psc = new PaymentSuccessController();   
		psc.ref = lead.Id;
		psc.lea = lead;
		psc.result = 'FAILED';
		psc.ConvertLead();

    }

    static testMethod void PaymentSuccessControllerTestWithNoResult() {
    	init();
		cop.Price__c= 10;
		cop.Status__c = 'Active';
		psc = new PaymentSuccessController();   
		psc.ref = lead.Id;
		psc.lea = lead;   	
		psc.result = '';
        Test.startTest();
		psc.ConvertLead();
        test.stopTest();
		update cop;

    }

    static testMethod void PaymentSuccessControllerTestWithNoMembershipStatus() {
    	init(); 
		psc = new PaymentSuccessController();  
		psc.ref = lead.Id;
		psc.lea = lead;     	  	
    	acc.Membership_Status__c='Paid';
    	acc.Payment_Method2__c = 'Direct Debit';
    	update acc;
		//psc.result = '';
        test.startTest();
		psc.ConvertLead();
        test.stopTest();

    }

    static testMethod void PaymentSuccessControllerTestWithNoLeadPartner() {
    	init();  
		psc = new PaymentSuccessController();   	  	
    	acc.Membership_Status__c='Paid';
    	update acc;  	  	
    	lead.hasPartner__c=false;
    	lead.hasAssociate__c = true;
        Lead.Secondary_Member_First_Name__c = null;
        Lead.Secondary_Member_Surname__c = null;
        Lead.Secondary_Member_Title__c = null;
        update lead;
    	cop.RecordTypeId = sc.amRecordTypeId;
    	update cop;
		psc.ref = lead.Id;
		psc.lea = lead; 
		psc.result = '';
        test.startTest();
		psc.ConvertLead();
        test.stopTest();

    }

    static testMethod void PaymentSuccessControllerTestWithDCCPaymentMethodOnLead() {
    	init();
		cop.Price__c= 10;
		cop.Status__c = 'Active';
		psc = new PaymentSuccessController();      	  	
    	lead.Payment_Method__c='Debit/Credit Card';
    	update lead;
		psc.ref = lead.Id;
		psc.lea = lead; 
		psc.result = '';
        Test.startTest();
		psc.ConvertLead();
        Test.stopTest();
		//update cop;

    }

    static testMethod void PaymentSuccessControllerTestWithCashPaymentMethodOnLeadANDWithoutcAssocMember() {
    	init();
		cop.Price__c=10;
		cop.Status__c = 'Active';
		psc = new PaymentSuccessController();
    	lead.Payment_Method__c='Cash/Cheque';
    	update lead;
    	cAssocMember.date_ended__c = system.today();
    	update cAssocMember;
		psc.ref = lead.Id;
		psc.lea = lead; 
		psc.result = '';
		system.debug('running in error now ');
		Test.startTest();
		psc.ConvertLead();
		Test.stopTest();
		//update cop;

    }

    static testMethod void PaymentSuccessControllerTestWithRenewalOppData() {
    	init();
		cop.Price__c=10;
		cop.Status__c = 'Active';
		psc = new PaymentSuccessController();     
    	TestDataFactory.createRenewalTestRecords(); 
		psc.ref = lead.Id;
		psc.lea = lead;
        Test.startTest();
    	psc.ConvertLead();
        Test.stopTest();
		update cop;

    }

    static testMethod void PaymentSuccessControllerTestWithNoResultAndNoAccWithOpp() {
    	//init();    
    	TestDataFactory.testDataforPaymentMethod();
		sc = new constants();
    	lead = [Select Id, LastName,Email,sections__c FROM Lead];
    	cop = [Select Id, recordtypeId from Club_Opportunity_Product__c limit 1];   
		o = [select id,name,closedate,accountid,(select id,price__c,product__c,recordtypeid from Line_Items__r) from Opportunity where recordtypeid= :sc.OppRenewalRecordTypeId and isclosed=false and iswon=false];
		lead.Company = o.Id;
		update lead;
		psc = new PaymentSuccessController();
		psc.ref = lead.Id;
		psc.lea = lead;
		system.debug('PaymentSuccessControllerTestWithNoResultAndNoAccWithOpp '+acc);
		//psc.ConvertLead();
    }

    static testMethod void PaymentSuccessControllerTestWithNoResultAndNoAccWithOppAndAssoc() {
    	//init();    
    	TestDataFactory.testDataforPaymentMethod();
		sc = new constants();
    	lead = [Select Id, LastName,Email,sections__c,hasPartner__c,hasAssociate__c, Payment_Method__c FROM Lead];
    	cop = [Select Id, recordtypeId from Club_Opportunity_Product__c limit 1];   
		o = [select id,name,closedate,accountid,(select id,price__c,product__c,recordtypeid from Line_Items__r) from Opportunity where recordtypeid= :sc.OppRenewalRecordTypeId and isclosed=false and iswon=false];
		lead.Company = o.Id;
		lead.hasPartner__c = false;
		lead.hasAssociate__c = true;
		lead.Payment_Method__c='Debit/Credit Card';
        Lead.Secondary_Member_First_Name__c = null;
        Lead.Secondary_Member_Surname__c = null;
        Lead.Secondary_Member_Title__c = null;
		update lead;
		psc = new PaymentSuccessController();
		psc.ref = lead.Id;
		psc.lea = lead;
		system.debug('PaymentSuccessControllerTestWithNoResultAndNoAccWithOppAndAssoc '+acc);
        test.startTest();
		psc.ConvertLead();
        test.stopTest();
    }

    static testMethod void PaymentSuccessControllerTestWithNoResultAndNoAccWithOppAndNoAssoc() {
    	//init();    
    	TestDataFactory.testDataforPaymentMethod();
		sc = new constants();
    	lead = [Select Id, LastName,Email,sections__c,hasPartner__c,hasAssociate__c, Payment_Method__c FROM Lead];
    	cop = [Select Id, recordtypeId, Product__c, Price__c, Status__c from Club_Opportunity_Product__c limit 1];
		o = [select id,name,closedate,accountid,(select id,price__c,product__c,recordtypeid from Line_Items__r) from Opportunity where recordtypeid= :sc.OppRenewalRecordTypeId and isclosed=false and iswon=false];
		Club_Product__c cp = [Select id,SectionsAreFree__c, Product_Detail__c, name, (SELECT Id, Price__c, Start_Date__c, End_Date__c FROM Prices__r) from Club_Product__c where Product_Detail__c = 'Association of Lightweight Camper'];
		cAssocMember = [select title,firstname,lastname,birthdate from Contact where date_ended__c = null and recordtypeid=:sc.associateContactRecordTypeId limit 1];
		cAssocMember.Date_Ended__c = system.today();
		update cAssocMember;
		lead.Company = o.Id;
		lead.hasPartner__c = false;
		lead.hasAssociate__c = true;
		lead.Payment_Method__c='Cash/Cheque';
        Lead.Secondary_Member_First_Name__c = null;
        Lead.Secondary_Member_Surname__c = null;
        Lead.Secondary_Member_Title__c = null;
		update lead;
		cop.Price__c = 10;
		cop.Status__c = 'Active';
		update cop;
		psc = new PaymentSuccessController();
		psc.ref = lead.Id;
		psc.lea = lead;
		List<sectionSelectWrapper> sections = new List<sectionSelectWrapper>();
		sectionSelectWrapper s = new sectionSelectWrapper(cp, cp.Prices__r, true);
		sections.add(s);
		psc.sections = sections;
		system.debug('PaymentSuccessControllerTestWithNoResultAndNoAccWithOppAndNoAssoc '+acc);
        Test.startTest();
		psc.ConvertLead();
        Test.stopTest();
    }
}