force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Allowed_Payment_Types__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Payment_Types__c</fullName>
    <label>Allowed Payment Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Cash_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Cash_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cash Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/DD_Payment_Allowed__c.field-meta.xml
<CustomField>
    <fullName>DD_Payment_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Payment Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Max_Age_for_Membership__c.field-meta.xml
<CustomField>
    <fullName>Max_Age_for_Membership__c</fullName>
    <label>Max Age for Membership</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Membership_Length__c.field-meta.xml
<CustomField>
    <fullName>Membership_Length__c</fullName>
    <label>Membership Length (Months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Min_Age_for_Membership__c.field-meta.xml
<CustomField>
    <fullName>Min_Age_for_Membership__c</fullName>
    <label>Min Age for Membership</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Renewable__c.field-meta.xml
<CustomField>
    <fullName>Renewable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Sections_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Sections_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sections Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/VIClass__c.field-meta.xml
<CustomField>
    <fullName>VIClass__c</fullName>
    <description>For Internal system use, do not modify</description>
    <label>VIClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <label>Membership Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership_Code__c/Membership_Code__c.object-meta.xml
<CustomObject>
    <label>Membership Code</label>
    <nameField>
        <label>Membership Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VITest.cls
@IsTest
private class VITest {
    @IsTest
    static void testBehavior() {
        Lead newLead = new Lead(
                FirstName = 'John',
                LastName = 'Smith',
                Company = 'Test Company'
        );
        insert newLead;

        Account acc = new Account(
                Name = 'Test Account'
        );
        insert acc;

        Contact con = new Contact(
                LastName = 'Smith'
        );
        insert con;

        Opportunity opp = new Opportunity(
                Name = 'Test Opp',
                CloseDate = Date.today(),
                StageName = 'Due'
        );
        insert opp;

        Club_Product__c clubProduct1 = new Club_Product__c();
        insert clubProduct1;

        Club_Product__c clubProduct2 = new Club_Product__c();
        insert clubProduct2;

        VIDefault defaultVI = new VIDefault();
        defaultVI.validate(newLead);
        defaultVI.validateAtRenewal(newLead);
        defaultVI.autoswitch(acc, con, opp, clubProduct1.Id, clubProduct2.Id);

        VIYoungCamper youngCamperVI = new VIYoungCamper();
        youngCamperVI.validate(newLead);
        youngCamperVI.validateAtRenewal(newLead);
        youngCamperVI.autoswitch(acc, con, opp, clubProduct1.Id, clubProduct2.Id);
    }

    @IsTest
    static void testVIDigital() {
        Id membershipCodeRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Club_Product__c' AND DeveloperName = 'Membership_Code' LIMIT 1].Id;

        Club_Product__c clubProduct = new Club_Product__c(
                RecordTypeId = membershipCodeRecordTypeId,
                Name = 'Paper',
                Product_Detail__c = 'Paper Membership',
                Active__c = true,
                Show_in_New_Membership_Picklist__c = true,
                Auto_Renew__c = false,
                Min_Age_for_Membership__c = 18,
                Max_Age_for_Membership__c = null,
                Sections_Allowed__c = true,
                Associate_Allowed__c = true,
                PartnerAllowed__c = true,
                DD_Payment_Allowed__c = true,
                Cash_Payment_Allowed__c = true,
                Membership_Length__c = 12,
                Renewable__c = true,
                VIClass__c = 'Paper',
                Allowed_Payment_Types__c = 'Cash/Cheque;Direct Debit;No payment method'
        );
        insert clubProduct;

        Account acc = new Account(
                Name = 'Test Account',
                Membership_Code__c = clubProduct.Id,
                Date_Joined__c = Date.today()
        );
        insert acc;

        //Create related Opportunity
        Opportunity opp = new Opportunity(
                Name = 'New Membership',
                CloseDate = Date.today(),
                StageName = 'Complete',
                AccountId = acc.Id
        );
        insert opp;

        Lead newLead = new Lead(
                FirstName = 'John',
                LastName = 'Smith',
                Company = opp.Id
        );
        insert newLead;

        VIDigital digitalVI = new VIDigital();
        digitalVI.validate(newLead);
        digitalVI.validateAtRenewal(newLead);
    }
}