force-app/main/default/objects/Account/fields/Membership_Code__c.field-meta.xml
<CustomField>
    <fullName>Membership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Club_Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <formula>Account__r.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <formula>IMAGE(
CASE( Name ,
&quot;50 Years&quot;, &quot;/resource/0000000000000/fifty&quot;, /* fifty*/
&quot;Certificated Sites - Digital&quot;, &quot;/resource/0000000000000/other&quot;, /* other*/
&quot;CHH - Digital&quot;, &quot;/resource/0000000000000/chh3&quot;, /* chh*/
&quot;Complimentary&quot;, &quot;/resource/0000000000000/complimentary&quot;, /* complimentary*/
&quot;Honorary&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Honorary (VP)&quot;, &quot;/resource/0000000000000/honorary2&quot;, /* honorary*/
&quot;Digital&quot;, &quot;/resource/0000000000000/digital&quot;, /* online*/
&quot;Overseas - Digital Membership&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Overseas - Paper&quot;, &quot;/resource/0000000000000/overseas&quot;, /* overseas*/
&quot;Paper&quot;, &quot;/resource/0000000000000/paper2&quot;, /* paper*/
&quot;Press Card Holder&quot;, &quot;/resource/0000000000000/press&quot;, /* press*/
&quot;Senior Youth - Digital&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Senior Youth - Paper&quot;, &quot;/resource/0000000000000/senioryouth&quot;, /* senioryouth*/
&quot;Staff&quot;, &quot;/resource/0000000000000/staff&quot;, /* staff*/
&quot;Technical&quot;, &quot;/resource/0000000000000/tech&quot;, /* tech*/
&quot;Temporary Overseas Membership&quot;, &quot;/resource/0000000000000/tempoverseas&quot;, /* tempoverseas*/
&quot;Veteran - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran - Paper&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Veteran Overseas - Digital&quot;, &quot;/resource/0000000000000/veteran2&quot;, /* veteran*/
&quot;Vice President&quot;, &quot;/resource/0000000000000/vp2&quot;, /* vp*/
&quot;Youth - Digital&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Youth - Paper&quot;, &quot;/resource/0000000000000/youth&quot;, /* youth*/
&quot;Site Paper&quot;, &quot;/resource/0000000000000/ccc_site_paper&quot;, /* site*/
&quot;Site Digital&quot;, &quot;/resource/0000000000000/ccc_site_digital&quot;, /* site*/
&quot;/resource/0000000000000/trans_circle&quot;), /* Other */
&quot;Membership Status&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Allow_DDI_Alert__c.field-meta.xml
<CustomField>
    <fullName>Allow_DDI_Alert__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When True, Direct Debit Instruction email alerts will be sent on creation or update to direct debit details. Used to filter out alerts on renewal.</description>
    <inlineHelpText>When True, Direct Debit Instruction email alerts will be sent on creation or update to direct debit details.</inlineHelpText>
    <label>Allow DDI Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchUpdateDDRenewalsTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BatchUpdateDDRenewalsTest {

    static testMethod void UpdateDDRenewalsTest() {
        // TO DO: implement unit test
		TestDataFactory.createAccWithTomorrowRenewalDateTestRecords();
		
		Test.startTest();
		ID batchProcessId = Database.executeBatch(new BatchUpdateDDRenewals(),200);
		Test.stopTest();
		/*
		TestDataFactory.createRenewalOppTestRecords();
		
		
		Test.startTest();
		ID batchProcessId = Database.executeBatch(new BatchUpdateDDRenewals(),200);
		Test.stopTest();*/
    }
    
    @isTest static void batchUpdateDDRenewalsSchedulerTest(){
    	
    	
        TestDataFactory.createAccWithTomorrowRenewalDateTestRecords();

        String cronTime = '0 0 0 * * ? *';
        
        Test.startTest();
            
        // Schedule the test job
        String jobID = System.schedule('Create DD Transactions', cronTime, new BatchUpdateDDRenewalsScheduler());
          
        Test.stopTest();
                
        // Get the information from the CronTrigger API object  
        list<CronTrigger> cts = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        
        // Verify the job has been scheduled
        System.assertEquals(1, cts.size());  
    }

    @IsTest
    static void testYoungCamperToDigitalRenewal() {
        // Young Camper to Digital
        TestDataFactory.RenewalDataSetup dataSetup = new TestDataFactory.RenewalDataSetup();
        dataSetup.prodNameFrom = 'Young Camper';
        dataSetup.prodNameTo = 'Digital';
        dataSetup.paymentMethod = 'Direct Debit';
        dataSetup.memberBirthdate = Date.today().addYears(-25);
        dataSetup.renewalDate = Date.today().addMonths(2);
        dataSetup.youthTestDate = null;
        dataSetup.VIClass1 = 'YoungCamper';
        dataSetup.VIClass2 = 'Digital';
        dataSetup.minAge1 = 18;
        dataSetup.minAge2 = 18;
        dataSetup.maxAge1 = 25;
        dataSetup.maxAge2 = null;

        Id accId = TestDataFactory.prepareRecordsForMembershipRenewal(dataSetup);

        Id opportunityRenewalRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'Renewal' LIMIT 1].Id;
        Id membershipCodeRecordTypeId2 = [SELECT Id FROM RecordType WHERE SobjectType = 'Club_Opportunity_Product__c' AND DeveloperName = 'Membership_Code' LIMIT 1].Id;
        Id clubProductToId = [SELECT Id FROM Club_Product__c WHERE Name = 'Digital' LIMIT 1].Id;

        Opportunity opp = new Opportunity(
                RecordTypeId = opportunityRenewalRecordType,
                Name = 'Renewal',
                StageName = 'Due',
                Amount = 0,
                AccountId = accId,
                CloseDate = Date.today()
        );
        insert opp;

        Club_Opportunity_Product__c clubOpportunityProduct = new Club_Opportunity_Product__c(
                RecordTypeId = membershipCodeRecordTypeId2,
                Status__c = 'Pending',
                Price__c = 0,
                Account__c = accId,
                Product__c = clubProductToId,
                Opportunity__c = opp.Id
        );
        insert clubOpportunityProduct;

        Payment_Method__c paymentMethod = new Payment_Method__c(
                Membership__c = accId,
                Start_Date__c = Date.today(),
                Active__c = true,
                Allow_DDI_Alert__c = true,
                Status__c = 'Active',
                Bank_Account_Name__c = 'John Smith',
                Bank_Account_Number__c = '12345678',
                Bank_Name__c = 'UKBank',
                Sort_Code__c = '121212'
        );
        insert paymentMethod;

        update new Account(Id = accId, Renewal_Date__c = Date.today());

        Test.startTest();
        Database.executeBatch(new BatchUpdateDDRenewals());
        Test.stopTest();

        System.assertEquals('Digital', [SELECT Id, Membership_Code__r.Name FROM Account WHERE Id = :accId].Membership_Code__r.Name, 'Membership Type should be changed to Digital!');
    }
}