force-app/main/default/objects/Account/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <formula>Membership_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Type (Name)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type_Name__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>Account.Membership_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Type (Name)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VIYoungCamper.cls
/**
 * @description Validation class for Membership Type of Young Camper
 */
public with sharing class VIYoungCamper implements ValidationInterface {
    private static final String YOUTH_DIGITAL_MEMBERSHIP_TYPE = 'Youth - Digital';

    public void validate(Lead l) {
    }

    public void validateAtRenewal(Lead l) {
    }

    public Id autoswitch(Account acc, Contact con, Opportunity opp, Id clubProductFromId, Id clubProductToId) {
        Integer membersAgeOnRenewalDate = con.Birthdate != null ? con.Birthdate.monthsBetween(acc.Renewal_Date__c) / 12 : null;
        if (acc.Membership_Type_Name__c == YOUTH_DIGITAL_MEMBERSHIP_TYPE
                && con.Youth_Test_Passed_Date__c <= Date.today()
                && membersAgeOnRenewalDate >= 18
                ) {
            return clubProductToId;
        }
        return clubProductFromId;
    }
}