force-app/main/default/objects/Account/fields/Payment_Method2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method2__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_date__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_date__c</fullName>
    <label>Correspondence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Correspondence_Type__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Type__c</fullName>
    <label>Correspondence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>New Associate Member</fullName>
            </value>
            <value>
                <fullName>Member Get Member</fullName>
            </value>
            <value>
                <fullName>Replacement Renewal</fullName>
            </value>
            <value>
                <fullName>New Second Member</fullName>
            </value>
            <value>
                <fullName>Replacement Card</fullName>
            </value>
            <value>
                <fullName>Monthly Magazine</fullName>
            </value>
            <value>
                <fullName>Auddis Letter</fullName>
            </value>
            <value>
                <fullName>New Access Member</fullName>
            </value>
            <value>
                <fullName>New Member DD</fullName>
            </value>
            <value>
                <fullName>Amend DD</fullName>
            </value>
            <value>
                <fullName>Renew DD</fullName>
            </value>
            <value>
                <fullName>Replacement AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Gift_Code__c.field-meta.xml
<CustomField>
    <fullName>Gift_Code__c</fullName>
    <label>Gift Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Last_Name__c</fullName>
    <label>Lead Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Lead_Member_Salutation__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_Salutation__c</fullName>
    <label>Lead Member Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <label>Gift</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Club Site Voucher</fullName>
            </value>
            <value>
                <fullName>Foldable Camping Chair</fullName>
                <label>RAF - Camping Chair</label>
            </value>
            <value>
                <fullName>Golf Umbrella</fullName>
                <label>RAF - Umbrella</label>
            </value>
            <value>
                <fullName>Insulated Picnic Bag</fullName>
                <label>RAF - Cooler Bag</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Member_First_Name__c</fullName>
    <label>Lead Member First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/Member_Get_Member__c.object-meta.xml
<CustomObject>
    <description>Referral scheme to give existing members a gift when recommended friend joins</description>
    <label>Recommend A Friend</label>
    <nameField>
        <displayFormat>RAF-{00000000}</displayFormat>
        <label>Member Get Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommend A Friend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member_Get_Member__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lead</value>
        </filterItems>
        <filterItems>
            <field>Contact.Membership_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled,Ex-Member,Lapsed,Refer to Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Member_Get_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <description>The picklist field values should only represent the current gifts that are available for selection. However, the field will retain previous gift values that have been updated via data import, or from picklist values that are no longer available for selection.</description>
    <label>Gift</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club Site Voucher</fullName>
            </value>
            <value>
                <fullName>Foldable Camping Chair</fullName>
                <label>RAF - Camping Chair</label>
            </value>
            <value>
                <fullName>Golf Umbrella</fullName>
                <label>RAF - Umbrella</label>
            </value>
            <value>
                <fullName>Insulated Picnic Bag</fullName>
                <label>RAF - Cooler Bags</label>
            </value>
            <value>
                <fullName>1 - Small Fleece</fullName>
                <isActive>false</isActive>
                <label>1 - Small Fleece</label>
            </value>
            <value>
                <fullName>2 - Medium Fleece</fullName>
                <isActive>false</isActive>
                <label>2 - Medium Fleece</label>
            </value>
            <value>
                <fullName>3 - Large Fleece</fullName>
                <isActive>false</isActive>
                <label>3 - Large Fleece</label>
            </value>
            <value>
                <fullName>4 - X Large Fleece</fullName>
                <isActive>false</isActive>
                <label>4 - X Large Fleece</label>
            </value>
            <value>
                <fullName>5 - XX Large Fleece</fullName>
                <isActive>false</isActive>
                <label>5 - XX Large Fleece</label>
            </value>
            <value>
                <fullName>6 - XXX Large Fleece</fullName>
                <isActive>false</isActive>
                <label>6 - XXX Large Fleece</label>
            </value>
            <value>
                <fullName>Adventure Bottle</fullName>
                <isActive>false</isActive>
                <label>Adventure Bottle</label>
            </value>
            <value>
                <fullName>Badge</fullName>
                <isActive>false</isActive>
                <label>Badge</label>
            </value>
            <value>
                <fullName>CCC1-13324-Camper Hamper (Caravan)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Caravan)</label>
            </value>
            <value>
                <fullName>CCC1-13325-Camper Hamper (Motorhome)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Motorhome)</label>
            </value>
            <value>
                <fullName>CCC1-13326-Camper Hamper (Tent)</fullName>
                <isActive>false</isActive>
                <label>Camper Hamper (Tent)</label>
            </value>
            <value>
                <fullName>Camping in the Forest Voucher</fullName>
                <isActive>false</isActive>
                <label>Camping in the Forest Voucher</label>
            </value>
            <value>
                <fullName>Club Care Key Protection Policy</fullName>
                <isActive>false</isActive>
                <label>Club Care Key Protection Policy</label>
            </value>
            <value>
                <fullName>Coin</fullName>
                <isActive>false</isActive>
                <label>Coin</label>
            </value>
            <value>
                <fullName>European Drivers&apos; Handbook</fullName>
                <isActive>false</isActive>
                <label>European Drivers&apos; Handbook</label>
            </value>
            <value>
                <fullName>F - CITF</fullName>
                <isActive>false</isActive>
                <label>F - CITF</label>
            </value>
            <value>
                <fullName>F - CITF Voucher</fullName>
                <isActive>false</isActive>
                <label>F - CITF Voucher</label>
            </value>
            <value>
                <fullName>Five Pound Club Site Voucher</fullName>
                <isActive>false</isActive>
                <label>Five Pound Club Site Voucher</label>
            </value>
            <value>
                <fullName>Games Cards Club Sites</fullName>
                <isActive>false</isActive>
                <label>Games Cards Club Sites</label>
            </value>
            <value>
                <fullName>Gelert Camping Essentials Bottle</fullName>
                <isActive>false</isActive>
                <label>Gelert Camping Essentials Bottle</label>
            </value>
            <value>
                <fullName>Indy</fullName>
                <isActive>false</isActive>
                <label>Indy</label>
            </value>
            <value>
                <fullName>Lantern</fullName>
                <isActive>false</isActive>
                <label>Lantern</label>
            </value>
            <value>
                <fullName>Large Fleece</fullName>
                <isActive>false</isActive>
                <label>Large Fleece</label>
            </value>
            <value>
                <fullName>Medium Fleece</fullName>
                <isActive>false</isActive>
                <label>Medium Fleece</label>
            </value>
            <value>
                <fullName>Phillips Club Atlas</fullName>
                <isActive>false</isActive>
                <label>Phillips Club Atlas</label>
            </value>
            <value>
                <fullName>Pitch Up, Eat Local Book</fullName>
                <isActive>false</isActive>
                <label>Pitch Up, Eat Local Book</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member_Get_Member__c/fields/Introduced_Membership__c.field-meta.xml
<CustomField>
    <fullName>Introduced_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Introduced Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Member_Get_Member_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Debit/Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cash/Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>No payment method</fullName>
    </customValue>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MemberGetMemberTriggerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class MemberGetMemberTriggerTest {

        static testMethod void myUnitTest() {
        
       
       system.debug('inside the myUnitTest');
       
        Account acc = new Account();
       // Contact con = new Contact();
        contact con2 = new Contact();
        //Contact con3 = new Contact();
        Constants c = new constants();
        Lead lea = new Lead();
        Correspondence__c corr = new Correspondence__c();
        Member_Get_Member__c mgm = new Member_Get_Member__c();
        
        
       lea.FirstName = 'Test First';
       lea.LastName = 'Test Last';
       lea.Company = 'Test Co';
       system.debug('inserting lead');
       insert lea;  
       system.debug('inserted lead ' + lea.Id);  
            
        acc.Name = 'Paul';
        acc.Renewal_Date__c = date.parse('19/01/2017');
        acc.Payment_Method2__c = 'Direct Debit';
       system.debug('inserting Account');
        insert acc;
       system.debug('inserted Account ' + acc.Id);
            
            
  
        
        con2.AccountId = acc.Id;
        con2.RecordTypeId = c.leadContactRecordTypeId;
        con2.Salutation = 'Mr';
        con2.FirstName = 'Test';
        con2.LastName = 'Testing';
        insert con2;

        mgm.existing_member__c = con2.id;        
        mgm.Gift__c = 'Medium Fleece';
        mgm.Introduced_Membership__c = acc.id;
        insert mgm;
        
       corr.id = mgm.name;
       corr.Membership__c = acc.id;
       corr.gift_code__c = mgm.Gift__c;
       corr.Correspondence_Type__c = 'Member Get Member';
       corr.Correspondence_date__c =  system.today(); 
       corr.Lead_Member_Salutation__c =  con2.Salutation;
       corr.Lead_Member_First_Name__c =  con2.FirstName;
       corr.Lead_Member_Last_Name__c =  con2.LastName;
       insert corr;
        
        
            
        
        
    }
}