force-app/main/default/objects/Account/fields/Promotional_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotional Code</label>
    <referenceTo>Promotional_Code__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Associate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Associate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Children_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Children_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Children Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Membership_Length__c.field-meta.xml
<CustomField>
    <fullName>Membership_Length__c</fullName>
    <label>Membership Length (Months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/PartnerAllowed__c.field-meta.xml
<CustomField>
    <fullName>PartnerAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Price_for_Initial_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Price_for_Initial_Picklist__c</fullName>
    <description>This is a display price only for the first page of membership flow</description>
    <label>Product Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/fields/Show_in_New_Membership_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_in_New_Membership_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Membership Codes that should appear in the picklist in New Membership process</description>
    <label>Show in New Membership Picklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_Product__c/recordTypes/Membership_Code.recordType-meta.xml
<RecordType>
    <fullName>Membership_Code</fullName>
    <active>true</active>
    <label>Membership Code</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(  ISBLANK(Date_Ended__c) = TRUE, &quot;Active&quot;, &quot;Inactive&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <description>Add a new Child to the Membership</description>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Secondary.recordType-meta.xml
<RecordType>
    <fullName>Secondary</fullName>
    <active>true</active>
    <description>Add a new Secondary Member to the Membership</description>
    <label>Secondary</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Associate_Member_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Associate_Member_Date_of_Birth__c</fullName>
    <label>Associate Member Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/hasAssociate__c.field-meta.xml
<CustomField>
    <fullName>hasAssociate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Associate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promotional_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotional Code</label>
    <referenceTo>Promotional_Code__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(Can_Renew__c = TRUE, 
   CASE( Member_Status__c,
         &apos;1&apos;, &apos;00510&apos;,
         &apos;2&apos;, &apos;00520&apos;,
         &apos;4&apos;, &apos;00530&apos;,
         IF( Account.Membership_Code__r.Name = &apos;Online&apos;, &apos;00050&apos;,&apos;00000&apos;)),
   &apos;00540&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Mandate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Amount__c</fullName>
    <label>Mandate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>Sort_Code__c</fullName>
    <label>Sort Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/Joining_Fee__c.field-meta.xml
<CustomField>
    <fullName>Joining_Fee__c</fullName>
    <label>Joining Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotional_Code__c/Promotional_Code__c.object-meta.xml
<CustomObject>
    <label>Promotional Code</label>
    <nameField>
        <label>Promotional Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotional_Code__c/fields/Number_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Number_Allowed__c</fullName>
    <label>Number Allowed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotional_Code__c/fields/Valid_for_Memberships__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Memberships__c</fullName>
    <label>Valid for (Memberships)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHH - Digital</fullName>
            </value>
            <value>
                <fullName>Complimentary</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Honorary</fullName>
            </value>
            <value>
                <fullName>Overseas - Digital</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Press Card Holder</fullName>
            </value>
            <value>
                <fullName>Senior Youth - Digital</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Temporary Overseas Membership</fullName>
            </value>
            <value>
                <fullName>Veteran - Digital</fullName>
            </value>
            <value>
                <fullName>Veteran Paper</fullName>
            </value>
            <value>
                <fullName>Vice President</fullName>
            </value>
            <value>
                <fullName>Youth - Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotional_Code__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestDataDefaults.cls
/**
 * @description       :
 * @author            : Kev Cadger (Wipro)
 * @group             :
 * @last modified on  : 18-08-2022
 * @last modified by  : Kev Cadger (Wipro)
 * Modifications Log
 * Ver       Date           Author                          Modification
 * 01.00.00  00-00-0000     Kev Cadger (Wipro)              Initial Version
 **/

@IsTest
public class TestDataDefaults {
  // ! -------------------------------------------------- ! //
  // * Interface * //
  /**
   * Interface used to ensure all classes have the same base structure.
   */

  public interface SObjectDefaults {
    Map<Schema.SObjectField, Object> getDefaultValues();
  }

  // ! -------------------------------------------------- ! //
  // * Standard Objects * //
  /**
   * Default values for standard objects.
   */

  public class AccountDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Account.Name => 'TestAccount'
      };
    }
  }

  public class CaseDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Case.Description => 'This is a test case.'
      };
    }
  }

  public class ContactDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Contact.FirstName => 'Testy',
        Contact.Email => 'testy.mctest@testunit.com'
      };
    }
  }

  public class ContentVersionDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, object>{
        ContentVersion.PathOnClient => 'Test',
        ContentVersion.Title => 'Test Content Version',
        ContentVersion.VersionData => Blob.valueOf('Test Content Version')
      };
    }
  }

  public class LeadDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Lead.Company => 'TestAccount',
        Lead.LastName => 'TestLastName'
      };
    }
  }

  public class OpportunityDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Opportunity.CloseDate => Date.today().addDays(60),
        Opportunity.Name => 'TestOpportunity',
        Opportunity.StageName => ''
      };
    }
  }

  public class OrderDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Order.EffectiveDate => Date.today(),
        Order.Name => 'TestOrder',
        Order.Pricebook2Id => Test.getStandardPricebookId(),
        Order.Status => 'Draft'
      };
    }
  }

  public class OrderItemDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        OrderItem.Quantity => 1,
        OrderItem.UnitPrice => 0.0
      };
    }
  }

  public class UserDefaults implements SObjectDefaults {
    public Map<Schema.SobjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        User.Alias => 'TestUser',
        User.Email => 'testy.mctest@testunit.com',
        User.EmailEncodingKey => 'UTF-8',
        User.FirstName => 'Testy',
        User.LastName => 'McTest',
        User.LanguageLocaleKey => 'en_US',
        User.LocaleSidKey => 'en_US',
        User.TimeZoneSidKey => 'America/LoUser.s_Angeles',
        User.Username => 'testy.mctest' +
        DateTime.now() +
        '@testunit.com'
      };
    }
  }

  // ! -------------------------------------------------- ! //
  // * Custom Objects * //
  /**
   * Default values for custom objects.
   */

  public class ClubProductDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Club_Product__c.Active__c => true,
        Club_Product__c.Associate_Allowed__c => true,
        Club_Product__c.Children_Allowed__c => true,
        Club_Product__c.Membership_Length__c => 12,
        Club_Product__c.Name => 'TestClubProduct',
        Club_Product__c.PartnerAllowed__c => true,
        Club_Product__c.Price_for_Initial_Picklist__c => 50,
        Club_Product__c.RecordTypeId => Utilities.getRecordTypeId(
          Club_Product__c.getSObjectType().getDescribe().getName(),
          'Membership_Code'
        ),
        Club_Product__c.Show_in_New_Membership_Picklist__c => true
      };
    }
  }

  public class DealerAdvertDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Dealer_Advert__c.Active__c => true,
        Dealer_Advert__c.Name => 'TestShow'
      };
    }
  }

  public class PaymentMethodDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Payment_Method__c.Bank_Account_Name__c => 'Mr Testy McTest',
        Payment_Method__c.Bank_Account_Number__c => '00010001',
        Payment_Method__c.Bank_Name__c => 'Test Bank',
        Payment_Method__c.Mandate_Amount__c => 10,
        Payment_Method__c.Sort_Code__c => '001001',
        Payment_Method__c.Start_Date__c => Date.today().addDays(-7),
        Payment_Method__c.Status__c => 'Active'
      };
    }
  }

  public class PriceDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Price__c.Joining_Fee__c => 0,
        Price__c.Price__c => 10,
        Price__c.Start_Date__c => Date.today().addDays(-30).toStartOfMonth()
      };
    }
  }

  public class PromotionalCodeDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Promotional_Code__c.Description__c => 'Instant Membership Pack',
        Promotional_Code__c.Name => 'TestPromoCode',
        Promotional_Code__c.Number_Allowed__c => 1,
        Promotional_Code__c.Valid_for_Memberships__c => 'Paper',
        Promotional_Code__c.Valid_From__c => Date.today().addDays(-1)
      };
    }
  }

  public class TransactionDefaults implements SObjectDefaults {
    public Map<Schema.SObjectField, Object> getDefaultValues() {
      return new Map<Schema.SObjectField, Object>{
        Transaction__c.Amount__c => 10,
        Transaction__c.Status__c => 'Pending',
        Transaction__c.Transaction_Date__c => Date.today()
      };
    }
  }

  // ! -------------------------------------------------- ! //
  // * Helper Methods - Standard Objects * //
  /**
   * Extension methods for standard objects
   */

  public class LeadDataExtension {
    public void setAssociateMemberDetails(Lead lead) {
      lead.hasAssociate__c = true;
      lead.Associate_Member_Date_of_Birth__c = Date.today().addYears(45);
      lead.Associate_Member_First_Name__c = 'Associate';
      lead.Associate_Member_Surname__c = 'Member';
      lead.Associate_Member_Title__c = 'Sir';
    }

    public void setPartnerMemberDetails(Lead lead) {
      lead.hasPartner__c = true;
      lead.Secondary_Member_Date_of_Birth__c = Date.today().addYears(45);
      lead.Secondary_Member_Email__c = 'secondmember@testcompany.com';
      lead.Secondary_Member_First_Name__c = 'Secondary';
      lead.Secondary_Member_Surname__c = 'Member';
      lead.Secondary_Member_Online_Account__c = false;
      lead.Secondary_Member_Title__c = 'Sir';
    }

    public void setChildMemberDetails(lead lead, Integer numChildren) {
      if (numChildren > 6) {
        numChildren = 6;
      }
      lead.Number_of_Children__c = String.valueOf(numChildren);

      for (Integer i = 1; i < numChildren + 1; i++) {
        lead.put(
          'Child_' +
          i +
          '_Date_of_Birth__c',
          Date.today().addYears(-10)
        );
        lead.put('Child_' + i + '_First_Name__c', 'Child' + i);
        lead.put('Child_' + i + '_Surname__c', 'Member');
        lead.put('Child_' + i + '_Title__c', 'Miss');
      }
    }
  }
}