force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Post_nominal_Letters__c.field-meta.xml
<CustomField>
    <fullName>Post_nominal_Letters__c</fullName>
    <inlineHelpText>Awards or Honours, for example OBE or MBE</inlineHelpText>
    <label>Post-nominal Letters</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <formula>Membership__r.Date_Joined__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Correspondence</relationshipLabel>
    <relationshipName>Correspondence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DD_Mandates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchDeleteMemberships.cls
global class BatchDeleteMemberships implements Database.Batchable<sObject> {
	
	//global String QUERY =  'select id,name  from Account where Renewal_Date__c < :twoYearsOld ';
    
	global Database.QueryLocator start(Database.BatchableContext BC) {

		
		Date twoYearsOld = Date.today().addDays(- 730);
		String QUERY = 'select id,name  from Account where Renewal_Date__c < :twoYearsOld' ;
		system.debug(QUERY + ' LIMIT 200');
		
		if(Test.isRunningTest()) {
			return Database.getQueryLocator(QUERY + ' LIMIT 200');
		}
		
		system.debug('QUERY twoYearsOld '+QUERY + ' ' + twoYearsOld);
		return Database.getQueryLocator(QUERY);
	}

    global void execute(Database.BatchableContext BC, List<Account> scope) {
		constants sc = new constants();

		Set<Id> accids = new Set<id>();

        for(Account o : scope) {
        	accids.add(o.Id);
        }
        
       List<Contact> memlist = new List<Contact>([select id,account.Renewal_Date__c, RecordTypeId, Salutation,FirstName,LastName, Post_nominal_Letters__c, Date_Joined__c from Contact where accountId in :accids and (RecordTypeId = :sc.leadContactRecordTypeId OR RecordTypeId = :sc.secondaryContactRecordTypeId)]);
       List<Opportunity> opplist = new List<Opportunity>([select id,account.Renewal_Date__c, RecordTypeId, StageName from Opportunity  where accountId in :accids]);
       List<Payment_Method__c> paymentlist = new List<Payment_Method__c>([select id,Membership__r.Renewal_Date__c, RecordTypeId from Payment_Method__c  where Membership__c in :accids]);
       List<Correspondence__c> correslist = new List<Correspondence__c>([select id,Membership__r.Renewal_Date__c from Correspondence__c  where Membership__c in :accids]);
        
       
		
		system.debug(opplist);
		system.debug(paymentlist);
		system.debug(correslist);
		system.debug(memlist);
		system.debug(accids);
		
		delete memlist;
		delete opplist;
		delete correslist;
		delete paymentlist;
		delete scope;
    }

    global void finish(Database.BatchableContext BC) {}
    

}

/* // Initialize setup variables
			String objectName = 'Contact';  // modify as needed
			String query = 'SELECT';
			Map<String, Schema.SObjectField> cobjectFields = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap();
			
			// Grab the fields from the describe method and append them to the queryString one by one.
			for(String s : cobjectFields.keySet()) {
			   query += ' ' + s + ', ';
			}
			
			// Manually add related object's fields that are needed.
			query += 'Account.Name,'; // modify as needed
			
			// Strip off the last comma if it exists.
			if (query.subString(query.Length()-1,query.Length()) == ','){
			    query = query.subString(0,query.Length()-1);
			}
			
			// Add FROM statement
			query += ' FROM ' + objectName;
			
			// Add on a WHERE/ORDER/LIMIT statement as needed
			query += '  accountId in :accids and (RecordTypeId = :sc.leadContactRecordTypeId OR RecordTypeId = :sc.secondaryContactRecordTypeId)'; // modify as needed
			  
			try {
			        memlist = new Map<id,Contact>(query);
			} catch (QueryException e){
			        //perform exception handling
			}
        
        
        
		system.debug(memlist);
		
		Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Contact').getDescribe().fields.getMap();
		system.debug(objectFields);
		for(Contact c:memlist.values())
		{
			
	    	for(String s : objectFields.keySet()) {
	    		if(s != 'salutation')
	    			if( s!= 'firstName')
	    				if( s !='lastName')
	    					if( s !='post_nominal_letters__c')
	    						if( s != 'date_joined__c') {
					    			//TODO set the field to null
					    			system.debug('In if '+ s + ' ' + c.get(s));
					    			//c.set(s) = null;
	    		}
	    	}
		}
		*/