force-app/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>This formula is need to get information to be sent to a third party tool using outbound message</description>
    <formula>TEXT(Account.Renewal_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Youth_Test_Passed_Date__c.field-meta.xml
<CustomField>
    <fullName>Youth_Test_Passed_Date__c</fullName>
    <label>Youth Test Passed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Pulled through from Membership record for reporting purposes only</description>
    <formula>Account.Renewal_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VISeniorYouth.cls
Public class VISeniorYouth implements ValidationInterface {
    public void validate(lead l) {
        Constants sc = new Constants();
        System.debug ('-------Inside senior Youth validate-------');
        system.debug(l.company);
        if(l.company!=null){
        	Contact c;
        	if(l.company.startswith('001')){
            	c = [select id,name,birthdate,Youth_Test_Passed_Date__c from contact where recordtypeid=:sc.leadContactRecordTypeId and accountid=:l.company];
        	}
        	else if (l.company.startswith('006')){
        		Opportunity  o = [select id,closedate,accountid from opportunity where id=:l.company];
            	c = [select id,name,birthdate,Youth_Test_Passed_Date__c from contact where recordtypeid=:sc.leadContactRecordTypeId and accountid=:o.accountid];
								
        	}
            system.debug(c);
            if(c.Youth_Test_Passed_Date__c==null)l.adderror('Youth test not passed');
            if(c.birthdate.addyears(30)<=date.today())l.adderror('Member is over 29 years old');
            if(c.birthdate.addyears(21)>date.today())l.adderror('Member is under 21 years old');
        }
    }
    public void validateAtRenewal(lead l){
    	validate(l); 
    }
	public id autoswitch(Account a,Contact c,Opportunity o,ID clubProduct,ID clubProductto){
		if(c.birthdate.addyears(21)< a.Renewal_Date__c && c.Youth_Test_Passed_Date__c!=null){
			return clubProductto;
		}
		return clubProduct;
	} 
}