force-app/main/default/objects/Association__c/Association__c.object-meta.xml
<CustomObject>
    <label>Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Association__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Offices associated with the Regions</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/recordTypes/Section.recordType-meta.xml
<RecordType>
    <fullName>Section</fullName>
    <active>true</active>
    <label>Section</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Access.recordType-meta.xml
<RecordType>
    <fullName>Access</fullName>
    <active>true</active>
    <description>Access Members should only be added by a Membership Administrator</description>
    <label>Access</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Associate.recordType-meta.xml
<RecordType>
    <fullName>Associate</fullName>
    <active>true</active>
    <description>Associate Members should be added using the [Change Membership] button</description>
    <label>Associate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <description>Add a new Child to the Membership</description>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <description>New Lead Members cannot be added to the Membership</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Secondary.recordType-meta.xml
<RecordType>
    <fullName>Secondary</fullName>
    <active>true</active>
    <description>Add a new Secondary Member to the Membership</description>
    <label>Secondary</label>
</RecordType>

force-app/main/default/objects/Dealer_Advert__c/Dealer_Advert__c.object-meta.xml
<CustomObject>
    <label>Dealer / Advert</label>
    <nameField>
        <label>Dealer / Advert</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers / Adverts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Advert__c/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Debit/Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash/Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Reinstatement.recordType-meta.xml
<RecordType>
    <fullName>Reinstatement</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Reinstatement</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>membership</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>DDI Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/constants.cls
public class constants {
    
    public String leadContactRecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Lead').RecordTypeId;
    public String childContactRecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Child').RecordTypeId;
    public String associateContactRecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Associate').RecordTypeId;
    public String secondaryContactRecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Secondary').RecordTypeId;
    public String accessContactRecordTypeId = Schema.SObjectType.Contact.RecordTypeInfosByName.get('Access').RecordTypeId;
    public String CcardRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Debit/Credit Card').RecordTypeId;
    public String ddebitRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Direct Debit').RecordTypeId;
    public String cashRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Cash/Cheque').RecordTypeId;
    public String trCcardRecordTypeId = Schema.SObjectType.Transaction__c.RecordTypeInfosByName.get('Debit/Credit Card').RecordTypeId;
    public String trddebitRecordTypeId = Schema.SObjectType.Transaction__c.RecordTypeInfosByName.get('Direct Debit').RecordTypeId;
    public String trcashRecordTypeId = Schema.SObjectType.Transaction__c.RecordTypeInfosByName.get('Cash/Cheque').RecordTypeId;
    public String cpsectRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Section').RecordTypeId;
    public String mtsectRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Membership Code').RecordTypeId;
    public String amsectRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Associate Membership').RecordTypeId;

    public final String OppRenewalRecordTypeId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Renewal').RecordTypeId;
    public final String OppChangeRecordTypeId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Change').RecordTypeId;
    public final String OppReinRecordTypeId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('Reinstatement').RecordTypeId;
    public final String OppNewMembershipRecordTypeId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('New Membership').RecordTypeId;
    public final String amRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Associate Membership').RecordTypeId;
    public final String sectionRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Section').RecordTypeId;
    public final String mtRecordTypeId = Schema.SObjectType.Club_Opportunity_Product__c.RecordTypeInfosByName.get('Membership Code').RecordTypeId;
    public final String PaymentMethodDDRecordTypeId = Schema.SObjectType.Payment_Method__c.RecordTypeInfosByName.get('Direct Debit').RecordTypeId;
    public final String clubProdAssociateRecordTypeId = Schema.SObjectType.Club_Product__c.RecordTypeInfosByName.get('Associate Membership').RecordTypeId;
    public final String clubProdMembershipCodeRecordTypeId = Schema.SObjectType.Club_Product__c.RecordTypeInfosByName.get('Membership Code').RecordTypeId;
    public final String clubProdSectionRecordTypeId = Schema.SObjectType.Club_Product__c.RecordTypeInfosByName.get('Section').RecordTypeId;
    
     
    
    
    public final String dealerAdvertDealerRecordTypeId = Schema.SObjectType.Dealer_Advert__c.RecordTypeInfosByName.get('Dealer').RecordTypeId;
    
    public String complete = 'Complete';
    public String superseded = 'Superseded';
    public String active = 'Active'; 
    
    
    
    public String accDaRecordTypeId = Schema.SObjectType.Association__c.RecordTypeInfosByName.get('District Association').RecordTypeId;
    public String accRegionRecordTypeId = Schema.SObjectType.Association__c.RecordTypeInfosByName.get('Region').RecordTypeId;

    public static final String YOUNG_CAMPER_MEMBERSHIP_TYPE = 'Young Camper';

}