force-app/main/default/objects/Lead/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Verifone__c/Verifone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Verifone</label>
</CustomObject>

force-app/main/default/objects/Verifone__c/fields/Accountid__c.field-meta.xml
<CustomField>
    <fullName>Accountid__c</fullName>
    <label>Accountid</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verifone__c/fields/Merchantid__c.field-meta.xml
<CustomField>
    <fullName>Merchantid__c</fullName>
    <label>Merchantid</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verifone__c/fields/Return_URL__c.field-meta.xml
<CustomField>
    <fullName>Return_URL__c</fullName>
    <label>Return URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Verifone__c/fields/Systemguid__c.field-meta.xml
<CustomField>
    <fullName>Systemguid__c</fullName>
    <label>System Guid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VerifoneCalloutUtilityTest.cls
/*
* @who   Alasdair Leggat <alasdair.leggat@weare4c.com>
* @what  Test class for VerifoneCalloutUtility
* @when  2019-11-04
*/

@isTest
public class VerifoneCalloutUtilityTest {

    @testSetup
    static void setup(){
        // test custom setting
        Verifone__c  verifoneCustomSetting = new Verifone__c(
            Accountid__c = '00000000',
            Endpoint__c = 'TEST_ENDPOINT',
            Merchantid__c = '00000000',
            Systemguid__c = '00000000',
            Return_URL__c = 'https://google.co.uk'
        );
        insert verifoneCustomSetting;
        
        // test lead
        Lead ld = new Lead(
            FirstName = 'FIRST_NAME',
            LastName = 'LAST_NAME',
            Email = 'test@email.com',
            Street = 'STREET',
            City = 'CITY',
            State = 'STATE',
            PostalCode = 'PO1 CO2',
            Country = 'COUNTRY',
            Amount__c = 1.0,
            Company = 'COMPANY'
        );
        insert ld;
    }
    
    @isTest
    static void testFormDataCreation(){
        // get lead
        Lead ld = [SELECT FirstName, LastName, Email, Street, City, State, PostalCode, Country, Amount__c
                   FROM Lead
                   WHERE FirstName = 'FIRST_NAME'
                   LIMIT 1].get(0);
        
        // instantiate utility class
        VerifoneCalloutUtility calloutUtil = new VerifoneCalloutUtility(ld);
        
        // assert lead fields inserted into form data
        System.assertEquals(true, calloutUtil.formData.contains('FIRST_NAME'));
        System.assertEquals(true, calloutUtil.formData.contains('LAST_NAME'));
        
    }
}