force-app/main/default/objects/Correspondence__c/Correspondence__c.object-meta.xml
<CustomObject>
    <label>Correspondence</label>
    <nameField>
        <displayFormat>COR-{000000}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correspondence__c/fields/Date_Processed__c.field-meta.xml
<CustomField>
    <fullName>Date_Processed__c</fullName>
    <description>This is the date and time the entry was processed by Salesforce and added to the CSV export file</description>
    <label>Date Processed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Re_issue__c.field-meta.xml
<CustomField>
    <fullName>Re_issue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Correspondence__c/fields/Re_issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Re_issue_Date__c</fullName>
    <label>Re-issue Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CloneCorrespondenceController.cls
public with sharing class CloneCorrespondenceController {

    private final Correspondence__c corr;
    ApexPages.StandardController sController;  

    public CloneCorrespondenceController(ApexPages.StandardController stdController) {
        sController = stdController;  

		List<String> corrfields = new list<String>();

		Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Correspondence__c').getDescribe().fields.getMap();
		for(String s : objectFields.keySet()) {
			corrfields.add(s);
		}
		if(!test.isRunningTest()) 
			stdController.addFields(corrfields);

        this.corr = (Correspondence__c)stdController.getRecord();
    }

	public PageReference cloneCorr(){
		Correspondence__c cloned_corr = corr.clone(false,true,false,false);
		cloned_corr.Re_issue__c = true;
		cloned_corr.Re_issue_Date__c = system.now();
		cloned_corr.Date_Processed__c = null;
		insert cloned_corr;
		return new PageReference('/'+cloned_corr.id); 
	}
}