force-app/main/default/objects/Club_Opportunity_Product__c/Club_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Club Opportunity Product</label>
    <nameField>
        <displayFormat>LI-{00000000}</displayFormat>
        <label>Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Club Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Club_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Club_Product__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Club_Product__c</referenceTo>
    <relationshipLabel>Club Opportunity Products</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_Opportunity_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Non-Renewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_Product__c/Club_Product__c.object-meta.xml
<CustomObject>
    <label>Club Product</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_Product__c/fields/Product_Detail__c.field-meta.xml
<CustomField>
    <fullName>Product_Detail__c</fullName>
    <description>This field value appears in the New Membership picklist</description>
    <label>Product Detail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReinstatePaymentControllerTest.cls
@IsTest
private class ReinstatePaymentControllerTest {

    @IsTest
    static void getMembershipInfoNoSelectedSectionsTest(){
        TestDataFactory.createTestRecords();

        Account account = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];

        Test.startTest();
        ReinstatePaymentController.MembershipInfo membershipInfo = ReinstatePaymentController.getMembershipInfo(account.Id);
        Test.stopTest();

        System.assertEquals(0, membershipInfo.associateMemberCost);
        System.assertEquals(144, membershipInfo.membershipCost);
        System.assertEquals(144, membershipInfo.totalCost);
        System.assert(membershipInfo.selectedSections.isEmpty());
    }


    @IsTest
    static void getMembershipInfoSelectedSectionsTest(){
        TestDataFactory.createTestRecords();

        constants sc = new constants();

        Account account = [SELECT Id FROM Account ORDER BY CreatedDate DESC LIMIT 1];

        List<Club_Opportunity_Product__c> opportunityProducts = [SELECT Account__c, Status__c, RecordType.DeveloperName, Product__r.Product_Detail__c, Product__r.Name FROM Club_Opportunity_Product__c LIMIT 1];

        for(Club_Opportunity_Product__c opportunityProduct : opportunityProducts) {
            opportunityProduct.Status__c = 'Cancelled';
            opportunityProduct.RecordTypeId = sc.sectionRecordTypeId;
        }

        update opportunityProducts;

        Test.startTest();
        ReinstatePaymentController.MembershipInfo membershipInfo = ReinstatePaymentController.getMembershipInfo(account.Id);
        Test.stopTest();

        System.assertEquals(0, membershipInfo.associateMemberCost);
        System.assertEquals(144, membershipInfo.membershipCost);
        System.assertEquals(288, membershipInfo.totalCost);
        System.assertEquals(1, membershipInfo.selectedSections.size());
    }

}